//! Independent OAS 3.2 HTTP contract oracles, through the public compilation seam.
//! Normative sources and deliberately unsupported resolver semantics are recorded
//! in docs/SDK-OAS32-CONTRACT.md. Expected tokens, statuses and addresses below
//! are literals from the fixtures, not values generated by the implementation.

use std::collections::BTreeMap;
use std::sync::Arc;

use serde_json::{Value, json};
use suspect_ir::contract::{
    Contract, ContractReader, ContractSeverity, HttpMethod, OAuthFlowKind, OperationKind,
    ParameterLocation, ParameterStyle, ResponseStatus, SchemaDialect, SourceId,
};
use suspect_low::Pointer;
use suspect_ref::WorkspaceBuilder;
use suspect_source::Uri;

fn fixture(files: &[(&str, Value)]) -> tempfile::TempDir {
    let dir = tempfile::tempdir().unwrap();
    for (name, value) in files {
        std::fs::write(
            dir.path().join(name),
            serde_json::to_vec_pretty(value).unwrap(),
        )
        .unwrap();
    }
    dir
}

fn load(dir: &tempfile::TempDir, entry: &str, reader: ContractReader) -> Contract {
    let workspace = Arc::new(WorkspaceBuilder::new().root(dir.path()).build().unwrap());
    Contract::from_workspace_with_reader(
        &workspace,
        &Uri::from_path(&dir.path().join(entry)).unwrap(),
        reader,
    )
    .unwrap()
}

fn id(uri: &Uri, pointer: &str) -> SourceId {
    SourceId::new(uri.clone(), Pointer::parse(pointer).unwrap())
}

fn located(contract: &Contract, source: &SourceId, code: &str) {
    let diagnostic = contract
        .diagnostics()
        .iter()
        .find(|d| &d.source == source && d.code == code)
        .unwrap_or_else(|| panic!("missing {code} at {source:?}: {:?}", contract.diagnostics()));
    assert_eq!(diagnostic.severity, ContractSeverity::Error);
    assert!(contract.source(&diagnostic.source).is_some());
    assert!(!diagnostic.at.is_empty(), "{diagnostic:?}");
}

fn clean(contract: &Contract) {
    assert!(!contract.has_errors(), "{:?}", contract.diagnostics());
}

fn both(dir: &tempfile::TempDir, check: impl Fn(&Contract)) {
    let left = load(dir, "api.json", ContractReader::Lossless);
    let right = load(dir, "api.json", ContractReader::Fast);
    check(&left);
    check(&right);
    parity(&left, &right);
}

fn parity(left: &Contract, right: &Contract) {
    assert_eq!(
        left.documents().collect::<Vec<_>>(),
        right.documents().collect::<Vec<_>>()
    );
    assert_eq!(left.schema_roots(), right.schema_roots());
    let schemas = |contract: &Contract| {
        contract
            .schemas()
            .map(|schema| {
                (
                    schema.id().clone(),
                    (
                        schema.raw().clone(),
                        schema.dialect().clone(),
                        schema.children().to_vec(),
                        schema.references().to_vec(),
                        schema.span(),
                    ),
                )
            })
            .collect::<BTreeMap<_, _>>()
    };
    assert_eq!(schemas(left), schemas(right));
    let diagnostics = |contract: &Contract| {
        contract
            .diagnostics()
            .iter()
            .map(|d| {
                (
                    d.source.clone(),
                    d.code,
                    d.severity,
                    d.message.clone(),
                    d.at.clone(),
                )
            })
            .collect::<Vec<_>>()
    };
    assert_eq!(diagnostics(left), diagnostics(right));
    let operations = |contract: &Contract| {
        contract
            .operations()
            .chain(contract.webhooks())
            .chain(contract.callbacks())
            .map(|op| {
                (
                    op.source().clone(),
                    op.path_item_source().clone(),
                    op.kind(),
                    op.method().as_str().to_owned(),
                    op.server_source().cloned(),
                    op.security_source().cloned(),
                    op.parameters()
                        .into_iter()
                        .map(|p| {
                            (
                                p.source().clone(),
                                p.resolved_source(),
                                p.name().map(str::to_owned),
                                p.location(),
                            )
                        })
                        .collect::<Vec<_>>(),
                )
            })
            .collect::<Vec<_>>()
    };
    assert_eq!(operations(left), operations(right));
}

fn api(path_item: Value) -> Value {
    json!({"openapi":"3.2.0","info":{"title":"OAS32 contract","version":"1"},"paths":{"/resource":path_item}})
}

fn querystring(name: &str) -> Value {
    json!({"name":name,"in":"querystring","content":{"application/json":{"schema":{"type":"object"}}}})
}

#[test]
fn query_and_additional_operations_preserve_case_sensitive_http_tokens() {
    let dir = fixture(&[(
        "api.json",
        api(json!({
            "get":{"responses":{"200":{}}},
            "query":{"requestBody":{"content":{"application/json":{"schema":{"type":"object"}}}},"responses":{"207":{}}},
            "additionalOperations":{
                "COPY":{"responses":{"204":{}}},
                "CONNECT":{"responses":{"200":{}}},
                "get":{"responses":{"201":{}}},
                "GeT":{"responses":{"202":{}}},
                "Query":{"responses":{"203":{}}},
                "x-purge":{"responses":{"205":{}}},
                "M-SEARCH":{"responses":{"206":{}}},
                "!#$%&'*+-.^_`|~":{"responses":{"208":{}}}
            }
        })),
    )]);
    both(&dir, |contract| {
        clean(contract);
        let expected = [
            (
                "!#$%&'*+-.^_`|~",
                "/paths/~1resource/additionalOperations/!#$%&'*+-.^_`|~0",
                208,
            ),
            (
                "CONNECT",
                "/paths/~1resource/additionalOperations/CONNECT",
                200,
            ),
            ("COPY", "/paths/~1resource/additionalOperations/COPY", 204),
            ("GET", "/paths/~1resource/get", 200),
            ("GeT", "/paths/~1resource/additionalOperations/GeT", 202),
            (
                "M-SEARCH",
                "/paths/~1resource/additionalOperations/M-SEARCH",
                206,
            ),
            ("QUERY", "/paths/~1resource/query", 207),
            ("Query", "/paths/~1resource/additionalOperations/Query", 203),
            ("get", "/paths/~1resource/additionalOperations/get", 201),
            (
                "x-purge",
                "/paths/~1resource/additionalOperations/x-purge",
                205,
            ),
        ];
        let operations = contract.operations().collect::<Vec<_>>();
        assert_eq!(operations.len(), expected.len());
        for (operation, (token, pointer, status)) in operations.iter().zip(expected) {
            assert_eq!(operation.method().as_str(), token);
            assert_eq!(operation.method().to_string(), token);
            let copied = operation.method();
            assert_eq!(copied, operation.method()); // borrowed method remains Copy
            assert_eq!(operation.source(), &id(contract.entry(), pointer));
            assert_eq!(operation.path_template(), Some("/resource"));
            assert_eq!(operation.kind(), OperationKind::Client);
            assert_eq!(
                operation.responses()[0].status(),
                Some(ResponseStatus::Exact(status))
            );
            assert!(contract.source_span(operation.source()).is_some());
        }
        assert_eq!(suspect_ir::Method::ALL.len(), 8);
        assert!(
            operations
                .iter()
                .find(|op| op.method().as_str() == "GET")
                .unwrap()
                .method()
                == suspect_ir::Method::Get
        );
        assert!(
            operations
                .iter()
                .find(|op| op.method().as_str() == "get")
                .unwrap()
                .method()
                != suspect_ir::Method::Get
        );
    });
    for invalid in [
        "", "GET ", "A B", "A/B", "A:B", "A(B)", "[GET]", "GÉT", "A\tB", "A\r\nB", "A\0B",
    ] {
        assert!(HttpMethod::parse(invalid).is_none(), "{invalid:?}");
    }
}

#[test]
fn invalid_methods_and_duplicate_fixed_methods_are_not_indexed_as_get() {
    let dir = fixture(&[(
        "api.json",
        api(json!({
            "get":{"responses":{"200":{}}},
            "additionalOperations":{
                "GET":{},"PUT":{},"POST":{},"DELETE":{},"OPTIONS":{},"HEAD":{},"PATCH":{},"TRACE":{},"QUERY":{},
                "":{},"A B":{},"GÉT":{},"A/B":{},"A:B":{},"A\nB":{},
                "COPY":false,"ok":{}
            }
        })),
    )]);
    both(&dir, |contract| {
        assert_eq!(
            contract
                .operations()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["GET", "ok"]
        );
        let root = id(contract.entry(), "/paths/~1resource/additionalOperations");
        for token in [
            "GET", "PUT", "POST", "DELETE", "OPTIONS", "HEAD", "PATCH", "TRACE", "QUERY",
        ] {
            located(contract, &root.child(token), "DUPLICATE_HTTP_METHOD");
        }
        for token in ["", "A B", "GÉT", "A/B", "A:B", "A\nB"] {
            located(contract, &root.child(token), "INVALID_HTTP_METHOD");
        }
        located(contract, &root.child("COPY"), "INVALID_HTTP_SHAPE");
    });
    for malformed in [Value::Null, json!(17), json!([]), json!("COPY")] {
        let dir = fixture(&[(
            "api.json",
            api(json!({"query":false,"additionalOperations":malformed})),
        )]);
        both(&dir, |contract| {
            assert_eq!(contract.operations().count(), 0);
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/query"),
                "INVALID_HTTP_SHAPE",
            );
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/additionalOperations"),
                "INVALID_HTTP_SHAPE",
            );
        });
    }
}

#[test]
fn querystring_name_identifies_overrides_but_never_implies_style_serialization() {
    let dir = fixture(&[(
        "api.json",
        json!({
            "openapi":"3.2.0","info":{"title":"Query string","version":"1"},
            "components":{"parameters":{"Whole":{"name":"criteria","in":"querystring","content":{"application/x-www-form-urlencoded":{"schema":{"type":"object","properties":{"term":{"type":"string"}}},"encoding":{"term":{"style":"form"}}}}}}},
            "paths":{"/resource":{"parameters":[{"$ref":"#/components/parameters/Whole"}],
                "query":{"parameters":[{"name":"criteria","in":"querystring","required":true,"content":{"application/json":{"schema":{"type":"object","required":["term"],"properties":{"term":{"type":"string"}}}}}}],"responses":{"200":{}}},
                "additionalOperations":{"SEARCH":{"responses":{"200":{}}}}
            }}
        }),
    )]);
    both(&dir, |contract| {
        clean(contract);
        let query = contract
            .operations()
            .find(|op| op.method().as_str() == "QUERY")
            .unwrap();
        let parameters = query.parameters();
        assert_eq!(parameters.len(), 1);
        let whole = &parameters[0];
        assert_eq!(whole.name(), Some("criteria"));
        assert_eq!(whole.location(), Some(ParameterLocation::Querystring));
        assert_eq!(whole.required(), Some(true));
        assert_eq!(
            whole.source().pointer(),
            "/paths/~1resource/query/parameters/0"
        );
        assert!(whole.schema().is_none());
        assert!(whole.effective_style().is_none());
        assert!(whole.effective_explode().is_none());
        assert_eq!(whole.content()[0].name(), "application/json");
        assert_eq!(
            whole.content()[0].schema().unwrap().id().pointer(),
            "/paths/~1resource/query/parameters/0/content/application~1json/schema"
        );
        assert_eq!(
            query.parameter_collections(),
            [
                id(contract.entry(), "/paths/~1resource/parameters"),
                id(contract.entry(), "/paths/~1resource/query/parameters"),
            ]
        );
        let inherited = contract
            .operations()
            .find(|op| op.method().as_str() == "SEARCH")
            .unwrap()
            .parameters()
            .remove(0);
        assert_eq!(inherited.name(), Some("criteria"));
        assert_eq!(
            inherited.source().pointer(),
            "/paths/~1resource/parameters/0"
        );
        assert_eq!(
            inherited.resolved_source().unwrap().pointer(),
            "/components/parameters/Whole"
        );
        assert_eq!(inherited.content()[0].encoding()[0].name(), "term");
    });
}

#[test]
fn querystring_uniqueness_and_query_exclusion_include_path_item_inheritance() {
    let query = json!({"name":"q","in":"query","schema":{"type":"string"}});
    for (shared, declared, expected, pointer) in [
        (
            vec![],
            vec![querystring("a"), querystring("b")],
            "DUPLICATE_QUERYSTRING_PARAMETER",
            "/paths/~1resource/query/parameters/1",
        ),
        (
            vec![querystring("a")],
            vec![querystring("b")],
            "DUPLICATE_QUERYSTRING_PARAMETER",
            "/paths/~1resource/query/parameters/0",
        ),
        (
            vec![query.clone()],
            vec![querystring("a")],
            "INVALID_QUERYSTRING_COMBINATION",
            "/paths/~1resource/query/parameters/0",
        ),
        (
            vec![querystring("a")],
            vec![query.clone()],
            "INVALID_QUERYSTRING_COMBINATION",
            "/paths/~1resource/parameters/0",
        ),
        (
            vec![],
            vec![querystring("a"), query],
            "INVALID_QUERYSTRING_COMBINATION",
            "/paths/~1resource/query/parameters/0",
        ),
        (
            vec![],
            vec![querystring("a"), querystring("a")],
            "DUPLICATE_PARAMETER",
            "/paths/~1resource/query/parameters/1",
        ),
    ] {
        let dir = fixture(&[(
            "api.json",
            api(json!({"parameters":shared,"query":{"parameters":declared}})),
        )]);
        both(&dir, |contract| {
            located(contract, &id(contract.entry(), pointer), expected)
        });
    }
    // Required string names may be empty. Serialization still uses the whole
    // query string; the empty name is a valid override identity.
    let dir = fixture(&[(
        "api.json",
        api(json!({"parameters":[querystring("")],"query":{"parameters":[querystring("")]}})),
    )]);
    both(&dir, |contract| {
        clean(contract);
        assert_eq!(contract.operations().next().unwrap().parameters().len(), 1);
    });
}

#[test]
fn querystring_requires_name_and_exactly_one_content_entry_and_forbids_schema_fields() {
    for (field, value, code) in [
        (
            "schema",
            json!({"type":"object"}),
            "INVALID_QUERYSTRING_PARAMETER",
        ),
        ("style", json!("form"), "INVALID_QUERYSTRING_PARAMETER"),
        ("explode", json!(false), "INVALID_QUERYSTRING_PARAMETER"),
        (
            "allowReserved",
            json!(false),
            "INVALID_QUERYSTRING_PARAMETER",
        ),
        ("allowEmptyValue", json!(false), "INVALID_PARAMETER_FIELD"),
        ("content", json!({}), "INVALID_PARAMETER_CONTENT"),
        (
            "content",
            json!({"application/json":{},"text/plain":{}}),
            "INVALID_PARAMETER_CONTENT",
        ),
        ("content", Value::Null, "INVALID_HTTP_SHAPE"),
        ("content", json!([]), "INVALID_HTTP_SHAPE"),
        ("name", json!(7), "INVALID_HTTP_SHAPE"),
    ] {
        let mut parameter = querystring("whole");
        parameter[field] = value;
        let dir = fixture(&[("api.json", api(json!({"query":{"parameters":[parameter]}})))]);
        both(&dir, |contract| {
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/query/parameters/0").child(field),
                code,
            );
            let parameter = contract.operations().next().unwrap().parameters().remove(0);
            assert!(parameter.effective_style().is_none());
            assert!(parameter.effective_explode().is_none());
        });
    }
    for removed in ["name", "content"] {
        let mut parameter = querystring("whole");
        parameter.as_object_mut().unwrap().remove(removed);
        let dir = fixture(&[("api.json", api(json!({"query":{"parameters":[parameter]}})))]);
        both(&dir, |contract| {
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/query/parameters/0"),
                "INVALID_HTTP_SHAPE",
            )
        });
    }
}

#[test]
fn split_media_references_keep_both_schema_roots_mounts_statuses_and_recursive_targets() {
    let dir = fixture(&[
        (
            "api.json",
            json!({
                "openapi":"3.2.0","info":{"title":"Split stream","version":"1"},
                "servers":[{"name":"root","url":"https://api.example.test"}],
                "security":[{"key":[]}],
                "components":{"securitySchemes":{"key":{"type":"apiKey","in":"header","name":"X-Key"}},"mediaTypes":{"Stream":{"$ref":"media.json#/Forward"}}},
                "paths":{"/events":{"$ref":"routes.json#/Route"}}
            }),
        ),
        (
            "routes.json",
            json!({"Route":{
                "servers":[{"name":"stream","url":"./stream"}],
                "parameters":[{"$ref":"http.json#/Whole"}],
                "query":{"requestBody":{"$ref":"http.json#/Body"},"responses":{"206":{"$ref":"http.json#/Reply"},"2XX":{},"default":{}}},
                "additionalOperations":{"Subscribe":{"servers":[],"security":[],"responses":{"202":{}}}}
            }}),
        ),
        (
            "http.json",
            json!({
                "Whole":{"name":"whole","in":"querystring","content":{"application/json-seq":{"$ref":"media.json#/Forward"}}},
                "Body":{"required":true,"content":{"application/json-seq":{"$ref":"media.json#/Forward"}}},
                "Reply":{"summary":"A sequence","headers":{"X-Sequence":{"content":{"application/json-seq":{"$ref":"media.json#/Forward"}}}},"content":{
                    "application/json-seq":{"$ref":"media.json#/Forward"},
                    "text/event-stream":{"$ref":"media.json#/Forward"}
                }}
            }),
        ),
        (
            "media.json",
            json!({
                "Forward":{"$ref":"#/Sequence","itemSchema":{"$ref":"must-not-load-ignored.json"}},
                "Sequence":{
                    "schema":{"type":"array","items":{"$ref":"schema.json#/$defs/Event"}},
                    "itemSchema":{"$ref":"schema.json#/$defs/Event"},
                    "examples":{"data":{"dataValue":[{"$ref":"must-not-load-instance.json","schema":{"$anchor":"Event"},"itemSchema":{"type":"null"}}],"serializedValue":"{\"data\":\"hello\"}\n"}}
                }
            }),
        ),
        (
            "schema.json",
            json!({"$defs":{"Event":{"$anchor":"Event","type":"object","properties":{"data":{"type":"string"},"next":{"$ref":"#Event"}}}}}),
        ),
    ]);
    both(&dir, |contract| {
        clean(contract);
        assert_eq!(contract.documents().count(), 5);
        let routes = Uri::from_path(&dir.path().join("routes.json")).unwrap();
        let http = Uri::from_path(&dir.path().join("http.json")).unwrap();
        let media = Uri::from_path(&dir.path().join("media.json")).unwrap();
        let schemas = Uri::from_path(&dir.path().join("schema.json")).unwrap();
        let operation = contract
            .operations()
            .find(|op| op.method().as_str() == "QUERY")
            .unwrap();
        assert_eq!(operation.source(), &id(&routes, "/Route/query"));
        assert_eq!(
            operation.path_item_source(),
            &id(contract.entry(), "/paths/~1events")
        );
        assert_eq!(operation.path_template(), Some("/events"));
        assert_eq!(
            operation.server_source(),
            Some(&id(&routes, "/Route/servers"))
        );
        assert_eq!(operation.effective_servers()[0].name(), Some("stream"));
        assert_eq!(operation.effective_servers()[0].url(), Some("./stream"));
        assert_eq!(
            operation.security_source(),
            Some(&id(contract.entry(), "/security"))
        );
        assert_eq!(
            operation.effective_security()[0].requirements()[0]
                .scheme()
                .unwrap()
                .parameter_name(),
            Some("X-Key")
        );
        let cleared = contract
            .operations()
            .find(|op| op.method().as_str() == "Subscribe")
            .unwrap();
        assert_eq!(
            cleared.server_source(),
            Some(&id(
                &routes,
                "/Route/additionalOperations/Subscribe/servers"
            ))
        );
        assert!(cleared.effective_servers()[0].is_default());
        assert!(cleared.effective_security().is_empty());
        let body = operation.request_body().unwrap();
        assert_eq!(body.source(), &id(&routes, "/Route/query/requestBody"));
        assert_eq!(body.resolved_source(), Some(id(&http, "/Body")));
        let content = body.content().remove(0);
        assert_eq!(
            content.source(),
            &id(&http, "/Body/content/application~1json-seq")
        );
        assert_eq!(content.resolved_source(), Some(id(&media, "/Sequence")));
        assert_eq!(
            contract.reference_target(content.source()),
            Some(&id(&media, "/Forward"))
        );
        assert_eq!(
            contract.reference_target(&id(&media, "/Forward")),
            Some(&id(&media, "/Sequence"))
        );
        assert!(
            contract
                .reference_target(&content.source().child("$ref"))
                .is_none()
        );
        assert_eq!(content.name(), "application/json-seq");
        assert_eq!(
            content.schema().unwrap().id(),
            &id(&media, "/Sequence/schema")
        );
        assert_eq!(
            content.item_schema().unwrap().id(),
            &id(&media, "/Sequence/itemSchema")
        );
        assert_eq!(
            content.item_schema().unwrap().references()[0].target,
            Some(id(&schemas, "/$defs/Event"))
        );
        let closure = contract.reachable_from(&content.schema_roots());
        let mut expected = vec![
            id(&media, "/Sequence/schema"),
            id(&media, "/Sequence/schema/items"),
            id(&media, "/Sequence/itemSchema"),
            id(&schemas, "/$defs/Event"),
            id(&schemas, "/$defs/Event/properties/data"),
            id(&schemas, "/$defs/Event/properties/next"),
        ];
        expected.sort();
        assert_eq!(closure, expected);
        let parameter = operation.parameters().remove(0);
        assert_eq!(parameter.location(), Some(ParameterLocation::Querystring));
        assert_eq!(
            parameter.content()[0].schema_roots(),
            content.schema_roots()
        );
        let replies = operation.responses();
        assert_eq!(
            replies.iter().map(|r| r.status()).collect::<Vec<_>>(),
            [
                Some(ResponseStatus::Exact(206)),
                Some(ResponseStatus::Range(2)),
                Some(ResponseStatus::Default)
            ]
        );
        assert_eq!(
            replies[0].source(),
            &id(&routes, "/Route/query/responses/206")
        );
        assert_eq!(replies[0].summary(), Some("A sequence"));
        assert_eq!(
            replies[0]
                .content()
                .iter()
                .map(|m| m.name())
                .collect::<Vec<_>>(),
            ["application/json-seq", "text/event-stream"]
        );
        assert_eq!(
            replies[0].headers()[0].content()[0]
                .item_schema()
                .unwrap()
                .id(),
            content.item_schema().unwrap().id()
        );
        assert_eq!(contract.media_types()[0].name(), "Stream");
        assert_eq!(
            contract.media_types()[0].resolved_source(),
            Some(id(&media, "/Sequence"))
        );
        assert!(
            contract
                .schema(&id(&media, "/Forward/itemSchema"))
                .is_none()
        );
        assert!(
            !contract
                .schemas()
                .any(|s| s.id().pointer().contains("/dataValue"))
        );
        let example = content.examples().remove(0);
        assert!(example.value().is_none());
        assert_eq!(
            example.data_value().unwrap()[0]["$ref"],
            "must-not-load-instance.json"
        );
        assert_eq!(
            example.data_value_source(),
            Some(id(&media, "/Sequence/examples/data/dataValue"))
        );
        assert_eq!(example.serialized_value(), Some("{\"data\":\"hello\"}\n"));
        assert_eq!(
            example.serialized_value_source(),
            Some(id(&media, "/Sequence/examples/data/serializedValue"))
        );
    });
}

#[test]
fn item_schemas_and_positional_nested_encoding_header_schemas_are_real_graph_positions() {
    let dir = fixture(&[(
        "api.json",
        api(json!({"query":{
            "parameters":[{"name":"chunks","in":"header","content":{"application/json-seq":{"itemSchema":false}}}],
            "requestBody":{"content":{"multipart/mixed":{
                "itemSchema":{"type":"string"},
                "prefixEncoding":[
                    {"headers":{"X-Chunk":{"schema":{"type":"integer"}}}},
                    {"encoding":{"part":{"headers":{"X-Part":{"content":{"application/json-seq":{"itemSchema":{"type":"number"}}}}}}}}
                ],
                "itemEncoding":{"prefixEncoding":[{"headers":{"X-Nested":{"schema":true}}}],"itemEncoding":{"headers":{"X-Tail":{"schema":{"type":"boolean"}}}}},
                "examples":{"data":{"dataValue":{"schema":{"$ref":"never-load.json"},"itemSchema":{"$ref":"never-load.json"},"prefixEncoding":[{"headers":{"X-Fake":{"schema":null}}}]}}}
            }}},
            "responses":{"200":{"content":{"application/x-ndjson":{"schema":{"type":"array"},"itemSchema":{"type":"null"}}}}}
        }})),
    )]);
    both(&dir, |contract| {
        clean(contract);
        let expected = [
            "/paths/~1resource/query/parameters/0/content/application~1json-seq/itemSchema",
            "/paths/~1resource/query/requestBody/content/multipart~1mixed/itemSchema",
            "/paths/~1resource/query/requestBody/content/multipart~1mixed/prefixEncoding/0/headers/X-Chunk/schema",
            "/paths/~1resource/query/requestBody/content/multipart~1mixed/prefixEncoding/1/encoding/part/headers/X-Part/content/application~1json-seq/itemSchema",
            "/paths/~1resource/query/requestBody/content/multipart~1mixed/itemEncoding/prefixEncoding/0/headers/X-Nested/schema",
            "/paths/~1resource/query/requestBody/content/multipart~1mixed/itemEncoding/itemEncoding/headers/X-Tail/schema",
            "/paths/~1resource/query/responses/200/content/application~1x-ndjson/schema",
            "/paths/~1resource/query/responses/200/content/application~1x-ndjson/itemSchema",
        ];
        assert_eq!(contract.schema_roots().len(), expected.len());
        for pointer in expected {
            let source = id(contract.entry(), pointer);
            assert!(
                contract.schema_roots().contains(&source),
                "missing {pointer}"
            );
            assert!(contract.schema(&source).is_some());
            assert!(!contract.source_span(&source).unwrap().is_empty());
        }
        assert_eq!(contract.schemas().count(), expected.len());
        let op = contract.operations().next().unwrap();
        let media = op.request_body().unwrap().content().remove(0);
        assert!(media.schema().is_none());
        assert_eq!(media.prefix_encoding().len(), 2);
        assert_eq!(
            media.prefix_encoding()[0].headers()[0]
                .schema()
                .unwrap()
                .raw()["type"],
            "integer"
        );
        assert_eq!(media.prefix_encoding()[1].encoding()[0].name(), "part");
        assert_eq!(
            media.item_encoding().unwrap().prefix_encoding()[0].headers()[0]
                .schema()
                .unwrap()
                .raw(),
            &json!(true)
        );
        assert_eq!(
            media
                .item_encoding()
                .unwrap()
                .item_encoding()
                .unwrap()
                .headers()[0]
                .name(),
            "X-Tail"
        );
        assert_eq!(
            op.parameters()[0].content()[0].item_schema().unwrap().raw(),
            &json!(false)
        );
    });
}

#[test]
fn item_schema_anchors_are_forward_resolved_without_instance_anchor_candidates() {
    let dir = fixture(&[(
        "api.json",
        json!({
            "openapi":"3.2.0","info":{"title":"Item anchors","version":"1"},
            "components":{"mediaTypes":{
                "AUse":{"itemSchema":{"$ref":"#It%65m"}},
                "ZItem":{"itemSchema":{"$anchor":"Item","type":"object","properties":{"next":{"$ref":"#Item"}}}},
            "ZLiteral":{"example":{"$anchor":"Item","schema":{"$anchor":"Item"}}},
            "ZInstances":{"examples":{"data":{"dataValue":{"$anchor":"Item","itemSchema":{"$anchor":"Item"}},"serializedValue":"{\"$anchor\":\"Item\"}"}}}
            }}
        }),
    )]);
    both(&dir, |contract| {
        clean(contract);
        let use_id = id(contract.entry(), "/components/mediaTypes/AUse/itemSchema");
        let target_id = id(contract.entry(), "/components/mediaTypes/ZItem/itemSchema");
        assert_eq!(
            contract.schema(&use_id).unwrap().references()[0].target,
            Some(target_id.clone())
        );
        assert_eq!(
            contract
                .schema(&target_id.child("properties").child("next"))
                .unwrap()
                .references()[0]
                .target,
            Some(target_id)
        );
        assert_eq!(contract.reachable_from(&[use_id]).len(), 3);
        assert_eq!(contract.schemas().count(), 3);
    });
}

#[test]
fn callbacks_and_webhooks_keep_direction_and_exact_additional_method_identity() {
    let dir = fixture(&[(
        "api.json",
        json!({
            "openapi":"3.2.0","info":{"title":"Directions","version":"1"},
            "paths":{"/subscribe":{"query":{"operationId":"subscribe","callbacks":{"x-notification":{"{$request.querystring}":{
                "query":{"operationId":"callbackQuery","requestBody":{"content":{"application/json-seq":{"itemSchema":{"type":"string"}}}}},
                "additionalOperations":{"Deliver":{"operationId":"deliver"}}
            }}}}}},
            "webhooks":{"x-event":{"query":{"operationId":"webhookQuery"},"additionalOperations":{"notify":{"operationId":"notify"}}}}
        }),
    )]);
    both(&dir, |contract| {
        clean(contract);
        assert_eq!(
            contract
                .operations()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["QUERY"]
        );
        assert_eq!(
            contract
                .webhooks()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["QUERY", "notify"]
        );
        assert_eq!(
            contract
                .callbacks()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["Deliver", "QUERY"]
        );
        let parent = id(contract.entry(), "/paths/~1subscribe/query");
        for webhook in contract.webhooks() {
            assert_eq!(webhook.kind(), OperationKind::Webhook);
            assert_eq!(webhook.webhook_name(), Some("x-event"));
            assert!(webhook.path_template().is_none());
            assert!(webhook.callback_parent().is_none());
        }
        for callback in contract.callbacks() {
            assert_eq!(callback.kind(), OperationKind::Callback);
            assert_eq!(callback.callback_parent(), Some(&parent));
            assert_eq!(callback.callback_name(), Some("x-notification"));
            assert_eq!(
                callback.callback_expression(),
                Some("{$request.querystring}")
            );
            assert!(callback.path_template().is_none());
        }
        let callback = contract
            .callbacks()
            .find(|op| op.method().as_str() == "QUERY")
            .unwrap();
        assert_eq!(
            callback.request_body().unwrap().content()[0]
                .item_schema()
                .unwrap()
                .raw()["type"],
            "string"
        );
    });
}

#[test]
fn response_status_identity_and_optional_32_descriptions_have_literal_oracles() {
    let dir = fixture(&[(
        "api.json",
        api(json!({"query":{"responses":{
            "100":{},"199":{},"200":{},"299":{},"599":{},"1XX":{},"2XX":{},"3XX":{},"4XX":{},"5XX":{},"default":{},
            "99":{},"600":{},"0200":{},"2xx":{},"20X":{}," 200":{},"2XX ":{},"x-extra":{"schema":"instance metadata"}
        }}})),
    )]);
    both(&dir, |contract| {
        let operation = contract.operations().next().unwrap();
        let responses = operation.responses();
        let expected = [
            ("100", ResponseStatus::Exact(100)),
            ("199", ResponseStatus::Exact(199)),
            ("200", ResponseStatus::Exact(200)),
            ("299", ResponseStatus::Exact(299)),
            ("599", ResponseStatus::Exact(599)),
            ("1XX", ResponseStatus::Range(1)),
            ("2XX", ResponseStatus::Range(2)),
            ("3XX", ResponseStatus::Range(3)),
            ("4XX", ResponseStatus::Range(4)),
            ("5XX", ResponseStatus::Range(5)),
            ("default", ResponseStatus::Default),
        ];
        for (key, status) in expected {
            let response = responses
                .iter()
                .find(|response| response.status_key() == key)
                .unwrap();
            assert_eq!(response.status(), Some(status));
            assert_eq!(
                response.source(),
                &id(contract.entry(), "/paths/~1resource/query/responses").child(key)
            );
        }
        for key in ["99", "600", "0200", "2xx", "20X", " 200", "2XX "] {
            assert_eq!(
                responses
                    .iter()
                    .find(|r| r.status_key() == key)
                    .unwrap()
                    .status(),
                None
            );
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/query/responses").child(key),
                "INVALID_RESPONSE_STATUS",
            );
        }
        assert_eq!(responses.len(), 18);
        assert_eq!(contract.diagnostics().len(), 7);
    });
    for (version, missing_description_is_error) in
        [("3.0.4", true), ("3.1.2", true), ("3.2.0", false)]
    {
        let mut value = api(json!({"get":{"responses":{"200":{}}}}));
        value["openapi"] = json!(version);
        let dir = fixture(&[("api.json", value)]);
        both(&dir, |contract| {
            assert_eq!(contract.has_errors(), missing_description_is_error);
            if missing_description_is_error {
                located(
                    contract,
                    &id(contract.entry(), "/paths/~1resource/get/responses/200"),
                    "INVALID_HTTP_SHAPE",
                );
            }
        });
    }
}

#[test]
fn http_metadata_fields_are_32_only_and_are_typed_without_invented_defaults() {
    for version in ["3.0.4", "3.1.2", "3.2.0"] {
        let dir = fixture(&[
            (
                "api.json",
                json!({
                    "openapi":version,"info":{"title":"Version matrix","version":"1"},
                    "servers":[{"url":"https://api.example.test","name":"production"}],
                    "security":[{"oauth":[]}],
                    "components":{
                        "mediaTypes":{"Sequence":{"itemSchema":{"type":"string"}}},
                        "securitySchemes":{"oauth":{"type":"oauth2","deprecated":false,"oauth2MetadataUrl":"https://auth.example.test/.well-known/oauth-authorization-server","flows":{
                            "deviceAuthorization":{"deviceAuthorizationUrl":"https://auth.example.test/device","tokenUrl":"https://auth.example.test/token","scopes":{}}
                        }}}
                    },
                    "paths":{"/resource":{
                        "query":{},"additionalOperations":{"copy":{}},
                        "get":{"parameters":[
                            {"name":"session","in":"cookie","style":"cookie","schema":{"type":"string"}},
                            querystring("whole")
                        ],"responses":{"200":{"description":"OK","summary":"Result","content":{
                            "multipart/mixed":{"schema":{"type":"array"},"itemSchema":{"type":"string"},"prefixEncoding":[],"itemEncoding":{},"examples":{"data":{"dataValue":["x"],"serializedValue":"x"}}},
                            "application/json-seq":{"$ref":"media.json#/Sequence"}
                        }}}}
                    }}
                }),
            ),
            ("media.json", json!({"Sequence":{"itemSchema":true}})),
        ]);
        both(&dir, |contract| {
            let modern = version == "3.2.0";
            assert_eq!(
                contract.has_errors(),
                !modern,
                "{:?}",
                contract.diagnostics()
            );
            assert_eq!(contract.operations().count(), if modern { 3 } else { 1 });
            assert_eq!(contract.documents().count(), if modern { 2 } else { 1 });
            assert_eq!(contract.media_types().len(), usize::from(modern));
            let operation = contract
                .operations()
                .find(|op| op.method().as_str() == "GET")
                .unwrap();
            assert_eq!(
                operation.effective_servers()[0].name(),
                modern.then_some("production")
            );
            let cookie = operation.parameters().remove(0);
            assert_eq!(cookie.style(), modern.then_some(ParameterStyle::Cookie));
            assert_eq!(cookie.effective_explode(), modern.then_some(true));
            assert_eq!(
                operation.parameters()[1].location(),
                modern.then_some(ParameterLocation::Querystring)
            );
            let response = operation.responses().remove(0);
            assert_eq!(response.summary(), modern.then_some("Result"));
            let multipart = response
                .content()
                .into_iter()
                .find(|m| m.name() == "multipart/mixed")
                .unwrap();
            assert_eq!(multipart.item_schema().is_some(), modern);
            assert_eq!(multipart.item_encoding().is_some(), modern);
            assert_eq!(
                multipart.examples()[0].data_value(),
                modern.then_some(&json!(["x"]))
            );
            assert_eq!(
                multipart.examples()[0].serialized_value(),
                modern.then_some("x")
            );
            let oauth = contract.security_schemes().remove(0);
            assert_eq!(oauth.deprecated(), modern.then_some(false));
            assert_eq!(
                oauth.oauth2_metadata_url(),
                modern
                    .then_some("https://auth.example.test/.well-known/oauth-authorization-server")
            );
            let flow = oauth.flows().remove(0);
            assert_eq!(
                flow.kind(),
                modern.then_some(OAuthFlowKind::DeviceAuthorization)
            );
            assert_eq!(
                flow.device_authorization_url(),
                modern.then_some("https://auth.example.test/device")
            );
            if !modern {
                for pointer in [
                    "/servers/0/name",
                    "/components/mediaTypes",
                    "/paths/~1resource/query",
                    "/paths/~1resource/additionalOperations",
                    "/paths/~1resource/get/responses/200/summary",
                    "/paths/~1resource/get/responses/200/content/application~1json-seq/$ref",
                    "/paths/~1resource/get/responses/200/content/multipart~1mixed/itemSchema",
                    "/paths/~1resource/get/responses/200/content/multipart~1mixed/prefixEncoding",
                    "/paths/~1resource/get/responses/200/content/multipart~1mixed/itemEncoding",
                    "/paths/~1resource/get/responses/200/content/multipart~1mixed/examples/data/dataValue",
                    "/paths/~1resource/get/responses/200/content/multipart~1mixed/examples/data/serializedValue",
                    "/components/securitySchemes/oauth/deprecated",
                    "/components/securitySchemes/oauth/oauth2MetadataUrl",
                ] {
                    located(
                        contract,
                        &id(contract.entry(), pointer),
                        "UNSUPPORTED_HTTP_FIELD",
                    );
                }
                located(
                    contract,
                    &id(contract.entry(), "/paths/~1resource/get/parameters/0/style"),
                    "INVALID_PARAMETER_STYLE",
                );
                located(
                    contract,
                    &id(contract.entry(), "/paths/~1resource/get/parameters/1/in"),
                    "UNSUPPORTED_PARAMETER_LOCATION",
                );
                located(
                    contract,
                    &id(
                        contract.entry(),
                        "/components/securitySchemes/oauth/flows/deviceAuthorization",
                    ),
                    "UNSUPPORTED_OAUTH_FLOW",
                );
                assert!(
                    !contract
                        .schemas()
                        .any(|s| s.id().pointer().ends_with("/itemSchema"))
                );
            }
        });
    }
}

#[test]
fn declaring_document_versions_survive_ref_mounts_and_propagate_to_standalone_media() {
    let dir = fixture(&[
        (
            "api.json",
            json!({"openapi":"3.1.2","info":{"title":"Entry","version":"1"},"paths":{"/remote":{"$ref":"remote.json#/paths/~1route"}}}),
        ),
        (
            "remote.json",
            json!({"openapi":"3.2.0","info":{"title":"Remote","version":"1"},"paths":{"/route":{
                "query":{"requestBody":{"content":{"application/json-seq":{"$ref":"media.json#/Sequence"}}},"parameters":[querystring("whole")]},
                "additionalOperations":{"M-SEARCH":{}}
            }}}),
        ),
        (
            "media.json",
            json!({"Sequence":{"itemSchema":{"type":"string"}}}),
        ),
    ]);
    both(&dir, |contract| {
        clean(contract);
        assert_eq!(contract.openapi_version(), "3.1.2");
        assert_eq!(
            contract
                .operations()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["M-SEARCH", "QUERY"]
        );
        let query = contract
            .operations()
            .find(|op| op.method().as_str() == "QUERY")
            .unwrap();
        assert_eq!(contract.openapi_version_at(query.source()), "3.2.0");
        assert_eq!(query.path_item_source().document(), contract.entry());
        assert_eq!(
            query.parameters()[0].location(),
            Some(ParameterLocation::Querystring)
        );
        let media = query.request_body().unwrap().content().remove(0);
        let schema = media.item_schema().unwrap();
        assert_eq!(
            schema.id(),
            &id(
                &Uri::from_path(&dir.path().join("media.json")).unwrap(),
                "/Sequence/itemSchema"
            )
        );
        assert_eq!(contract.openapi_version_at(schema.id()), "3.2.0");
        assert_eq!(
            schema.dialect(),
            &SchemaDialect::Uri("https://spec.openapis.org/oas/3.1/dialect/base".to_owned())
        );
    });

    let dir = fixture(&[
        (
            "api.json",
            json!({"openapi":"3.2.0","info":{"title":"Entry","version":"1"},"paths":{"/remote":{"$ref":"remote.json#/paths/~1route"}}}),
        ),
        (
            "remote.json",
            json!({"openapi":"3.1.2","info":{"title":"Remote","version":"1"},"paths":{"/route":{
                "query":{},"additionalOperations":{"COPY":{}},
                "get":{"responses":{"200":{"description":"OK","content":{"application/json-seq":{"itemSchema":{"$ref":"never-load.json"}}}}}}
            }}}),
        ),
    ]);
    both(&dir, |contract| {
        assert_eq!(
            contract
                .operations()
                .map(|op| op.method().as_str())
                .collect::<Vec<_>>(),
            ["GET"]
        );
        let remote = Uri::from_path(&dir.path().join("remote.json")).unwrap();
        for pointer in [
            "/paths/~1route/query",
            "/paths/~1route/additionalOperations",
            "/paths/~1route/get/responses/200/content/application~1json-seq/itemSchema",
        ] {
            located(contract, &id(&remote, pointer), "UNSUPPORTED_HTTP_FIELD");
        }
        assert_eq!(contract.documents().count(), 2);
        assert_eq!(contract.schemas().count(), 0);
    });
}

#[test]
fn reusing_one_standalone_fragment_with_conflicting_versions_is_explicit() {
    let dir = fixture(&[
        (
            "api.json",
            json!({"openapi":"3.2.0","info":{"title":"Entry","version":"1"},"paths":{"/old":{"$ref":"old.json#/paths/~1route"},"/new":{"$ref":"new.json#/paths/~1route"}}}),
        ),
        (
            "old.json",
            json!({"openapi":"3.1.2","info":{"title":"Old","version":"1"},"paths":{"/route":{"get":{"responses":{"200":{"description":"OK","content":{"application/json":{"$ref":"shared.json#/Media"}}}}}}}}),
        ),
        (
            "new.json",
            json!({"openapi":"3.2.0","info":{"title":"New","version":"1"},"paths":{"/route":{"get":{"responses":{"200":{"content":{"application/json":{"$ref":"shared.json#/Media"}}}}}}}}),
        ),
        ("shared.json", json!({"Media":{"schema":{"type":"string"}}})),
    ]);
    // A Media Type reference is itself a 3.2-only declaration in old.json;
    // the 3.1 source must not acquire 3.2 reference semantics through another use.
    both(&dir, |contract| {
        located(
            contract,
            &id(
                &Uri::from_path(&dir.path().join("old.json")).unwrap(),
                "/paths/~1route/get/responses/200/content/application~1json/$ref",
            ),
            "UNSUPPORTED_HTTP_FIELD",
        );
        let old = contract
            .operations()
            .find(|op| op.path_template() == Some("/old"))
            .unwrap();
        assert!(old.responses()[0].content()[0].schema().is_none());
    });

    let dir = fixture(&[
        (
            "api.json",
            json!({"openapi":"3.2.0","info":{"title":"Entry","version":"1"},"paths":{"/old":{"$ref":"old.json#/paths/~1route"},"/new":{"$ref":"new.json#/paths/~1route"}}}),
        ),
        (
            "old.json",
            json!({"openapi":"3.1.2","info":{"title":"Old","version":"1"},"paths":{"/route":{"get":{"requestBody":{"$ref":"shared.json#/Body"}}}}}),
        ),
        (
            "new.json",
            json!({"openapi":"3.2.0","info":{"title":"New","version":"1"},"paths":{"/route":{"query":{"requestBody":{"$ref":"shared.json#/Body"}}}}}),
        ),
        (
            "shared.json",
            json!({"Body":{"content":{"application/json":{"schema":{"type":"string"}}}}}),
        ),
    ]);
    both(&dir, |contract| {
        located(
            contract,
            &id(
                &Uri::from_path(&dir.path().join("shared.json")).unwrap(),
                "/Body",
            ),
            "AMBIGUOUS_OPENAPI_CONTEXT",
        )
    });
}

#[test]
fn malformed_media_references_and_reference_cycles_are_located() {
    for (declaration, target, code, pointer) in [
        (
            json!({"$ref":null}),
            json!({}),
            "invalid-reference",
            "/paths/~1resource/query/responses/200/content/application~1json-seq",
        ),
        (
            json!({"$ref":7}),
            json!({}),
            "invalid-reference",
            "/paths/~1resource/query/responses/200/content/application~1json-seq",
        ),
        (
            json!({"$ref":"missing.json"}),
            json!({}),
            "invalid-reference",
            "/paths/~1resource/query/responses/200/content/application~1json-seq",
        ),
        (
            json!({"$ref":"#/components/mediaTypes/Bad"}),
            json!(false),
            "INVALID_HTTP_SHAPE",
            "/components/mediaTypes/Bad",
        ),
        (
            json!({"$ref":"#/components/mediaTypes/Bad"}),
            json!({"$ref":"#/components/mediaTypes/Bad"}),
            "HTTP_REFERENCE_CYCLE",
            "/components/mediaTypes/Bad/$ref",
        ),
    ] {
        let mut value = api(
            json!({"query":{"responses":{"200":{"content":{"application/json-seq":declaration}}}}}),
        );
        value["components"] = json!({"mediaTypes":{"Bad":target}});
        let dir = fixture(&[("api.json", value)]);
        both(&dir, |contract| {
            located(contract, &id(contract.entry(), pointer), code);
            let media = contract.operations().next().unwrap().responses()[0]
                .content()
                .remove(0);
            assert!(media.schema().is_none());
            assert!(media.item_schema().is_none());
            assert!(media.raw().get("$ref").is_some());
        });
    }
}

#[test]
fn malformed_32_metadata_is_validated_at_its_actual_field_source() {
    let base = json!({
        "openapi":"3.2.0","info":{"title":"Declarations","version":"1"},
        "servers":[{"url":"https://api.example.test","name":7}],
        "components":{"securitySchemes":{"oauth":{"type":"oauth2","deprecated":"yes","oauth2MetadataUrl":false,"flows":{"deviceAuthorization":{"deviceAuthorizationUrl":false,"tokenUrl":"https://auth.example.test/token","scopes":[]}}}}},
        "paths":{"/resource":{"query":{"responses":{"200":{"summary":[],"description":null,"content":{"multipart/mixed":{
            "itemSchema":null,"encoding":{},"prefixEncoding":{},"itemEncoding":false,
            "examples":{
                "dataAndValue":{"dataValue":null,"value":null},
                "serializedAndValue":{"serializedValue":"null","value":null},
                "serializedAndExternal":{"serializedValue":"null","externalValue":"example.txt"},
                "badSerialized":{"serializedValue":42}
            }
        }}}}}}}
    });
    let dir = fixture(&[("api.json", base)]);
    both(&dir, |contract| {
        for pointer in [
            "/servers/0/name",
            "/components/securitySchemes/oauth/deprecated",
            "/components/securitySchemes/oauth/oauth2MetadataUrl",
            "/components/securitySchemes/oauth/flows/deviceAuthorization/deviceAuthorizationUrl",
            "/components/securitySchemes/oauth/flows/deviceAuthorization/scopes",
            "/paths/~1resource/query/responses/200/summary",
            "/paths/~1resource/query/responses/200/description",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/prefixEncoding",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/itemEncoding",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/examples/badSerialized/serializedValue",
        ] {
            located(
                contract,
                &id(contract.entry(), pointer),
                "INVALID_HTTP_SHAPE",
            );
        }
        for pointer in [
            "/paths/~1resource/query/responses/200/content/multipart~1mixed",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/examples/dataAndValue",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/examples/serializedAndValue",
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/examples/serializedAndExternal",
        ] {
            located(
                contract,
                &id(contract.entry(), pointer),
                "INVALID_HTTP_COMBINATION",
            );
        }
        let source = id(
            contract.entry(),
            "/paths/~1resource/query/responses/200/content/multipart~1mixed/itemSchema",
        );
        located(contract, &source, "invalid-schema");
        assert_eq!(contract.schema(&source).unwrap().raw(), &Value::Null);
    });
    for value in [
        json!({"prefixEncoding":[]}),
        json!({"schema":{"type":"string"},"itemEncoding":{}}),
    ] {
        let dir = fixture(&[(
            "api.json",
            api(json!({"query":{"requestBody":{"content":{"multipart/mixed":value}}}})),
        )]);
        both(&dir, |contract| {
            assert!(
                contract
                    .diagnostics()
                    .iter()
                    .any(|d| d.code == "INVALID_ENCODING_SCHEMA")
            )
        });
    }
    for media_types in [json!([]), json!({"Bad/Name":{}}), json!({"Null":null})] {
        let dir = fixture(&[(
            "api.json",
            json!({"openapi":"3.2.0","info":{"title":"Bad component","version":"1"},"components":{"mediaTypes":media_types}}),
        )]);
        both(&dir, |contract| assert!(contract.has_errors()));
    }
}

#[test]
fn absent_yaml_item_schema_and_malformed_json_schema_slots_are_not_dropped() {
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("api.yaml"), "openapi: 3.2.0\ninfo: {title: Missing, version: '1'}\npaths:\n  /events:\n    query:\n      responses:\n        '200':\n          content:\n            application/json-seq:\n              itemSchema:\n").unwrap();
    let left = load(&dir, "api.yaml", ContractReader::Lossless);
    let right = load(&dir, "api.yaml", ContractReader::Fast);
    for contract in [&left, &right] {
        let source = id(
            contract.entry(),
            "/paths/~1events/query/responses/200/content/application~1json-seq/itemSchema",
        );
        located(contract, &source, "invalid-schema");
        let schema = contract.operations().next().unwrap().responses()[0].content()[0]
            .item_schema()
            .unwrap();
        assert_eq!(schema.id(), &source);
        assert_eq!(schema.raw(), &Value::Null);
        assert!(!schema.span().is_empty());
    }
    parity(&left, &right);
    for malformed in [Value::Null, json!(17), json!([]), json!("schema")] {
        let dir = fixture(&[(
            "api.json",
            api(
                json!({"query":{"responses":{"200":{"content":{"application/json-seq":{"itemSchema":malformed}}}}}}),
            ),
        )]);
        both(&dir, |contract| {
            located(
                contract,
                &id(
                    contract.entry(),
                    "/paths/~1resource/query/responses/200/content/application~1json-seq/itemSchema",
                ),
                "invalid-schema",
            )
        });
    }
}

#[test]
fn self_and_schema_id_are_scoped_without_rewriting_physical_identity() {
    for declaration in [
        json!("https://canonical.example.test/openapi.json"),
        Value::Null,
    ] {
        let mut value = api(
            json!({"query":{"requestBody":{"$ref":"must-not-load-under-retrieval-base.json"}}}),
        );
        value["$self"] = declaration.clone();
        let dir = fixture(&[("api.json", value)]);
        both(&dir, |contract| {
            let root = id(contract.entry(), "");
            if declaration.is_string() {
                assert_eq!(
                    contract.resource(&root).unwrap().canonical_uri(),
                    "https://canonical.example.test/openapi.json"
                );
                assert_eq!(contract.resource(&root).unwrap().source(), &root);
                assert!(
                    !contract
                        .diagnostics()
                        .iter()
                        .any(|d| d.source == root.child("$self"))
                );
            } else {
                located(contract, &root.child("$self"), "invalid-openapi-self");
                assert!(contract.resource_scope(&root).is_none());
            }
            located(
                contract,
                &id(contract.entry(), "/paths/~1resource/query/requestBody"),
                "invalid-reference",
            );
            assert!(
                contract
                    .operations()
                    .next()
                    .unwrap()
                    .request_body()
                    .unwrap()
                    .resolved_source()
                    .is_none()
            );
            assert_eq!(contract.documents().count(), 1);
        });
    }
    let dir = fixture(&[(
        "api.json",
        api(
            json!({"query":{"responses":{"200":{"content":{"application/json-seq":{"itemSchema":{
                "$id":"https://canonical.example.test/item", "$ref":"#Item", "$anchor":"Item"
            }}}}}}}),
        ),
    )]);
    both(&dir, |contract| {
        clean(contract);
        let source = id(
            contract.entry(),
            "/paths/~1resource/query/responses/200/content/application~1json-seq/itemSchema",
        );
        assert_eq!(
            contract.resource(&source).unwrap().canonical_uri(),
            "https://canonical.example.test/item"
        );
        assert_eq!(
            contract.schema(&source).unwrap().references()[0].target,
            Some(source.clone())
        );
        assert_eq!(contract.reachable_from(&[source]).len(), 1);
    });
    // The same words in a schema annotation or instance do not establish OAS
    // document identity, embedded resources, or schema anchor candidates.
    let mut value = api(
        json!({"query":{"responses":{"200":{"content":{"application/json-seq":{"itemSchema":{
            "$self":"https://annotation.example.test", "$anchor":"Item", "type":"object",
            "default":{"$id":"wrong.json","$self":"wrong.json","$anchor":"Item"},
            "properties":{"next":{"$ref":"#Item"}}
        }}}}}}}),
    );
    value["$id"] = json!("wrong-non-schema-root.json");
    let dir = fixture(&[("api.json", value)]);
    both(&dir, |contract| {
        clean(contract);
        assert_eq!(contract.documents().count(), 1);
        let source = id(
            contract.entry(),
            "/paths/~1resource/query/responses/200/content/application~1json-seq/itemSchema",
        );
        assert_eq!(
            contract
                .schema(&source.child("properties").child("next"))
                .unwrap()
                .references()[0]
                .target,
            Some(source)
        );
        assert!(
            contract
                .diagnostics()
                .iter()
                .any(|d| d.code == "unknown-schema-keyword")
        );
    });
}

#[test]
fn a_nested_schema_reference_retains_the_declared_media_schema_dialect_and_id_scope() {
    let dir = fixture(&[
        (
            "api.json",
            api(
                json!({"query":{"requestBody":{"content":{"application/json-seq":{
                    "itemSchema":{"$ref":"remote.json#/components/mediaTypes/Stream/itemSchema/$defs/Nested"}
                }}}}}),
            ),
        ),
        (
            "remote.json",
            json!({"openapi":"3.2.0","info":{"title":"Remote","version":"1"},"components":{"mediaTypes":{"Stream":{
                "itemSchema":{"$schema":"https://json-schema.org/draft/2020-12/schema","$defs":{"Nested":{"type":"string"}}}
            }}}}),
        ),
    ]);
    both(&dir, |contract| {
        clean(contract);
        let remote = Uri::from_path(&dir.path().join("remote.json")).unwrap();
        let nested = id(
            &remote,
            "/components/mediaTypes/Stream/itemSchema/$defs/Nested",
        );
        assert_eq!(
            contract.schema(&nested).unwrap().dialect(),
            &SchemaDialect::Uri("https://json-schema.org/draft/2020-12/schema".to_owned())
        );
        assert_eq!(contract.schemas().count(), 2);
        assert!(
            contract
                .schema(&id(&remote, "/components/mediaTypes/Stream/itemSchema"))
                .is_none()
        );
    });
    let dir = fixture(&[
        (
            "api.json",
            api(
                json!({"query":{"requestBody":{"content":{"application/json-seq":{
                    "itemSchema":{"$ref":"schema.json#/$defs/Resource/properties/nested"}
                }}}}}),
            ),
        ),
        (
            "schema.json",
            json!({"$defs":{"Resource":{"$id":"https://canonical.example.test/resource","properties":{"nested":{"type":"string"}}}}}),
        ),
    ]);
    both(&dir, |contract| {
        clean(contract);
        let external = Uri::from_path(&dir.path().join("schema.json")).unwrap();
        let declaration = id(&external, "/$defs/Resource");
        let resource = contract.resource(&declaration).unwrap();
        assert_eq!(
            resource.canonical_uri(),
            "https://canonical.example.test/resource"
        );
        assert_eq!(
            resource.declaration_source(),
            Some(&declaration.child("$id"))
        );
        assert!(
            !contract
                .source_span(resource.declaration_source().unwrap())
                .unwrap()
                .is_empty()
        );
        let source = id(
            contract.entry(),
            "/paths/~1resource/query/requestBody/content/application~1json-seq/itemSchema",
        );
        let target = declaration.child("properties").child("nested");
        assert_eq!(contract.reference_target(&source), Some(&target));
        assert_eq!(
            contract.resource_scope(&target).unwrap().resource(),
            &declaration
        );
        assert_eq!(
            contract.schema(&source).unwrap().references()[0].target,
            Some(target)
        );
    });
}

#[test]
fn duplicate_item_schema_anchors_and_duplicate_method_declarations_fail_explicitly() {
    let dir = fixture(&[(
        "api.json",
        json!({"openapi":"3.2.0","info":{"title":"Ambiguous","version":"1"},"components":{"mediaTypes":{
            "Use":{"itemSchema":{"$ref":"#Item"}},"First":{"itemSchema":{"$anchor":"Item","type":"string"}},"Second":{"itemSchema":{"$anchor":"Item","type":"integer"}}
        }}}),
    )]);
    both(&dir, |contract| {
        let source = id(contract.entry(), "/components/mediaTypes/Use/itemSchema");
        located(contract, &source, "invalid-reference");
        assert!(contract.reference_target(&source).is_none());
        assert!(
            contract.schema(&source).unwrap().references()[0]
                .target
                .is_none()
        );
    });
    let dir = tempfile::tempdir().unwrap();
    std::fs::write(dir.path().join("api.json"), r#"{"openapi":"3.2.0","info":{"title":"Duplicate","version":"1"},"paths":{"/resource":{"additionalOperations":{"COPY":{},"COPY":{}}}}}"#).unwrap();
    for reader in [ContractReader::Lossless, ContractReader::Fast] {
        let workspace = Arc::new(WorkspaceBuilder::new().root(dir.path()).build().unwrap());
        let error = Contract::from_workspace_with_reader(
            &workspace,
            &Uri::from_path(&dir.path().join("api.json")).unwrap(),
            reader,
        )
        .unwrap_err();
        assert!(
            error.to_string().contains("duplicate mapping key `COPY`"),
            "{error}"
        );
    }
}

#[test]
fn yaml_and_json_oas32_sources_keep_method_case_schema_identity_and_exact_values() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("api.yaml");
    std::fs::write(
        &path,
        r#"
openapi: 3.2.0
info: {title: Stream, version: '1'}
paths:
  /events:
    additionalOperations:
      "MiX\u0045d~":
        parameters:
          - name: whole
            in: querystring
            content:
              application/json:
                schema: {type: object}
        responses:
          '200':
            content:
              application/json-seq:
                itemSchema:
                  type: number
                  minimum: 1e-4000
                  maximum: 18446744073709551617
                  default: {schema: {$ref: never-load.json}, itemSchema: {$anchor: Fake}}
"#,
    )
    .unwrap();
    let yaml_left = load(&dir, "api.yaml", ContractReader::Lossless);
    let yaml_right = load(&dir, "api.yaml", ContractReader::Fast);
    parity(&yaml_left, &yaml_right);
    let expected = id(
        yaml_left.entry(),
        "/paths/~1events/additionalOperations/MiXEd~0/responses/200/content/application~1json-seq/itemSchema",
    );
    for contract in [&yaml_left, &yaml_right] {
        clean(contract);
        assert_eq!(
            contract.operations().next().unwrap().method().as_str(),
            "MiXEd~"
        );
        assert_eq!(contract.schemas().count(), 2);
        assert_eq!(
            contract.schema(&expected).unwrap().raw()["minimum"].to_string(),
            "1e-4000"
        );
        assert_eq!(
            contract.schema(&expected).unwrap().raw()["maximum"].to_string(),
            "18446744073709551617"
        );
    }
    std::fs::write(
        &path,
        serde_json::to_vec(yaml_left.document(yaml_left.entry()).unwrap()).unwrap(),
    )
    .unwrap();
    let json_left = load(&dir, "api.yaml", ContractReader::Lossless);
    let json_right = load(&dir, "api.yaml", ContractReader::Fast);
    parity(&json_left, &json_right);
    clean(&json_left);
    assert_eq!(yaml_left.schema_roots(), json_left.schema_roots());
    assert_eq!(
        yaml_left.schema(&expected).unwrap().raw(),
        json_left.schema(&expected).unwrap().raw()
    );
    assert_ne!(
        yaml_left.schema(&expected).unwrap().span(),
        json_left.schema(&expected).unwrap().span()
    );
}
