// Code generated by suspect. DO NOT EDIT.

// Package cli is the generated command surface. Every command, flag and
// confirmation policy comes from the application mapping; HTTP semantics,
// authentication, schema validation and exact JSON handling stay in the
// embedded generated SDK. This file reads no environment variable: the SDK's
// own credential factory is the only credential reader, and it runs only while
// an API command executes, never during help or completion.
package cli

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/signal"
	"strings"
	"syscall"

	"github.com/spf13/cobra"
)

// Stable exit-code categories, documented in the root command's help.
const (
	// ExitSuccess: the request succeeded, or no request was needed.
	ExitSuccess = 0
	// ExitRuntime: transport, deadline, cancellation, codec or output failure.
	ExitRuntime = 1
	// ExitUsage: the invocation was refused before any request was sent.
	ExitUsage = 2
	// ExitAPIFailure: the API returned a response the contract documents as a failure.
	ExitAPIFailure = 3
)

// Generated flag names this runtime owns. A mapping can never claim them.
const (
	bodyFlagName    = "body-file"
	confirmFlagName = "confirm"
	serverFlagName  = "server-url"
)

// Streams are the only process streams any command touches.
type Streams struct {
	In  io.Reader
	Out io.Writer
	Err io.Writer
}

// usage classifies an invocation refused before any request was sent.
type usage struct{ message string }

func (e *usage) Error() string { return e.message }

func usagef(format string, args ...any) error {
	return &usage{message: fmt.Sprintf(format, args...)}
}

// failure classifies transport, deadline, cancellation, codec and output
// failures. Display keeps the SDK's own secret-free text.
type failure struct {
	message string
	cause   error
}

func (e *failure) Error() string {
	if e.cause == nil {
		return e.message
	}
	return e.message + ": " + e.cause.Error()
}

func (e *failure) Unwrap() error { return e.cause }

func failuref(cause error, format string, args ...any) error {
	return &failure{message: fmt.Sprintf(format, args...), cause: cause}
}

// documented is a response the contract declares as a failure. Its exact JSON
// document, when the contract declares one, is already on the output stream.
type documented struct {
	target string
	status int
}

func (e *documented) Error() string {
	return fmt.Sprintf("%s returned documented failure status %d", e.target, e.status)
}

// Execute runs one invocation and returns its exit code. Machine output goes
// to out; every diagnostic goes to errOut. SIGINT and SIGTERM cancel the
// context that every request observes.
func Execute(args []string, in io.Reader, out, errOut io.Writer) int {
	streams := &Streams{In: in, Out: out, Err: errOut}
	root := newRootCommand(streams)
	root.SetArgs(args)
	root.SetIn(in)
	root.SetOut(out)
	root.SetErr(errOut)
	root.SilenceErrors = true
	root.SilenceUsage = true
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	err := root.ExecuteContext(ctx)
	if err == nil {
		return ExitSuccess
	}
	fmt.Fprintln(errOut, err.Error())
	var api *documented
	if errors.As(err, &api) {
		return ExitAPIFailure
	}
	var runtimeFailure *failure
	if errors.As(err, &runtimeFailure) {
		return ExitRuntime
	}
	// Every command body returns one of the classified types above, so the
	// remaining errors are Cobra's own parse, unknown-flag and unknown-command
	// refusals: all usage failures, with nothing sent.
	return ExitUsage
}

// showHelp answers a bare root or group invocation. Those commands run no
// operation, so their only behavior is help; Args validation refuses anything
// else, which keeps an unrecognized command a usage failure instead of a
// silently successful help dump.
func showHelp(cmd *cobra.Command, _ []string) error {
	if err := cmd.Help(); err != nil {
		return failuref(err, "cannot write help")
	}
	return nil
}

// changedString reports a text flag's exact value and whether it was supplied
// at all, so an omitted flag stays distinct from an explicit empty string.
func changedString(cmd *cobra.Command, name string) (string, bool, error) {
	value, err := cmd.Flags().GetString(name)
	if err != nil {
		return "", false, failuref(err, "--%s is not a text flag", name)
	}
	return value, cmd.Flags().Changed(name), nil
}

// changedBool reports a boolean flag's exact value and whether it was supplied
// at all, so an omitted flag stays distinct from an explicit false.
func changedBool(cmd *cobra.Command, name string) (bool, bool, error) {
	value, err := cmd.Flags().GetBool(name)
	if err != nil {
		return false, false, failuref(err, "--%s is not a boolean flag", name)
	}
	return value, cmd.Flags().Changed(name), nil
}

// readDocument reads one finite request document. A path of "-" reads standard
// input. The generated ceiling is enforced before any decoding begins.
func readDocument(streams *Streams, path string, maximum int) ([]byte, error) {
	if path == "-" {
		return readBounded(streams.In, maximum, "standard input")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, usagef("cannot read --%s %q: %v", bodyFlagName, path, err)
	}
	defer func() { _ = file.Close() }()
	return readBounded(file, maximum, path)
}

func readBounded(reader io.Reader, maximum int, origin string) ([]byte, error) {
	data, err := io.ReadAll(io.LimitReader(reader, int64(maximum)+1))
	if err != nil {
		return nil, failuref(err, "cannot read %s", origin)
	}
	if len(data) > maximum {
		return nil, usagef("%s exceeds the generated maximum of %d bytes", origin, maximum)
	}
	return data, nil
}

// writeDocument writes one exact JSON document produced by a generated codec.
// The indented form only inserts whitespace between already-encoded tokens, so
// every number keeps the exact token the codec produced.
func writeDocument(streams *Streams, document []byte) error {
	if outputIndented {
		var indented bytes.Buffer
		if err := json.Indent(&indented, document, "", "  "); err != nil {
			return failuref(err, "cannot indent the exact document")
		}
		document = indented.Bytes()
	}
	if _, err := streams.Out.Write(document); err != nil {
		return failuref(err, "cannot write machine output")
	}
	if _, err := streams.Out.Write([]byte("\n")); err != nil {
		return failuref(err, "cannot write machine output")
	}
	return nil
}

// confirmRequired refuses to send an operation the mapping marks as requiring
// confirmation. The target operation is always named before refusing.
func confirmRequired(cmd *cobra.Command, streams *Streams, target, token string) error {
	supplied, changed, err := changedString(cmd, confirmFlagName)
	if err != nil {
		return err
	}
	if !changed {
		fmt.Fprintf(
			streams.Err,
			"refusing to send %s without confirmation: pass --%s %s, or --%s - to read the token from standard input\n",
			target, confirmFlagName, token, confirmFlagName,
		)
		return usagef("%s requires explicit confirmation", target)
	}
	if supplied == "-" {
		// Standard input can serve exactly one purpose per invocation.
		if cmd.Flags().Lookup(bodyFlagName) != nil && cmd.Flags().Changed(bodyFlagName) {
			if path, err := cmd.Flags().GetString(bodyFlagName); err == nil && path == "-" {
				return usagef(
					"--%s - and --%s - cannot both read standard input",
					confirmFlagName, bodyFlagName,
				)
			}
		}
		line, err := bufio.NewReader(streams.In).ReadString('\n')
		if err != nil && !errors.Is(err, io.EOF) {
			return failuref(err, "cannot read the confirmation token from standard input")
		}
		supplied = strings.TrimRight(line, "\r\n")
	}
	if supplied != token {
		fmt.Fprintf(
			streams.Err,
			"refusing to send %s: the supplied confirmation token does not match\n",
			target,
		)
		return usagef("%s requires explicit confirmation", target)
	}
	return nil
}

// callContext bounds one request with the generated deadline while keeping the
// caller's interrupt cancellation.
func callContext(parent context.Context) (context.Context, context.CancelFunc) {
	return context.WithTimeout(parent, requestDeadline)
}

// transportFailure classifies an SDK error that is not a documented API
// response, naming cancellation and the generated deadline explicitly.
func transportFailure(target string, err error) error {
	switch {
	case errors.Is(err, context.DeadlineExceeded):
		return failuref(nil, "%s exceeded the %s request deadline", target, requestDeadline)
	case errors.Is(err, context.Canceled):
		return failuref(nil, "%s was canceled", target)
	}
	return failuref(err, "%s failed", target)
}
