//! The builtin OAS pack: a Spectral-parity subset covering OpenAPI 2.0 and
//! 3.x. Every rule carries its applicable formats; the engine filters by the
//! document's sniffed family.

use crate::functions::Function;
use crate::rule::{FamilySet, Rule, Severity};

pub(crate) const METHOD_PATHS: [&str; 8] = [
    "$.paths.*.get",
    "$.paths.*.put",
    "$.paths.*.post",
    "$.paths.*.delete",
    "$.paths.*.options",
    "$.paths.*.head",
    "$.paths.*.patch",
    "$.paths.*.trace",
];

const SUMMARY_PATHS: [&str; 8] = [
    "$.paths.*.get.summary",
    "$.paths.*.put.summary",
    "$.paths.*.post.summary",
    "$.paths.*.delete.summary",
    "$.paths.*.options.summary",
    "$.paths.*.head.summary",
    "$.paths.*.patch.summary",
    "$.paths.*.trace.summary",
];

const DESCRIPTION_PATHS: [&str; 8] = [
    "$.paths.*.get.description",
    "$.paths.*.put.description",
    "$.paths.*.post.description",
    "$.paths.*.delete.description",
    "$.paths.*.options.description",
    "$.paths.*.head.description",
    "$.paths.*.patch.description",
    "$.paths.*.trace.description",
];

/// The full builtin OAS ruleset at Spectral default severities.
pub(crate) fn rules() -> Vec<Rule> {
    let oas23 = FamilySet::OAS2.union(FamilySet::OAS3);
    let f = FamilySet::OAS3;
    vec![
        Rule::new(
            "oas3-api-servers",
            "OpenAPI 3.x servers must be defined.",
            Severity::Warn,
            f,
            &["$.servers"],
            Function::Truthy,
        ),
        Rule::new(
            "oas3-api-contact",
            "OpenAPI 3.x API description must have a contact object.",
            Severity::Info,
            f,
            &["$.info"],
            property_defined("contact"),
        ),
        Rule::new(
            "info-contact",
            "Info object should contain a contact object.",
            Severity::Warn,
            oas23,
            &["$.info"],
            property_defined("contact"),
        ),
        Rule::new(
            "info-license",
            "Info object should contain a license object.",
            Severity::Warn,
            oas23,
            &["$.info"],
            property_defined("license"),
        ),
        Rule::new(
            "license-url",
            "License object should include `url`.",
            Severity::Warn,
            oas23,
            &["$.info.license"],
            property_defined("url"),
        ),
        Rule::new(
            "openapi-tags",
            "OpenAPI object should have non-empty `tags` array.",
            Severity::Warn,
            oas23,
            &["$.tags"],
            Function::Truthy,
        ),
        Rule::new(
            "operation-tags",
            "Operation should have non-empty `tags` array.",
            Severity::Warn,
            oas23,
            METHOD_PATHS.as_slice(),
            property_defined("tags"),
        ),
        Rule::new(
            "operation-operationId",
            "Operation must have an `operationId`.",
            Severity::Error,
            oas23,
            METHOD_PATHS.as_slice(),
            property_defined("operationId"),
        ),
        Rule::new(
            "operation-summary",
            "Operation should have `summary`.",
            Severity::Warn,
            oas23,
            SUMMARY_PATHS.as_slice(),
            Function::Truthy,
        ),
        Rule::new(
            "operation-description",
            "Operation should have `description`.",
            Severity::Info,
            oas23,
            DESCRIPTION_PATHS.as_slice(),
            Function::Truthy,
        ),
        Rule::new(
            "operation-default-response",
            "Operation must have a `default` or 2XX response.",
            Severity::Error,
            oas23,
            METHOD_PATHS.as_slice(),
            Function::DefaultResponse,
        ),
        Rule::new(
            "operation-success-response",
            "Operation must have at least one 2XX response.",
            Severity::Error,
            oas23,
            METHOD_PATHS.as_slice(),
            Function::SuccessResponse,
        ),
        Rule::new(
            "path-params",
            "Path template variables must be declared as path parameters.",
            Severity::Error,
            oas23,
            &["$.paths.*"],
            Function::PathParams,
        ),
        Rule::new(
            "path-keys-no-trailing-slash",
            "Path keys must not end with a trailing slash.",
            Severity::Warn,
            oas23,
            &["$.paths.*"],
            Function::NoTrailingSlash,
        ),
        Rule::new(
            "no-$ref-siblings",
            "$ref values must not have siblings other than description/summary (3.0).",
            Severity::Error,
            FamilySet::OAS30,
            &["$..['$ref']"],
            Function::RefSiblings,
        ),
        Rule::new(
            "no-$ref-siblings",
            "$ref values must not have siblings other than description/summary (3.1+).",
            Severity::Warn,
            FamilySet::OAS31.union(FamilySet::OAS32),
            &["$..['$ref']"],
            Function::RefSiblings,
        ),
        Rule::new(
            "typed-enum",
            "Enum member does not match the schema's declared type.",
            Severity::Error,
            oas23,
            &["$..enum"],
            Function::TypedEnum,
        ),
        // -- Spectral parity: tag/server/path hygiene ----------------------
        Rule::new(
            "openapi-tags-alphabetical",
            "Root `tags` should be alphabetically sorted.",
            Severity::Hint,
            oas23,
            &["$.tags"],
            Function::SortedKeys,
        ),
        Rule::new(
            "server-host-not-example",
            "Server URLs should not use example hosts (localhost, 127.0.0.1, example.com).",
            Severity::Warn,
            FamilySet::OAS3,
            &["$..servers.*.url"],
            Function::ServerUrls,
        ),
        Rule::new(
            "server-trailing-slash",
            "Server URLs should not end in a trailing slash.",
            Severity::Warn,
            FamilySet::OAS3,
            &["$..servers.*.url"],
            Function::ServerUrls,
        ),
        Rule::new(
            "operation-tag-defined",
            "Operation tags must be declared in the root `tags` list.",
            Severity::Error,
            oas23,
            &["$.paths.*.*.tags"],
            Function::TagDefined,
        ),
        Rule::new(
            "path-not-include-query",
            "Path keys must not include a query string.",
            Severity::Error,
            oas23,
            &["$.paths.*"],
            Function::PathNoQuery,
        ),
        Rule::new(
            "no-ambiguous-paths",
            "Path keys must not be ambiguous after normalization (no duplicates).",
            Severity::Error,
            oas23,
            &["$.paths"],
            Function::DuplicateKeys,
        ),
        // -- deeper operation rules --------------------------------------
        Rule::new(
            "operation-operationId-unique",
            "Every operation must have a unique `operationId`.",
            Severity::Error,
            oas23,
            &["$.paths"],
            Function::UniqueOperationIds,
        ),
        Rule::new(
            "operation-operationId-valid-in-url",
            "Operation `operationId` must only contain URL-safe characters.",
            Severity::Error,
            oas23,
            &["$.paths.*.*.operationId"],
            Function::Pattern(regex::Regex::new(r"^[A-Za-z0-9._-]+$").expect("static regex")),
        ),
        Rule::new(
            "operation-4xx-response",
            "Operation should have at least one 4XX response.",
            Severity::Warn,
            oas23,
            METHOD_PATHS.as_slice(),
            Function::StatusRange {
                low: 400,
                high: 499,
            },
        ),
        Rule::new(
            "operation-singular-tag",
            "Operation should have exactly one tag.",
            Severity::Hint,
            oas23,
            &["$.paths.*.*.tags"],
            Function::Length {
                min: None,
                max: Some(1.0),
            },
        ),
        // -- info and tag documentation ----------------------------------
        Rule::new(
            "info-description",
            "OpenAPI object should have `description`.",
            Severity::Info,
            oas23,
            &["$.info"],
            property_defined("description"),
        ),
        Rule::new(
            "tag-description",
            "Tag objects should have `description`.",
            Severity::Info,
            oas23,
            &["$.tags.*"],
            property_defined("description"),
        ),
        // -- markdown hygiene --------------------------------------------
        Rule::new(
            "no-eval-in-markdown",
            "Markdown descriptions must not contain `eval(` or `Function(`.",
            Severity::Error,
            oas23,
            &["$..description"],
            Function::NotMatch(regex::Regex::new(r"(eval\(|Function\()").expect("static regex")),
        ),
        Rule::new(
            "no-script-tags-in-markdown",
            "Markdown descriptions must not contain `<script>` tags.",
            Severity::Error,
            oas23,
            &["$..description"],
            Function::NotMatch(regex::Regex::new(r"<script").expect("static regex")),
        ),
        // -- security, paths and parameters --------------------------------
        Rule::new(
            "security-defined",
            "Security requirement must name a declared scheme.",
            Severity::Error,
            oas23,
            &["$..security"],
            Function::SecurityDefined,
        ),
        Rule::new(
            "path-declarations-must-exist",
            "Path keys must begin with a leading slash.",
            Severity::Error,
            oas23,
            &["$.paths.*"],
            Function::AbsolutePath,
        ),
        Rule::new(
            "no-identical-paths",
            "Path keys must not be identical modulo template variables.",
            Severity::Warn,
            oas23,
            &["$.paths"],
            Function::NoIdenticalPaths,
        ),
        Rule::new(
            "parameter-schema-or-content",
            "Parameter must define `schema` or `content`.",
            Severity::Error,
            FamilySet::OAS3,
            &["$..parameters.*"],
            Function::ParameterSchemaOrContent,
        ),
        Rule::new(
            "oas3-unused-component",
            "Component should be referenced by at least one `$ref`.",
            Severity::Warn,
            FamilySet::OAS3,
            &[
                "$.components.schemas",
                "$.components.responses",
                "$.components.parameters",
                "$.components.headers",
                "$.components.examples",
                "$.components.requestBodies",
                "$.components.securitySchemes",
                "$.components.links",
                "$.components.callbacks",
            ],
            Function::UnusedComponent,
        ),
        Rule::new(
            "oas2-unused-definition",
            "Definition should be referenced by at least one `$ref`.",
            Severity::Warn,
            FamilySet::OAS2,
            &["$.definitions"],
            Function::UnusedComponent,
        ),
        Rule::new(
            "parameter-description",
            "Parameter objects should have `description`.",
            Severity::Info,
            oas23,
            &["$..parameters.*"],
            property_defined("description"),
        ),
    ]
}

fn property_defined(name: &str) -> Function {
    Function::Defined {
        property: name.into(),
    }
}
