//! Native Go clients and package assembly from checked protocol/model plans.
use super::*;
use serde_json::{Value, json};

pub(super) fn q(text: &str) -> String {
    serde_json::to_string(text).expect("Go string literal")
}
pub(super) fn source(id: &SourceId) -> String {
    format!(
        "HTTPSource{{Document:{},Pointer:{}}}",
        q(id.document().as_str()),
        q(id.pointer())
    )
}
pub(super) fn location(id: &SourceId) -> Value {
    json!({"document":id.document().as_str(),"pointer":id.pointer()})
}
fn prose(text: &str) -> String {
    text.replace(['\n', '\r'], " ").replace("*/", "* /")
}
pub(super) fn description(op: &PlannedOperation) -> &str {
    op.wire.description().map_or("", |v| v.value())
}
pub(super) fn status(r: &PlannedResponse) -> Value {
    match r.status() {
        protocol::ResponseStatus::Exact(n) => json!(n),
        _ => json!(r.wire.status_key()),
    }
}
pub(super) fn aggregates(plan: &HttpPlan) -> Vec<&PlannedAggregate> {
    plan.operations
        .iter()
        .flat_map(|op| {
            op.body
                .iter()
                .flat_map(|b| &b.media)
                .chain(op.responses.iter().filter_map(|r| r.media.as_ref()))
        })
        .filter_map(|m| m.aggregate.as_ref())
        .collect()
}
pub(super) fn package(plan: &HttpPlan, package: &PackageConfig) -> Vec<OutFile> {
    let mut files: BTreeMap<_, _> = plan
        .codecs
        .render()
        .into_iter()
        .map(|f| (f.path, f.content))
        .collect();
    files.insert(
        "go/go.mod".into(),
        format!("module {}\n\ngo 1.23\n", package.module_path),
    );
    for (name, content) in [
        ("http_runtime", include_str!("runtime.go")),
        ("http_parameters", include_str!("parameters.go")),
        ("http_media", include_str!("media.go")),
        ("http_security", include_str!("security.go")),
        ("http_parts", include_str!("parts.go")),
        ("http_stream", include_str!("stream.go")),
    ] {
        files.insert(format!("go/{name}.go"), content.into());
    }
    files.insert(
        "go/attribution.go".into(),
        match &plan.config.attribution {
            Some(attribution) => format!(
                "// Code generated by suspect. DO NOT EDIT.\n// ua/v1 attribution: every request identifies suspect as the generator and the\n// SDK or a caller-supplied application as the client.\npackage sdk\n\nconst (\n\tuserAgentSuspectVersion = {}\n\tuserAgentSDKName = {}\n\tuserAgentSDKVersion = {}\n\tuserAgentSpecVersion = {}\n)\n",
                q(&attribution.suspect_version),
                q(&attribution.sdk_name),
                q(&attribution.sdk_version),
                q(&attribution.spec_version),
            ),
            None => "// Code generated by suspect. DO NOT EDIT.\npackage sdk\n\n// An empty suspect version disables the automatic attribution header.\nconst userAgentSuspectVersion = \"\"\nconst userAgentSDKName, userAgentSDKVersion, userAgentSpecVersion = \"\", \"\", \"\"\n".into(),
        },
    );
    for file in super::credential_env::artifacts(plan) {
        files.insert(file.path, file.content);
    }
    // Pagination helpers are emitted only for a configured policy with at
    // least one paginated operation; no-policy output stays byte-identical.
    if let Some(pagination) = plan.pagination.as_ref().filter(|p| p.emits()) {
        files.insert(
            "go/pagination.go".into(),
            super::pagination::emit(plan, pagination),
        );
    }
    // OAuth lifecycle helpers are emitted only for a configured policy with at
    // least one usable scheme; no-policy output stays byte-identical.
    if let Some(oauth) = plan.oauth.as_ref().filter(|plan| super::oauth::emits(plan)) {
        files.insert(
            "go/oauth.go".into(),
            super::oauth::emit(
                oauth,
                &super::oauth::no_replay_requirements(oauth, plan.operations()),
            ),
        );
    }
    // Typed event iterators are emitted only for operations whose compiled
    // stream plan carries a discriminated SSE event set; the file is absent
    // otherwise, so no-stream output stays byte-identical.
    if let Some(events) = plan.stream_events.as_ref().filter(|events| events.emits()) {
        files.insert(
            "go/stream_events.go".into(),
            super::stream_events::emit(plan, events),
        );
    }
    // Incoming receipt helpers are emitted only for contracts that declare
    // webhooks or callbacks; receipt-less output stays byte-identical.
    if !plan.incoming_receipts.is_empty() {
        files.insert(
            "go/incoming.go".into(),
            super::incoming::emit(plan, &plan.incoming_receipts),
        );
    }
    let mut code="// Code generated by suspect. DO NOT EDIT.\npackage sdk\n\nimport(\"context\";\"fmt\";\"io\";\"reflect\")\nvar _ fmt.State\nvar _ = io.WriteString\nvar _ = context.Background\n\n".to_string();
    code.push_str("var httpCodecs=map[string]httpValueCodec{\n");
    for name in plan.symbols.values() {
        code.push_str(&format!("{}:httpBind(Codecs.{name}),\n", q(name)));
    }
    code.push_str("}\n");
    code.push_str("var httpAggregateTypes=map[string]reflect.Type{\n");
    for a in aggregates(plan) {
        code.push_str(&format!(
            "{}:reflect.TypeFor[{}](),\n",
            q(&a.type_name),
            a.type_name
        ));
    }
    code.push_str("}\n");
    for (scheme, name) in &plan.credentials {
        let requirement = plan
            .protocol
            .operations()
            .iter()
            .flat_map(|op| op.security().alternatives())
            .flat_map(|a| a.requirements())
            .find(|r| r.name() == scheme)
            .unwrap();
        let (args, call): (String, String) = match requirement.credential() {
            protocol::CredentialHook::Bearer { .. } => (
                "token string".into(),
                format!("WithBearer({},token)", q(scheme)),
            ),
            protocol::CredentialHook::Basic => (
                "user,password string".into(),
                format!("WithBasic({},user,password)", q(scheme)),
            ),
            protocol::CredentialHook::ApiKey { .. } => (
                "value string".into(),
                format!("WithAPIKey({},value)", q(scheme)),
            ),
            _ => (
                "hook CredentialHook".into(),
                format!("WithHook({},hook)", q(scheme)),
            ),
        };
        code.push_str(&format!("// {name} supplies the source credential scheme {}.\nfunc {name}({args})Credentials{{return (Credentials{{}}).{call}}}\n",prose(scheme)));
    }
    for a in aggregates(plan) {
        code.push_str(&aggregate(a));
    }
    for (index, op) in plan.operations.iter().enumerate() {
        code.push_str(&operation(plan, op, index));
    }
    files.insert("go/operations.go".into(), code);
    let mut manifest = json!({"format":"suspect-go-http-v2","releaseReady":false,"module":package.module_path,"package":package.package_name,"version":package.version,"protocol":plan.protocol,"operations":plan.operations.iter().map(|op|binding(plan,op)).collect::<Vec<_>>()});
    if let Some(policy) = plan.credential_env() {
        manifest["credentialEnv"] = json!(policy);
        manifest["credentialEnvFactory"] = json!(plan.credential_env_factory());
    }
    files.insert(
        "go/http-manifest.json".into(),
        format!("{}\n", serde_json::to_string_pretty(&manifest).unwrap()),
    );
    files.insert(
        "go/examples.json".into(),
        crate::http_examples::manifest(&plan.examples),
    );
    files.insert("go/README.md".into(), readme(plan, package));
    for file in super::docs::artifacts(plan, package) {
        files.insert(file.path, file.content);
    }
    files
        .into_iter()
        .map(|(path, content)| OutFile { path, content })
        .collect()
}

fn structure(
    name: &str,
    constructor: &str,
    members: &[(String, String, bool, Option<String>)],
) -> String {
    let mut code =
        format!("// {name} contains typed source-defined inputs.\ntype {name} struct{{\n");
    for (field, ty, required, _) in members {
        code.push_str(&format!(
            "// {field} is {}.\n{field} {}\n",
            if *required {
                "required"
            } else {
                "optional; unset means omitted"
            },
            if *required {
                ty.clone()
            } else {
                format!("Optional[{ty}]")
            }
        ));
    }
    code.push_str("}\n");
    let args = members
        .iter()
        .enumerate()
        .filter(|(_, (_, _, required, _))| *required)
        .map(|(i, (_, ty, _, _))| format!("value{i} {ty}"))
        .collect::<Vec<_>>()
        .join(",");
    let values = members
        .iter()
        .enumerate()
        .filter(|(_, (_, _, required, _))| *required)
        .map(|(i, (field, _, _, _))| format!("{field}:value{i}"))
        .collect::<Vec<_>>()
        .join(",");
    code.push_str(&format!("// {constructor} supplies the required fields without applying defaults.\nfunc {constructor}({args}){name}{{return {name}{{{values}}}}}\n"));
    for (field, ty, _, setter) in members {
        if let Some(setter) = setter {
            code.push_str(&format!("// {setter} supplies the optional {field}.\nfunc(v {name}){setter}(value {ty}){name}{{v.{field}=OptionalSome(value);return v}}\n"));
        }
    }
    code
}
fn aggregate(a: &PlannedAggregate) -> String {
    let mut members = a
        .parts
        .iter()
        .map(|p| {
            (
                p.field_name.clone(),
                p.native_type.clone(),
                p.wire.required(),
                p.setter_name.clone(),
            )
        })
        .collect::<Vec<_>>();
    // Extras/items have ordinary native map/slice zero values, with structural
    // rules enforced by the aggregate encoder rather than a synthetic codec.
    let extra = a
        .additional
        .as_ref()
        .map(|p| {
            format!(
                "// {} holds source-admitted additional parts.\n{} {}\n",
                p.field_name, p.field_name, p.native_type
            )
        })
        .unwrap_or_default();
    let mut code = structure(&a.type_name, &a.constructor, &members);
    if !extra.is_empty() {
        let marker = format!("type {} struct{{\n", a.type_name);
        code = code.replacen(&marker, &format!("{marker}{extra}"), 1);
    }
    members.clear();
    code
}
fn operation(plan: &HttpPlan, op: &PlannedOperation, index: usize) -> String {
    let input = &op.input_type;
    let result = &op.success_type;
    let api_error = &op.error_variant;
    let mut code = String::new();
    if let Some(body) = op.body().filter(|b| b.is_choice()) {
        let name = &body.native_type;
        code.push_str(&format!("// {name} is a closed choice of source-declared request media.\ntype {name} interface{{is{name}();httpBody(httpOperation,int)(httpBody,error)}}\n"));
        for (i, m) in body.media.iter().enumerate() {
            let concrete = &m.choice_type;
            let ty = &m.native_type;
            let ctor = &m.constructor;
            let (args, ct) = if m.requires_content_type() {
                (
                    format!("contentType string,value {ty}"),
                    "contentType".into(),
                )
            } else {
                (format!("value {ty}"), q(m.wire.media_type().declared()))
            };
            code.push_str(&format!("// {concrete} contains {} request data.\ntype {concrete} struct{{Content[{ty}]}}\nfunc {ctor}({args}){concrete}{{return {concrete}{{Content[{ty}]{{ContentType:{ct},Data:value}}}}}}\nfunc({concrete})is{name}(){{}}\nfunc(v {concrete})httpBody(op httpOperation,limit int)(httpBody,error){{return httpEncodeBody(op,{i},v.ContentType,v.Data,limit)}}\n",prose(m.wire.media_type().declared())));
        }
    }
    let mut members = op
        .parameters
        .iter()
        .map(|p| {
            (
                p.field_name.clone(),
                plan.symbols[p.schema()].clone(),
                p.wire.required(),
                p.setter_name.clone(),
            )
        })
        .collect::<Vec<_>>();
    if let Some(b) = op.body() {
        members.push((
            b.field_name.clone(),
            b.native_type.clone(),
            b.wire.required(),
            b.setter_name.clone(),
        ));
    }
    code.push_str(&structure(input, &op.input_constructor, &members));
    code.push_str(&format!("// {result} is a closed union selected by actual response status and media.\n// Close releases streaming data; buffered data needs no cleanup.\ntype {result} interface{{is{result}();Close()error}}\n// {api_error} is the closed declared API-error union. Use errors.As for its concrete types.\ntype {api_error} interface{{error;io.Closer;is{api_error}()}}\n"));
    let mut header_types = BTreeSet::new();
    for r in &op.responses {
        let name = &r.type_name;
        let model = &r.native_type;
        let headers = &r.headers_type;
        if header_types.insert(headers.clone()) {
            code.push_str(&format!("// {headers} contains source-validated response headers.\ntype {headers} struct{{\n"));
            for h in &r.headers {
                let model = &plan.symbols[h.wire.codec().schema().id()];
                let ty = if h.wire.required() {
                    model.clone()
                } else {
                    format!("Optional[{model}]")
                };
                code.push_str(&format!("{} {ty}\n", h.field_name));
            }
            code.push_str("}\n");
        }
        code.push_str(&format!("// {name} contains the {} response; Status is always the actual HTTP status.\ntype {name} struct{{APIResponse[{model}];DecodedHeaders {headers}}}\n",r.wire.status_key()));
        if r.can_succeed() {
            code.push_str(&format!("func({name})is{result}(){{}}\n"));
        }
        if r.can_fail() {
            code.push_str(&format!("func(*{name})is{api_error}(){{}}\nfunc(e *{name})Error()string{{return fmt.Sprintf({},e.Status)}}\nfunc(e *{name})Format(s fmt.State,verb rune){{_,_=io.WriteString(s,e.Error())}}\n",q(&format!("{} returned HTTP %d",op.operation_id))));
        }
    }
    code.push_str(&format!(
        "var operation{index}=httpLoadOperation({})\n",
        q(&serde_json::to_string(&descriptors::operation(op, plan)).unwrap())
    ));
    code.push_str(&super::docs::operation_comment(plan, op));
    let signature = if op.optional_input {
        format!("inputs ...{input}")
    } else {
        format!("input {input}")
    };
    code.push_str(&format!(
        "func(c *Client){}(ctx context.Context,{signature})({result},error){{\n",
        op.method_name
    ));
    if op.optional_input {
        code.push_str(&format!("var input {input};if len(inputs)>1{{return nil,httpError(\"request-validation\",operation{index},operation{index}.Source,nil)}};if len(inputs)==1{{input=inputs[0]}};_=input\n"));
    }
    code.push_str(&format!(
        "parameters:=make([]httpParameter,0,{})\n",
        op.parameters.len()
    ));
    for (i, p) in op.parameters.iter().enumerate() {
        let field = &p.field_name;
        let model = &plan.symbols[p.schema()];
        let at = source(p.wire.source().use_site().source());
        if !p.wire.required() {
            code.push_str(&format!("if err:=httpOptional(input.{field},operation{index},{at});err!=nil{{return nil,err}};if input.{field}.IsSet{{\n"));
        }
        let value = if p.wire.required() {
            format!("input.{field}")
        } else {
            format!("input.{field}.Value")
        };
        code.push_str(&format!("{{value,err:=Codecs.{model}.EncodeValue({value});if err!=nil{{return nil,httpError(\"request-validation\",operation{index},{at},err)}};parameters=append(parameters,httpParameter{{index:{i},value:value}})}}\n"));
        if !p.wire.required() {
            code.push_str("}\n");
        }
    }
    code.push_str("var body httpBody\n");
    if let Some(b) = op.body() {
        let at = source(b.wire.source().use_site().source());
        let field = &b.field_name;
        if !b.wire.required() {
            code.push_str(&format!("if err:=httpOptional(input.{field},operation{index},{at});err!=nil{{return nil,err}};if input.{field}.IsSet{{\n"));
        }
        let value = if b.wire.required() {
            format!("input.{field}")
        } else {
            format!("input.{field}.Value")
        };
        let encode = if b.is_choice() {
            format!("{value}.httpBody(operation{index},c.options.MaxPartBytes)")
        } else if b.media[0].requires_content_type() {
            format!(
                "httpEncodeBody(operation{index},0,{value}.ContentType,{value}.Data,c.options.MaxPartBytes)"
            )
        } else {
            format!("httpEncodeBody(operation{index},0,\"\",{value},c.options.MaxPartBytes)")
        };
        if b.is_choice() {
            code.push_str(&format!("if {value}==nil||(reflect.ValueOf({value}).Kind()==reflect.Pointer&&reflect.ValueOf({value}).IsNil()){{return nil,httpError(\"request-validation\",operation{index},{at},nil)}}\n"));
        }
        code.push_str(&format!("{{var err error;body,err={encode};if err!=nil{{return nil,httpError(\"request-validation\",operation{index},{at},err)}}}}\n"));
        if !b.wire.required() {
            code.push_str("}\n");
        }
    }
    code.push_str(&format!("raw,err:=c.exchange(ctx,operation{index},parameters,body);if err!=nil{{return nil,err}};defer raw.release()\nswitch{{\n"));
    for r in &op.responses {
        let name = &r.type_name;
        let model = &r.native_type;
        let ri = r.response_index;
        let condition = if r.forbidden_body {
            format!("raw.response=={ri}&&raw.forbidden")
        } else if let Some(mi) = r.media_index {
            format!("raw.response=={ri}&&raw.media=={mi}&&!raw.forbidden")
        } else {
            format!("raw.response=={ri}")
        };
        let at = source(r.wire.source().use_site().source());
        code.push_str(&format!(
            "case {condition}:\nvar headers {}\n",
            r.headers_type
        ));
        for (hi, h) in r.headers.iter().enumerate() {
            let model = &plan.symbols[h.wire.codec().schema().id()];
            let field = &h.field_name;
            code.push_str(&format!("{{v,present,err:=httpDecodeHeader(operation{index}.Responses[{ri}].Headers[{hi}],raw.headers,raw.maximum);if err!=nil{{return nil,raw.fail(\"response-decoding\",{at},err)}};if present{{value,err:=httpNative[{model}](v);if err!=nil{{return nil,raw.fail(\"response-decoding\",{at},err)}};headers.{field}={}}}}}\n",if h.wire.required(){"value"}else{"OptionalSome(value)"}));
        }
        if r.forbidden_body {
            code.push_str("value:=NoContent{}\n");
        } else if let Some(mi) = r.media_index {
            if let Some(m) = r.media.as_ref().filter(|m| {
                matches!(
                    m.wire.representation(),
                    protocol::Representation::Stream { .. }
                )
            }) {
                let item = &plan.symbols[m.schema().unwrap()];
                code.push_str(&format!("value:=httpNewStream(raw,operation{index}.Responses[{ri}].Media[{mi}],Codecs.{item})\n"));
            } else {
                code.push_str(&format!("v,err:=httpDecodeMedia(operation{index}.Responses[{ri}].Media[{mi}],raw);if err!=nil{{return nil,raw.fail(\"response-decoding\",{at},err)}};value,err:=httpNative[{model}](v);if err!=nil{{return nil,raw.fail(\"response-decoding\",{at},err)}}\n"));
            }
        } else {
            code.push_str("value:=raw.body\n");
        }
        code.push_str(&format!("reply:={name}{{APIResponse:APIResponse[{model}]{{Status:raw.status,Headers:raw.headers.Clone(),ContentType:raw.contentType,Data:value,Links:httpCopy(operation{index}.Responses[{ri}].Links)}},DecodedHeaders:headers}}\n"));
        if r.can_succeed() && r.can_fail() {
            code.push_str(
                "if raw.status>=200&&raw.status<300{return reply,nil};return nil,&reply\n",
            );
        } else if r.can_succeed() {
            code.push_str("return reply,nil\n");
        } else {
            code.push_str("return nil,&reply\n");
        }
    }
    code.push_str("default:return nil,raw.fail(\"unexpected-response\",raw.source,nil)\n}\n}\n");
    if let Some(method) = &op.data_method {
        let r = op.responses.iter().find(|r| r.can_succeed()).unwrap();
        let ty = &r.native_type;
        let name = &r.type_name;
        let arg = if op.optional_input {
            "inputs..."
        } else {
            "input"
        };
        code.push_str(&format!("// {method} returns the single successful data representation directly.\n// Use [{}] to retain status, decoded headers and links.\nfunc(c *Client){method}(ctx context.Context,{signature})({ty},error){{var zero {ty};reply,err:=c.{}(ctx,{arg});if err!=nil{{return zero,err}};return reply.({name}).Data,nil}}\n",op.method_name,op.method_name));
    }
    code
}

pub(super) fn binding(plan: &HttpPlan, op: &PlannedOperation) -> Value {
    let first = op
        .wire
        .security()
        .alternatives()
        .first()
        .and_then(|a| a.requirements().first());
    json!({"operationId":op.operation_id,"method":op.method_name,"nativeMethod":op.method_name,"source":location(&op.source),"httpMethod":op.wire.method().as_str(),"path":op.wire.path(),"description":description(op),"input":op.input_type,"constructor":op.input_constructor,"inputConstructor":op.input_constructor,"success":op.success_type,"apiError":op.error_variant,"dataMethod":op.data_method,"optionalInput":op.optional_input,
        "security":first.map(|r|json!({"scheme":r.name(),"constructor":plan.credentials[r.name()],"useSource":location(r.source().source()),"definitionSource":location(r.scheme().terminal().source())})),
        "parameters":op.parameters.iter().map(|p|json!({"name":p.wire.name(),"wire":p.wire.name(),"member":p.field_name,"setter":p.setter_name,"required":p.wire.required(),"source":location(p.wire.source().use_site().source()),"schema":location(p.schema()),"model":plan.symbols[p.schema()],"serialization":p.wire.serialization(),"protocol":p.wire})).collect::<Vec<_>>(),
        "body":op.body().map(|b|json!({"member":b.field_name,"setter":b.setter_name,"required":b.wire.required(),"model":b.schema().map(|s|&plan.symbols[s]),"nativeType":b.native_type,"schema":b.schema().map(location),"source":location(b.wire.source().use_site().source()),"media":b.media.iter().map(|m|json!({"nativeType":m.native_type,"choiceType":m.choice_type,"constructor":m.constructor,"protocol":m.wire})).collect::<Vec<_>>()})),
        "responses":op.responses.iter().map(|r|json!({"type":r.type_name,"nativeType":r.type_name,"status":status(r),"selector":r.wire.status(),"model":r.schema().map(|s|&plan.symbols[s]),"dataType":r.native_type,"headersType":r.headers_type,"schema":r.schema().map(location),"source":location(r.wire.source().use_site().source()),"mediaType":r.media.as_ref().map(|m|m.wire.media_type().declared()),"forbiddenBody":r.forbidden_body})).collect::<Vec<_>>(),"protocol":op.wire})
}
fn readme(plan: &HttpPlan, package: &PackageConfig) -> String {
    let mut text = format!(
        "# {}\n\nSource-selected Go SDK (`go 1.23`), using standard `net/http` and exact typed codecs.\n\nCreate a reusable `Client` with explicit `Credentials` and `ClientOptions`. All calls take `context.Context`; no-input operations accept the context alone. A `*Data` method returns an unambiguous success payload directly; the ordinary operation returns typed status/media wrappers and decoded headers. Use `errors.As` for declared API errors and `*SDKError` for transport, representation, codec or budget failures.\n\n",
        package.module_path
    );
    text.push_str(&super::docs::quickstart(plan, package));
    text.push_str("\n## Protocol and transport\n\n- `ServerIndex`, `ServerVariables` and `DocumentURL` select source servers; `ServerURL` supplies an explicit absolute override including its prefix.\n- Security OR members use the first complete supplied alternative; `SecurityAlternative` selects one explicitly. AND members attach together. OAuth/OIDC accept caller `Authorization` or `CredentialHook` values with source scopes/roles/flow metadata.\n- JSON/text codecs validate mutable inputs before transport. Binary data is `[]byte`; forms and multipart have structural typed fields and per-part codecs. `Part[T]` carries in-memory data, optional filename, concrete media and headers.\n- Exact status precedes class then default. Media precedence is concrete, type wildcard, then any wildcard, with declared parameters breaking ties. Actual status determines success.\n- `Stream[T]` is a finite pull iterator: `defer stream.Close(); for stream.Next() { item := stream.Value(); _ = item }; err := stream.Err()`. The context/timeout owns its whole lifetime. SSE validates parsed envelopes, including string data and numeric retry.\n\nDefault HTTP transport ignores ambient proxies, follows no redirects and disables decompression. Inject a standard HTTP client or `Doer` for transport policy. Request bodies have no replay factory. Request, response, capture, part and item limits are finite; callers may lower limits. Error display omits bodies, credentials and causes; explicit fields and `Unwrap` retain diagnostic metadata. The SDK adds no retries, pagination, token acquisition, refresh, stream sentinels or JSON-in-SSE decoding.\n\n## Operations\n\n");
    for op in &plan.operations {
        text.push_str(&format!(
            "- `{}` (`{} {}`): `{}` → `{}`{}. {}\n",
            op.method_name,
            op.wire.method().as_str(),
            op.wire.path(),
            op.input_type,
            op.success_type,
            op.data_method
                .as_ref()
                .map_or(String::new(), |m| format!("; direct data: `{m}`")),
            prose(description(op))
        ));
    }
    text.push_str(&super::credential_env::readme(plan));
    text.push_str("\nRun `go test ./...`, `go run ./examples/validated`, and `go doc -all .`. `http-manifest.json` and `docs/source-bindings.json` retain typed protocol/native bindings and source provenance. Generation certifies only the admitted selected-operation slice.\n");
    text
}
