//! Go emitter: structs with JSON tags, sealed-interface unions with a
//! type-switch helper, and a stdlib-only client with functional options.

use crate::stg::{Base, Graph, StgNode, StgType};

/// Emits the Go SDK for `graph` as `(path, content)` pairs.
pub fn emit_go(graph: &Graph) -> Vec<(String, String)> {
    let mut models =
        String::from("// Code generated by suspect-codegen. DO NOT EDIT.\n\npackage api\n\n");
    let mut client = String::from(
        "// Code generated by suspect-codegen. DO NOT EDIT.\n\npackage api\n\nimport (\n\t\"bytes\"\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n\t\"net/http\"\n\t\"net/url\"\n)\n\n// Client calls the API described by the source specification.\ntype Client struct {\n\tBaseURL    string\n\tHTTP       *http.Client\n}\n\n// NewClient builds a client with sane defaults.\nfunc NewClient(baseURL string, opts ...ClientOption) *Client {\n\tc := &Client{BaseURL: baseURL, HTTP: http.DefaultClient}\n\tfor _, opt := range opts {\n\t\topt(c)\n\t}\n\treturn c\n}\n\n// ClientOption customizes the client at construction.\ntype ClientOption func(*Client)\n\n// WithHTTP replaces the underlying HTTP client.\nfunc WithHTTP(h *http.Client) ClientOption {\n\treturn func(c *Client) { c.HTTP = h }\n}\n\n// execute performs one round trip and returns the raw body.\nfunc (c *Client) execute(ctx context.Context, method, path string, body any) ([]byte, error) {\n\tvar rdr io.Reader\n\tif body != nil {\n\t\tbuf, err := json.Marshal(body)\n\t\tif err != nil {\n\t\t\treturn nil, err\n\t\t}\n\t\trdr = bytes.NewReader(buf)\n\t}\n\treq, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, rdr)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tif body != nil {\n\t\treq.Header.Set(\"Content-Type\", \"application/json\")\n\t}\n\tresp, err := c.HTTP.Do(req)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer resp.Body.Close()\n\treturn io.ReadAll(resp.Body)\n}\n\n// doJSON executes and decodes a JSON response into `into`.\nfunc (c *Client) doJSON(ctx context.Context, method, path string, body any, into any) error {\n\traw, err := c.execute(ctx, method, path, body)\n\tif err != nil {\n\t\treturn err\n\t}\n\tif into == nil {\n\t\treturn nil\n\t}\n\treturn json.Unmarshal(raw, into)\n}\n",
    );

    for name in &graph.topo_order {
        let Some(node) = graph.components.get(name) else {
            continue;
        };
        match node {
            StgNode::Struct(s) => {
                models.push_str(&format!("type {} struct {{\n", s.name.pascal));
                for f in &s.fields {
                    let optional = !f.required;
                    let ty = go_type(&f.ty);
                    let ty = if optional {
                        format!("*{}", ty.trim_start_matches('*'))
                    } else {
                        ty
                    };
                    let omitempty = if optional { ",omitempty" } else { "" };
                    let field_name = format!("{}{}", s.name.pascal, go_export(&f.ident.camel));
                    models.push_str(&format!(
                        "\t{field_name} {ty} `json:\"{}{}\"`\n",
                        f.ident.original, omitempty
                    ));
                }
                models.push_str("}\n\n");
            }
            StgNode::StringEnum(e) => {
                // Named string type + constants.
                models.push_str(&format!("type {} string\n\nconst (\n", e.name.pascal));
                for (lit, ident) in &e.variants {
                    let const_name = format!("{}{}", e.name.pascal, go_export(&ident.pascal));
                    models.push_str(&format!(
                        "\t{const_name} {} = {}\n",
                        e.name.pascal,
                        quote_go(lit)
                    ));
                }
                models.push_str(")\n\n");
            }
            StgNode::Sum(sum) => {
                // Sealed interface + marker methods on payload wrappers.
                models.push_str(&format!(
                    "// {} is a tagged union discriminated by `{}`.\ntype {} interface {{\n\tis{}()\n}}\n\n",
                    sum.name.pascal, sum.tag_field, sum.name.pascal, sum.name.pascal
                ));
                for (value, payload) in &sum.variants {
                    let exported = go_export(payload.pascal.as_str());
                    let wrapper_name = format!("{}{}", sum.name.pascal, exported);
                    let inner_type = go_export(payload.pascal.as_str());
                    let tag = sum.tag_field.as_str();
                    let marker_fn = sum.name.pascal.as_str();
                    let wrapper = format!(
                        "type {wrapper_name} struct {{\n\tValue {inner_type} `json:\"{tag}\"`\n}}\n\nfunc ({wrapper_name}) is{marker_fn}() {{}}\n\n"
                    );
                    models.push_str(&wrapper);
                    let _ = value;
                }
            }
            StgNode::Union(_) => {
                // Untagged: model as any until a discriminator exists.
                models.push_str("type Any = map[string]any\n\n");
            }
            StgNode::Alias(ty) => {
                models.push_str(&format!("type {} = {}\n\n", go_pascal(name), go_type(ty)));
            }
        }
    }

    // Operation methods on Client.
    for op in &graph.operations {
        let fn_name = go_export(&op.op_id.pascal);
        let mut args = vec!["ctx context.Context".to_string()];
        let mut path_expr = op.path_template.clone();
        for p in &op.params_path {
            args.push(format!("{} {}", p.name.snake, go_type(&p.ty)));
            path_expr = path_expr.replace(
                &format!("{{{}}}", p.name.original),
                &format!("{{{}}}", p.name.snake),
            );
        }
        let mut body_var = "nil".to_string();
        if let Some(body) = &op.request_body {
            let bn = format!("body {}", go_pascal(body));
            args.push(bn);
            body_var = "body".to_string();
        }
        let mut query_args: Vec<String> = Vec::new();
        for q in &op.params_query {
            query_args.push(q.name.snake.clone());
        }
        let _ = query_args;

        let fmt_path = format!("`{}`", path_expr.replace('{', "%v").replace('}', ""));
        client.push_str(&format!(
            "// {} calls {} {}.\nfunc (c *Client) {}({}) (string, error) {{\n",
            fn_name,
            op.method,
            op.path_template,
            fn_name,
            args.join(", ")
        ));
        client.push_str(&format!(
            "\tpath := fmt.Sprintf({fmt_path}{})\n",
            extra_sprintf_args(op)
        ));
        client.push_str(&format!(
            "\t_, err := c.doJSON(ctx, \"{}\", path, {}, nil)\n",
            op.method, body_var
        ));
        client.push_str("\tif err != nil {\n\t\treturn \"\", err\n\t}\n\treturn path, nil\n}\n\n");
    }

    vec![("models.go".into(), models), ("client.go".into(), client)]
}

fn extra_sprintf_args(op: &crate::stg::OpModel) -> String {
    op.params_path
        .iter()
        .map(|p| format!(", {}", p.name.snake))
        .collect::<Vec<_>>()
        .join("")
}

fn quote_go(literal: &str) -> String {
    format!("\"{}\"", literal.replace('"', "\\\""))
}

fn go_export(camel: &str) -> String {
    if camel.is_empty() {
        return camel.to_owned();
    }
    let mut c = camel.chars();
    match c.next() {
        Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
        None => String::new(),
    }
}

fn go_pascal(component: &str) -> String {
    go_export(&crate::stg::Ident::new(component).camel)
}

fn go_type(ty: &StgType) -> String {
    match ty {
        StgType::Named(n) => go_pascal(n),
        StgType::InlineStruct(s) => {
            let fields: Vec<String> = s
                .fields
                .iter()
                .map(|f| format!("{} {}", go_export(&f.ident.camel), go_type(&f.ty)))
                .collect();
            format!("struct {{ {} }}", fields.join("; "))
        }
        StgType::InlineEnum(e) => go_pascal(&e.name.pascal),
        StgType::InlineSum(s) => go_pascal(&s.name.pascal),
        StgType::InlineUnion(u) => go_pascal(&u.name.pascal),
        StgType::List(inner) => format!("[]{}", go_type(inner)),
        StgType::Dict(inner) => format!("map[string]{}", go_type(inner)),
        StgType::Optional(inner) => go_type(inner),
        StgType::Prim(p) => match p.base {
            Base::Str => "string".to_owned(),
            Base::Int => "int64".to_owned(),
            Base::Float => "float64".to_owned(),
            Base::Bool => "bool".to_owned(),
        },
    }
}
