//! Static API reference documentation emitters.
//!
//! One content model, three emitters:
//!
//! - [`html`] — a single self-contained HTML file (default `suspect docs`).
//! - [`markdown`] — structured Markdown files (frontmatter, per-tag and
//!   per-schema pages) for MDX/MDsvex pipelines.
//! - [`sveltekit`] — a runnable SvelteKit docs site whose generated layer
//!   (`src/lib/generated/**` + docs routes) is fully autogenerated while
//!   the maintained layer (theme, layout, landing page, configs) is
//!   scaffolded once and never overwritten, so a real site can be built
//!   around it.

mod html;
mod markdown;
mod sveltekit;

use std::collections::BTreeMap;

use suspect_low::{LowDoc, NodeRef};

pub use html::render_html;
pub use markdown::MarkdownReport;
pub use markdown::render_markdown;
pub use sveltekit::SvelteKitReport;
pub use sveltekit::render_sveltekit;

/// The API reference content model shared by every emitter.
#[derive(Debug, Clone, PartialEq)]
pub struct DocModel {
    /// `info.title`.
    pub title: String,
    /// `info.version`.
    pub version: String,
    /// `info.description`.
    pub description: Option<String>,
    /// Server URLs in declaration order.
    pub servers: Vec<String>,
    /// Operations grouped by primary tag, in path order.
    pub groups: Vec<OpGroup>,
    /// Component schemas in declaration order.
    pub schemas: Vec<SchemaDoc>,
}

/// One tag's operations.
#[derive(Debug, Clone, PartialEq)]
pub struct OpGroup {
    /// The tag name.
    pub tag: String,
    /// The operations carrying this tag.
    pub operations: Vec<Operation>,
}

/// One operation.
#[derive(Debug, Clone, PartialEq)]
pub struct Operation {
    /// Uppercase HTTP method.
    pub method: String,
    /// The path template.
    pub path: String,
    /// `operationId` (empty when absent).
    pub operation_id: String,
    /// `summary`.
    pub summary: String,
    /// `description`.
    pub description: String,
    /// `deprecated: true`.
    pub deprecated: bool,
    /// Operation-level parameters (path-level parameters are merged in).
    pub parameters: Vec<Param>,
    /// The request body, when declared.
    pub request_body: Option<BodySpec>,
    /// Responses in declaration order.
    pub responses: Vec<ResponseSpec>,
}

/// One parameter.
#[derive(Debug, Clone, PartialEq)]
pub struct Param {
    /// Parameter name.
    pub name: String,
    /// `in` (path/query/header/cookie).
    pub location: String,
    /// `required: true`.
    pub required: bool,
    /// Human type summary (`string`, `array<string>`, `Pet`, …).
    pub type_desc: String,
    /// `description`.
    pub description: String,
}

/// The request body.
#[derive(Debug, Clone, PartialEq)]
pub struct BodySpec {
    /// The single declared media type (first wins).
    pub content_type: String,
    /// Human type summary of the body schema.
    pub type_desc: String,
    /// `required: true`.
    pub required: bool,
}

/// One response.
#[derive(Debug, Clone, PartialEq)]
pub struct ResponseSpec {
    /// Status code or `default`.
    pub status: String,
    /// `description`.
    pub description: String,
    /// The single declared media type, when content exists.
    pub content_type: Option<String>,
    /// Human type summary of the response schema.
    pub type_desc: Option<String>,
}

/// One component schema.
#[derive(Debug, Clone, PartialEq)]
pub struct SchemaDoc {
    /// The component name.
    pub name: String,
    /// `description`.
    pub description: String,
    /// Property rows in declaration order.
    pub properties: Vec<Prop>,
}

/// One schema property.
#[derive(Debug, Clone, PartialEq)]
pub struct Prop {
    /// Property name.
    pub name: String,
    /// Human type summary.
    pub type_desc: String,
    /// Whether the property is in the schema's `required`.
    pub required: bool,
    /// `description`.
    pub description: String,
}

/// Extracts the shared content model from a parsed document.
#[must_use]
pub fn extract(low: &LowDoc) -> DocModel {
    let root = low.root();
    let title = root
        .get("info")
        .and_then(|i| i.get("title"))
        .and_then(|t| t.as_str())
        .unwrap_or("API Reference")
        .to_owned();
    let version = root
        .get("info")
        .and_then(|i| i.get("version"))
        .and_then(|v| v.as_str())
        .unwrap_or_default()
        .to_owned();
    let description = root
        .get("info")
        .and_then(|i| i.get("description"))
        .and_then(|d| d.as_str())
        .map(String::from);
    let servers = root
        .get("servers")
        .map(|s| {
            s.items()
                .iter()
                .filter_map(|server| server.get("url").and_then(|u| u.as_str()).map(String::from))
                .collect()
        })
        .unwrap_or_default();

    let mut by_tag: BTreeMap<String, Vec<Operation>> = BTreeMap::new();
    let mut tag_order: Vec<String> = Vec::new();
    // Declared tags keep their order and appear even when unused.
    if let Some(declared) = root.get("tags") {
        for tag in declared.items() {
            if let Some(name) = tag.get("name").and_then(|n| n.as_str()) {
                if !tag_order.contains(&name.to_owned()) {
                    tag_order.push(name.to_owned());
                }
            }
        }
    }
    if let Some(paths) = root.get("paths") {
        for path_entry in paths.entries() {
            let Some(path_item) = path_entry.value else {
                continue;
            };
            let path_level_params: Vec<Param> = path_item
                .get("parameters")
                .map(|p| p.items().iter().filter_map(param_of).collect())
                .unwrap_or_default();
            for method in [
                "get", "post", "put", "patch", "delete", "options", "head", "trace",
            ] {
                let Some(op) = path_item.get(method) else {
                    continue;
                };
                let tag = op
                    .get("tags")
                    .and_then(|t| t.items().first().map(|f| f.to_owned()))
                    .and_then(|t| t.as_str().map(String::from))
                    .unwrap_or_else(|| "Other".to_owned());
                if !tag_order.contains(&tag) {
                    tag_order.push(tag.clone());
                }
                let mut parameters: Vec<Param> = path_level_params.clone();
                if let Some(op_params) = op.get("parameters") {
                    for param in op_params.items() {
                        if let Some(param) = param_of(&param) {
                            // Operation-level wins over path-level by name+in.
                            parameters.retain(|existing| {
                                !(existing.name == param.name
                                    && existing.location == param.location)
                            });
                            parameters.push(param);
                        }
                    }
                }
                let request_body = op.get("requestBody").and_then(|body| {
                    let content_entries =
                        body.get("content").map(|c| c.entries()).unwrap_or_default();
                    let content_type = content_entries
                        .first()
                        .map(|e| e.key.to_owned())
                        .unwrap_or_else(|| "application/json".to_owned());
                    let type_desc = content_entries
                        .first()
                        .and_then(|e| e.value)
                        .and_then(|media| media.get("schema"))
                        .map(|schema| type_desc(&schema))
                        .unwrap_or_else(|| "unknown".to_owned());
                    let required = body
                        .get("required")
                        .and_then(|r| r.as_str())
                        .is_some_and(|v| v == "true");
                    Some(BodySpec {
                        content_type,
                        type_desc,
                        required,
                    })
                });
                let mut responses = Vec::new();
                if let Some(resps) = op.get("responses") {
                    for entry in resps.entries() {
                        let Some(resp) = entry.value else {
                            continue;
                        };
                        let content_entries =
                            resp.get("content").map(|c| c.entries()).unwrap_or_default();
                        let (content_type, type_desc) = match content_entries.first() {
                            Some(e) => {
                                let type_desc = e
                                    .value
                                    .and_then(|media| media.get("schema"))
                                    .map(|schema| type_desc(&schema));
                                (Some(e.key.to_owned()), type_desc)
                            }
                            None => (None, None),
                        };
                        responses.push(ResponseSpec {
                            status: entry.key.to_owned(),
                            description: resp
                                .get("description")
                                .and_then(|d| d.as_str())
                                .unwrap_or_default()
                                .to_owned(),
                            content_type,
                            type_desc,
                        });
                    }
                }
                by_tag.entry(tag.clone()).or_default().push(Operation {
                    method: method.to_ascii_uppercase(),
                    path: path_entry.key.to_owned(),
                    operation_id: op
                        .get("operationId")
                        .and_then(|s| s.as_str())
                        .unwrap_or_default()
                        .to_owned(),
                    summary: op
                        .get("summary")
                        .and_then(|s| s.as_str())
                        .unwrap_or_default()
                        .to_owned(),
                    description: op
                        .get("description")
                        .and_then(|d| d.as_str())
                        .unwrap_or_default()
                        .to_owned(),
                    deprecated: op
                        .get("deprecated")
                        .is_some_and(|d| d.as_str().is_some_and(|v| v == "true")),
                    parameters,
                    request_body,
                    responses,
                });
            }
        }
    }
    let groups: Vec<OpGroup> = tag_order
        .into_iter()
        .filter_map(|tag| {
            by_tag
                .remove(&tag)
                .map(|operations| OpGroup { tag, operations })
        })
        .collect();

    let schemas = root
        .get("components")
        .and_then(|c| c.get("schemas"))
        .map(|schemas| {
            schemas
                .entries()
                .iter()
                .filter_map(|entry| {
                    let schema = entry.value?;
                    let required: Vec<String> = schema
                        .get("required")
                        .map(|r| {
                            r.items()
                                .iter()
                                .filter_map(|i| i.as_str().map(String::from))
                                .collect()
                        })
                        .unwrap_or_default();
                    let properties = schema
                        .get("properties")
                        .map(|props| {
                            props
                                .entries()
                                .iter()
                                .filter_map(|entry| {
                                    let prop = entry.value?;
                                    Some(Prop {
                                        name: entry.key.to_owned(),
                                        type_desc: type_desc(&prop),
                                        required: required.contains(&entry.key.to_owned()),
                                        description: prop
                                            .get("description")
                                            .and_then(|d| d.as_str())
                                            .unwrap_or_default()
                                            .to_owned(),
                                    })
                                })
                                .collect()
                        })
                        .unwrap_or_default();
                    Some(SchemaDoc {
                        name: entry.key.to_owned(),
                        description: schema
                            .get("description")
                            .and_then(|d| d.as_str())
                            .unwrap_or_default()
                            .to_owned(),
                        properties,
                    })
                })
                .collect()
        })
        .unwrap_or_default();

    DocModel {
        title,
        version,
        description,
        servers,
        groups,
        schemas,
    }
}

/// Human type summary for a schema node: component name for `$ref`,
/// `array<T>` for arrays, `type (format)` for scalars, `object` with
/// property counts, `any` for untyped.
#[must_use]
pub fn type_desc(schema: &NodeRef<'_>) -> String {
    if let Some(r#ref) = schema.get("$ref").and_then(|r| r.as_str()) {
        if let Some(name) = r#ref.rsplit('/').next() {
            return name.to_owned();
        }
    }
    let format = schema.get("format").and_then(|f| f.as_str());
    match schema.get("type").and_then(|t| t.as_str()) {
        Some("array") => {
            let items = schema.get("items");
            let inner = items.map(|i| type_desc(&i)).unwrap_or_else(|| "?".into());
            format!("array<{inner}>")
        }
        Some("object") => {
            let count = schema
                .get("properties")
                .map(|p| p.entries().len())
                .unwrap_or(0);
            if count > 0 {
                format!("object ({count} properties)")
            } else {
                "object".to_owned()
            }
        }
        Some(base) => match format {
            Some(format) => format!("{base} ({format})"),
            None => base.to_owned(),
        },
        None => "any".to_owned(),
    }
}

/// One parameter row from a node, or `None` when it has no name.
fn param_of(node: &NodeRef<'_>) -> Option<Param> {
    Some(Param {
        name: node.get("name").and_then(|n| n.as_str())?.to_owned(),
        location: node
            .get("in")
            .and_then(|i| i.as_str())
            .unwrap_or_default()
            .to_owned(),
        required: node
            .get("required")
            .and_then(|r| r.as_str())
            .is_some_and(|v| v == "true"),
        type_desc: node
            .get("schema")
            .map(|schema| type_desc(&schema))
            .unwrap_or_else(|| "string".to_owned()),
        description: node
            .get("description")
            .and_then(|d| d.as_str())
            .unwrap_or_default()
            .to_owned(),
    })
}

/// Filesystem-safe slug for a tag or schema name.
#[must_use]
pub fn slugify(text: &str) -> String {
    let lower = text.to_ascii_lowercase();
    let mut out = String::with_capacity(lower.len());
    let mut last_dash = true; // suppress a leading dash
    for ch in lower.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
            last_dash = false;
        } else if !last_dash {
            out.push('-');
            last_dash = true;
        }
    }
    while out.ends_with('-') {
        out.pop();
    }
    if out.is_empty() {
        "unnamed".to_owned()
    } else {
        out
    }
}

/// Escapes HTML special characters.
#[must_use]
pub fn escape_html(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// Escapes a string for embedding in a single-quoted JS literal.
#[must_use]
pub fn escape_js(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            other => out.push(other),
        }
    }
    out
}

#[cfg(test)]
pub(crate) mod fixture {
    use suspect_low::LowDoc;
    use suspect_source::{Source, Uri};

    /// Shared fixture for emitter tests: two tags, parameters, request
    /// body, responses, and two schemas with a `$ref` between them.
    pub fn sample() -> LowDoc {
        const SPEC: &str = "\
openapi: 3.1.0
info:
  title: Test API
  version: '1.4.2'
  description: Test description
servers:
  - url: https://api.example.org/v1
tags: [{name: pets, description: Pet operations}]
paths:
  /pets:
    get:
      tags: [pets]
      operationId: listPets
      summary: Lists pets
      parameters:
        - name: limit
          in: query
          schema: {type: integer, format: int32}
        - name: cursor
          in: query
          description: Continuation cursor
          schema: {type: string}
      responses:
        '200':
          description: A page of pets
          content:
            application/json:
              schema:
                type: object
                properties:
                  data: {type: array, items: {$ref: '#/components/schemas/Pet'}}
    post:
      tags: [pets]
      operationId: createPet
      summary: Creates a pet
      requestBody:
        required: true
        content:
          application/json:
            schema: {$ref: '#/components/schemas/Pet'}
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Pet'}
  /adoption:
    get:
      tags: [adoption]
      operationId: listAdoptions
      responses:
        '200': {description: ok}
components:
  schemas:
    Pet:
      type: object
      description: A pet
      required: [name]
      properties:
        name: {type: string, description: The name}
        kind: {type: string, format: enum, description: Species}
        weight: {type: number, description: Kilograms}
        tag: {type: string}
";
        LowDoc::parse(
            Uri::parse("mem://docs.yaml").unwrap(),
            Source::from_vec(SPEC.as_bytes().to_vec()),
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extraction_builds_the_full_model() {
        let model = extract(&fixture::sample());
        assert_eq!(model.title, "Test API");
        assert_eq!(model.version, "1.4.2");
        assert_eq!(model.description.as_deref(), Some("Test description"));
        assert_eq!(model.servers, vec!["https://api.example.org/v1"]);

        // Declared tag order preserved; undeclared tag appended.
        let tags: Vec<&str> = model.groups.iter().map(|g| g.tag.as_str()).collect();
        assert_eq!(tags, vec!["pets", "adoption"]);
        let pets = &model.groups[0];
        assert_eq!(pets.operations.len(), 2);

        let list = &pets.operations[0];
        assert_eq!(list.method, "GET");
        assert_eq!(list.operation_id, "listPets");
        assert_eq!(list.parameters.len(), 2);
        assert_eq!(list.parameters[0].type_desc, "integer (int32)");
        assert_eq!(list.parameters[1].description, "Continuation cursor");
        let page = list.responses[0].type_desc.as_deref().unwrap();
        assert_eq!(page, "object (1 properties)");

        let create = &pets.operations[1];
        let body = create.request_body.as_ref().unwrap();
        assert!(body.required);
        assert_eq!(body.content_type, "application/json");
        assert_eq!(body.type_desc, "Pet");

        let pet = &model.schemas[0];
        assert_eq!(pet.name, "Pet");
        assert_eq!(pet.properties.len(), 4);
        assert_eq!(pet.properties[0].type_desc, "string");
        assert!(pet.properties[0].required);
        assert!(!pet.properties[3].required);
    }

    #[test]
    fn slugs_are_filesystem_safe() {
        assert_eq!(slugify("Pets & Dogs"), "pets-dogs");
        assert_eq!(slugify("  "), "unnamed");
        assert_eq!(slugify("PetStore"), "petstore");
    }
}
