//! SvelteKit docs-site emitter.
//!
//! Emits a runnable SvelteKit project split into two layers with
//! different regeneration semantics:
//!
//! - **Generated** (overwritten on every run): `src/lib/generated/docs/**`
//!   data modules plus the docs route (`src/routes/docs/[...slug]`).
//!   This is the fully-autogenerated part of the docs.
//! - **Maintained** (scaffolded once, never overwritten): the theme
//!   components (`src/lib/docs-theme/**`), root layout, landing page,
//!   app shell, and tool configs. The rest of the site is actively
//!   developed here; regeneration skips existing files.
//!
//! The contract is documented in the generated `README.md`: build the
//! site by editing the maintained layer, refresh the docs by re-running
//! `suspect docs --style sveltekit`.

use std::collections::BTreeMap;
use std::path::Path;

use super::{DocModel, escape_js, slugify};

/// What one SvelteKit render did.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SvelteKitReport {
    /// Generated-layer files written this run (overwritten).
    pub generated: Vec<String>,
    /// Maintained-layer files created this run (first scaffold).
    pub scaffolded: Vec<String>,
    /// Maintained-layer files that already existed and were left alone.
    pub skipped: Vec<String>,
}

/// Renders the SvelteKit docs site into `out_dir`.
///
/// # Errors
/// Propagates filesystem failures.
pub fn render_sveltekit(model: &DocModel, out_dir: &Path) -> std::io::Result<SvelteKitReport> {
    std::fs::create_dir_all(out_dir)?;
    let mut report = SvelteKitReport::default();

    // ------------------------------------------------ generated layer
    let slugs = Slugs::new(model);
    write_generated(
        &mut report,
        out_dir,
        "src/lib/generated/docs/toc.js",
        &toc_module(model, &slugs),
    );
    for group in &model.groups {
        let slug = &slugs.group_slugs[&group.tag];
        write_generated(
            &mut report,
            out_dir,
            &format!("src/lib/generated/docs/operations/{slug}.js"),
            &group_module(group, slug),
        );
    }
    for schema in &model.schemas {
        let slug = &slugs.schema_slugs[&schema.name];
        write_generated(
            &mut report,
            out_dir,
            &format!("src/lib/generated/docs/schemas/{slug}.js"),
            &schema_module(schema, slug),
        );
    }
    write_generated(
        &mut report,
        out_dir,
        "src/lib/generated/docs/index.js",
        &index_module(model, &slugs),
    );
    write_generated(
        &mut report,
        out_dir,
        "src/routes/docs/[...slug]/+page.js",
        LOAD_JS,
    );
    write_generated(
        &mut report,
        out_dir,
        "src/routes/docs/[...slug]/+page.svelte",
        DOCS_PAGE_SVELTE,
    );

    // ------------------------------------------------ maintained layer
    write_maintained(&mut report, out_dir, "package.json", &package_json(model));
    write_maintained(&mut report, out_dir, "svelte.config.js", SVELTE_CONFIG);
    write_maintained(&mut report, out_dir, "vite.config.js", VITE_CONFIG);
    write_maintained(&mut report, out_dir, "jsconfig.json", JSCONFIG);
    write_maintained(&mut report, out_dir, ".gitignore", GITIGNORE);
    write_maintained(&mut report, out_dir, "README.md", &readme(model));
    write_maintained(&mut report, out_dir, "src/app.html", APP_HTML);
    write_maintained(&mut report, out_dir, "src/app.css", APP_CSS);
    write_maintained(&mut report, out_dir, "src/routes/+layout.js", LAYOUT_JS);
    write_maintained(
        &mut report,
        out_dir,
        "src/routes/+layout.svelte",
        LAYOUT_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/routes/+page.svelte",
        LANDING_PAGE_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/lib/docs-theme/Sidebar.svelte",
        SIDEBAR_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/lib/docs-theme/Overview.svelte",
        OVERVIEW_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/lib/docs-theme/OperationGroup.svelte",
        OPERATION_GROUP_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/lib/docs-theme/SchemaView.svelte",
        SCHEMA_VIEW_SVELTE,
    );
    write_maintained(
        &mut report,
        out_dir,
        "src/lib/docs-theme/Markdown.svelte",
        MARKDOWN_SVELTE,
    );

    Ok(report)
}

/// Writes a generated-layer file, creating parent directories.
fn write_generated(report: &mut SvelteKitReport, out_dir: &Path, relative: &str, content: &str) {
    let path = out_dir.join(relative);
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("generated parent directory");
    }
    std::fs::write(&path, content).expect("generated file write");
    report.generated.push(relative.to_owned());
}

/// Writes a maintained-layer file only when it does not exist yet.
fn write_maintained(report: &mut SvelteKitReport, out_dir: &Path, relative: &str, content: &str) {
    let path = out_dir.join(relative);
    if path.exists() {
        report.skipped.push(relative.to_owned());
        return;
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("maintained parent directory");
    }
    std::fs::write(&path, content).expect("maintained file write");
    report.scaffolded.push(relative.to_owned());
}

/// Slug assignments shared by the generated modules.
struct Slugs {
    /// Tag → URL/file slug (deduplicated).
    group_slugs: BTreeMap<String, String>,
    /// Schema name → URL/file slug (deduplicated).
    schema_slugs: BTreeMap<String, String>,
}

impl Slugs {
    fn new(model: &DocModel) -> Self {
        let mut issued: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        let mut group_slugs = BTreeMap::new();
        for group in &model.groups {
            let slug = dedupe(&slugify(&group.tag), &mut issued);
            group_slugs.insert(group.tag.clone(), slug);
        }
        let mut schema_slugs = BTreeMap::new();
        for schema in &model.schemas {
            let slug = dedupe(&slugify(&schema.name), &mut issued);
            schema_slugs.insert(schema.name.clone(), slug);
        }
        Self {
            group_slugs,
            schema_slugs,
        }
    }
}

/// Deduplicates a slug against all issued ones with numeric suffixes.
fn dedupe(base: &str, issued: &mut std::collections::BTreeSet<String>) -> String {
    let mut candidate = base.to_owned();
    let mut suffix = 2;
    while issued.contains(&candidate) {
        candidate = format!("{base}-{suffix}");
        suffix += 1;
    }
    issued.insert(candidate.clone());
    candidate
}

/// A valid JS identifier for an import binding.
fn ident(text: &str) -> String {
    let mut out = String::new();
    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        out.push_str("mod");
    }
    out
}

/// The `toc.js` data module: metadata plus navigation lists.
fn toc_module(model: &DocModel, slugs: &Slugs) -> String {
    let groups: Vec<String> = model
        .groups
        .iter()
        .map(|group| {
            let slug = &slugs.group_slugs[&group.tag];
            format!(
                "\t{{ tag: '{}', slug: '{}', href: '/docs/operations/{}', count: {} }},",
                escape_js(&group.tag),
                escape_js(slug),
                escape_js(slug),
                group.operations.len()
            )
        })
        .collect();
    let schemas: Vec<String> = model
        .schemas
        .iter()
        .map(|schema| {
            let slug = &slugs.schema_slugs[&schema.name];
            format!(
                "\t{{ name: '{}', slug: '{}', href: '/docs/schemas/{}' }},",
                escape_js(&schema.name),
                escape_js(slug),
                escape_js(slug)
            )
        })
        .collect();
    let description = model.description.clone().unwrap_or_default();
    format!(
        "// GENERATED by suspect docs — overwritten on every regeneration.\n\
         // The maintained layer lives in src/lib/docs-theme and src/routes.\n\n\
         export const meta = {{\n\ttitle: '{}',\n\tversion: '{}',\n\tdescription: '{}',\n\t\
         servers: [{}],\n}};\n\n\
         export const groups = [\n{}\n];\n\n\
         export const schemas = [\n{}\n];\n",
        escape_js(&model.title),
        escape_js(&model.version),
        escape_js(&description),
        model
            .servers
            .iter()
            .map(|s| format!("'{}'", escape_js(s)))
            .collect::<Vec<_>>()
            .join(", "),
        groups.join("\n"),
        schemas.join("\n"),
    )
}

/// One operation-group data module.
fn group_module(group: &super::OpGroup, slug: &str) -> String {
    let operations: Vec<serde_json::Value> = group
        .operations
        .iter()
        .map(|op| {
            serde_json::json!({
                "method": op.method,
                "path": op.path,
                "operationId": op.operation_id,
                "summary": op.summary,
                "description": op.description,
                "deprecated": op.deprecated,
                "parameters": op.parameters.iter().map(|p| serde_json::json!({
                    "name": p.name,
                    "in": p.location,
                    "required": p.required,
                    "type": p.type_desc,
                    "description": p.description,
                })).collect::<Vec<_>>(),
                "requestBody": op.request_body.as_ref().map(|b| serde_json::json!({
                    "contentType": b.content_type,
                    "type": b.type_desc,
                    "required": b.required,
                })),
                "responses": op.responses.iter().map(|r| serde_json::json!({
                    "status": r.status,
                    "description": r.description,
                    "contentType": r.content_type,
                    "type": r.type_desc,
                })).collect::<Vec<_>>(),
            })
        })
        .collect();
    let body = serde_json::to_string_pretty(&operations).unwrap_or_else(|_| "[]".to_owned());
    format!(
        "// GENERATED by suspect docs — overwritten on every regeneration.\n\n\
         export const tag = '{}';\n\
         export const slug = '{}';\n\
         export const operations = {};\n",
        escape_js(&group.tag),
        escape_js(slug),
        body
    )
}

/// One schema data module.
fn schema_module(schema: &super::SchemaDoc, slug: &str) -> String {
    let value = serde_json::json!({
        "name": schema.name,
        "slug": slug,
        "description": schema.description,
        "properties": schema.properties.iter().map(|p| serde_json::json!({
            "name": p.name,
            "type": p.type_desc,
            "required": p.required,
            "description": p.description,
        })).collect::<Vec<_>>(),
    });
    let body = serde_json::to_string_pretty(&value).unwrap_or_else(|_| "{}".to_owned());
    format!(
        "// GENERATED by suspect docs — overwritten on every regeneration.\n\n\
         export const schema = {body};\n"
    )
}

/// The aggregate module mapping slugs to the data modules.
fn index_module(model: &DocModel, slugs: &Slugs) -> String {
    let mut out =
        String::from("// GENERATED by suspect docs — overwritten on every regeneration.\n\n");
    let mut operation_entries = Vec::new();
    for group in &model.groups {
        let slug = &slugs.group_slugs[&group.tag];
        let binding = format!("op_{}", ident(slug));
        out.push_str(&format!(
            "import * as {binding} from './operations/{slug}.js';\n"
        ));
        operation_entries.push(format!("\t'{}': {binding},", escape_js(slug)));
    }
    let mut schema_entries = Vec::new();
    for schema in &model.schemas {
        let slug = &slugs.schema_slugs[&schema.name];
        let binding = format!("schema_{}", ident(slug));
        out.push_str(&format!(
            "import * as {binding} from './schemas/{slug}.js';\n"
        ));
        schema_entries.push(format!("\t'{}': {binding},", escape_js(slug)));
    }
    out.push_str("\nexport const operationModules = {\n");
    out.push_str(&operation_entries.join("\n"));
    out.push_str("\n};\n\nexport const schemaModules = {\n");
    out.push_str(&schema_entries.join("\n"));
    out.push_str("\n};\n");
    let _ = model;
    out
}

// ---------------------------------------------------------------- templates

const LOAD_JS: &str = r"// GENERATED by suspect docs — overwritten on every regeneration.
import { error } from '@sveltejs/kit';
import { operationModules, schemaModules } from '$lib/generated/docs/index.js';
import { meta, groups, schemas } from '$lib/generated/docs/toc.js';

const navigation = { meta, groups, schemas };

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
  // `/docs` lands here with an empty rest param.
  const slug = params.slug || 'overview';
  if (slug === 'overview') {
    return { overview: true, navigation, slug };
  }
  if (slug.startsWith('operations/')) {
    const mod = operationModules[slug.slice('operations/'.length)];
    if (!mod) error(404, 'Docs page not found');
    return {
      group: { tag: mod.tag, slug: mod.slug, operations: mod.operations },
      navigation,
      slug
    };
  }
  if (slug.startsWith('schemas/')) {
    const mod = schemaModules[slug.slice('schemas/'.length)];
    if (!mod) error(404, 'Docs page not found');
    return { schema: mod.schema, navigation, slug };
  }
  error(404, 'Docs page not found');
}
";

const DOCS_PAGE_SVELTE: &str = r"<!-- GENERATED by suspect docs — overwritten on every regeneration. -->
<script>
  import Sidebar from '$lib/docs-theme/Sidebar.svelte';
  import Overview from '$lib/docs-theme/Overview.svelte';
  import OperationGroup from '$lib/docs-theme/OperationGroup.svelte';
  import SchemaView from '$lib/docs-theme/SchemaView.svelte';

  export let data;
</script>

<div class='docs-shell'>
  <Sidebar navigation={data.navigation} currentSlug={data.slug} />
  <main class='docs-main'>
    {#if data.overview}
      <Overview {data} />
    {:else if data.group}
      <OperationGroup group={data.group} />
    {:else if data.schema}
      <SchemaView schema={data.schema} />
    {/if}
  </main>
</div>
";

const SVELTE_CONFIG: &str = r"// MAINTAINED by the site team — suspect docs never overwrites this file.
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter()
  }
};

export default config;
";

const VITE_CONFIG: &str = r"// MAINTAINED by the site team — suspect docs never overwrites this file.
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()]
});
";

const JSCONFIG: &str = r#"{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "checkJs": false
  }
}
"#;

const GITIGNORE: &str = r"# MAINTAINED by the site team — suspect docs never overwrites this file.
node_modules/
.svelte-kit/
build/
";

const APP_HTML: &str = r#"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
"#;

const LAYOUT_JS: &str = r"// MAINTAINED by the site team — suspect docs never overwrites this file.
// Prerender everything: the docs site ships as static files.
export const prerender = true;
";

const LAYOUT_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file.
     Add site-wide chrome (headers, footers, analytics) around the slot. -->
<script>
  import '../app.css';
</script>

<slot />
";

const LANDING_PAGE_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file.
     This is the site's front page; the generated docs live under /docs. -->
<script>
  export let data;
</script>

<svelte:head>
  <title>Home</title>
</svelte:head>

<main class='landing'>
  <h1>Welcome</h1>
  <p>This site is built around autogenerated API reference docs.</p>
  <p><a class='cta' href='/docs'>Read the API docs</a></p>
</main>
";

const SIDEBAR_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->
<script>
  export let navigation;
  export let currentSlug = '';

  const href = (base) => '/docs/' + base;
</script>

<aside class='docs-sidebar'>
  <a class='docs-home' href='/docs'>{navigation.meta.title}</a>
  <p class='docs-version'>v{navigation.meta.version}</p>

  <p class='docs-section'>Operations</p>
  {#each navigation.groups as group}
    <a
      href={href('operations/' + group.slug)}
      class:active={currentSlug === 'operations/' + group.slug}
    >
      {group.tag} <span class='count'>{group.count}</span>
    </a>
  {/each}

  {#if navigation.schemas.length}
    <p class='docs-section'>Schemas</p>
    {#each navigation.schemas as schema}
      <a
        href={href('schemas/' + schema.slug)}
        class:active={currentSlug === 'schemas/' + schema.slug}
      >{schema.name}</a>
    {/each}
  {/if}
</aside>
";

const OVERVIEW_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->
<script>
  import Markdown from './Markdown.svelte';

  export let data;
</script>

<svelte:head>
  <title>{data.navigation.meta.title}</title>
</svelte:head>

<h1>{data.navigation.meta.title}</h1>
<p class='docs-version-line'>Version {data.navigation.meta.version}</p>

{#if data.navigation.meta.description}
  <Markdown text={data.navigation.meta.description} />
{/if}

{#if data.navigation.meta.servers.length}
  <h2>Servers</h2>
  <ul class='servers'>
    {#each data.navigation.meta.servers as server}
      <li><code>{server}</code></li>
    {/each}
  </ul>
{/if}

{#if data.navigation.groups.length}
  <h2>Operations</h2>
  <ul class='card-list'>
    {#each data.navigation.groups as group}
      <li>
        <a href={group.href}>{group.tag}</a>
        <span class='count'>{group.count} operations</span>
      </li>
    {/each}
  </ul>
{/if}

{#if data.navigation.schemas.length}
  <h2>Schemas</h2>
  <ul class='card-list'>
    {#each data.navigation.schemas as schema}
      <li><a href={schema.href}>{schema.name}</a></li>
    {/each}
  </ul>
{/if}
";

const OPERATION_GROUP_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->
<script>
  import Markdown from './Markdown.svelte';

  export let group;
</script>

<svelte:head>
  <title>{group.tag} — operations</title>
</svelte:head>

<h1>{group.tag} operations</h1>

{#each group.operations as op}
  <section class='operation'>
    <h2>
      <span class='method {op.method.toLowerCase()}'>{op.method}</span>
      <code>{op.path}</code>
    </h2>
    {#if op.summary}<p class='summary'>{op.summary}</p>{/if}
    {#if op.description}<Markdown text={op.description} />{/if}
    {#if op.deprecated}
      <p class='deprecated'>DEPRECATED — may be removed in a future version.</p>
    {/if}
    {#if op.operationId}
      <p class='opid'>Operation ID: <code>{op.operationId}</code></p>
    {/if}

    {#if op.parameters.length}
      <h3>Parameters</h3>
      <table>
        <thead>
          <tr><th>Name</th><th>In</th><th>Type</th><th>Required</th><th>Description</th></tr>
        </thead>
        <tbody>
          {#each op.parameters as param}
            <tr>
              <td><code>{param.name}</code></td>
              <td>{param.in}</td>
              <td>{param.type}</td>
              <td>{param.required ? 'yes' : 'no'}</td>
              <td>{param.description}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}

    {#if op.requestBody}
      <h3>Request body</h3>
      <p>
        Content type <code>{op.requestBody.contentType}</code>,
        type <code>{op.requestBody.type}</code>
        {op.requestBody.required ? ', required' : ', optional'}.
      </p>
    {/if}

    {#if op.responses.length}
      <h3>Responses</h3>
      <table>
        <thead>
          <tr><th>Status</th><th>Description</th><th>Content type</th><th>Type</th></tr>
        </thead>
        <tbody>
          {#each op.responses as response}
            <tr>
              <td>{response.status}</td>
              <td>{response.description}</td>
              <td>{response.contentType ?? '—'}</td>
              <td>{response.type ?? '—'}</td>
            </tr>
          {/each}
        </tbody>
      </table>
    {/if}
  </section>
{/each}
";

const SCHEMA_VIEW_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->
<script>
  export let schema;
</script>

<svelte:head>
  <title>{schema.name}</title>
</svelte:head>

<h1><code>{schema.name}</code></h1>
{#if schema.description}<p>{schema.description}</p>{/if}

{#if schema.properties.length}
  <h2>Properties</h2>
  <table>
    <thead>
      <tr><th>Property</th><th>Type</th><th>Required</th><th>Description</th></tr>
    </thead>
    <tbody>
      {#each schema.properties as prop}
        <tr>
          <td><code>{prop.name}</code></td>
          <td>{prop.type}</td>
          <td>{prop.required ? 'yes' : 'no'}</td>
          <td>{prop.description}</td>
        </tr>
      {/each}
    </tbody>
  </table>
{:else}
  <p><em>No declared properties.</em></p>
{/if}
";

const MARKDOWN_SVELTE: &str = r"<!-- MAINTAINED by the site team — suspect docs never overwrites this file.
     Renders descriptions safely: HTML-escape first, then apply a small
     inline subset (bold, code). Raw HTML in descriptions is never trusted. -->
<script>
  export let text = '';

  const escape = (s) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const inline = (s) =>
    escape(s)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>');
  const blocks = text.split(/\n{2,}/).filter((block) => block.trim().length);
</script>

<div class='markdown'>
  {#each blocks as block}
    <p>{@html inline(block.trim())}</p>
  {/each}
</div>
";

/// The project README: the generated/maintained contract.
fn readme(model: &DocModel) -> String {
    format!(
        r#"<!-- MAINTAINED by the site team — suspect docs never overwrites this file. -->

# {title} docs site

A SvelteKit site whose API reference is fully autogenerated by
[`suspect docs --style sveltekit`](https://github.com/LukasParke/suspect).

## The two layers

| Layer | Regeneration | Location |
|---|---|---|
| Generated docs | **Overwritten every run** | `src/lib/generated/docs/**`, `src/routes/docs/**` |
| Maintained site | **Scaffolded once, never touched** | everything else |

Never edit files under `src/lib/generated/` or `src/routes/docs/` — the
next regeneration replaces them. Build the site in the maintained layer:

- `src/lib/docs-theme/` — the docs presentation components (Sidebar,
  Overview, OperationGroup, SchemaView, Markdown). Edit freely to
  restyle the reference.
- `src/routes/+layout.svelte` + `src/app.css` — site chrome and global
  styles; wrap the docs in a header/footer here.
- `src/routes/+page.svelte` — the landing page; add any routes around
  `/docs` as usual.

## Commands

```sh
npm install
npm run dev        # develop the whole site
npm run build      # static build (adapter-static, fully prerendered)
npm run preview
```

## Regenerating the docs

```sh
suspect docs <openapi.yaml> --style sveltekit --out .
```

Only the generated layer changes; the maintained layer — including any
routes, pages, and theme edits you added — is preserved.

## Data shape

`src/lib/generated/docs/index.js` exports `operationModules` and
`schemaModules` keyed by slug; `toc.js` exports `meta`, `groups`, and
`schemas` for navigation. Import them directly from your own pages to
surface API data anywhere in the site (current API version:
{version}).
"#,
        title = model.title,
        version = model.version,
    )
}

/// package.json with static-adapter toolchain. Pure JSON — npm rejects
/// comments, so the maintained-marker lives in the README contract table.
fn package_json(model: &DocModel) -> String {
    let name = format!("{}-docs", slugify(&model.title));
    let value = serde_json::json!({
        "name": name,
        "private": true,
        "version": "0.1.0",
        "type": "module",
        "scripts": {
            "dev": "vite dev",
            "build": "vite build",
            "preview": "vite preview"
        },
        "devDependencies": {
            "@sveltejs/adapter-static": "^3.0.0",
            "@sveltejs/kit": "^2.0.0",
            "@sveltejs/vite-plugin-svelte": "^7.0.0",
            "svelte": "^5.0.0",
            "vite": "^8.0.0"
        }
    });
    serde_json::to_string_pretty(&value).unwrap_or_else(|_| "{}".to_owned()) + "\n"
}

/// Global stylesheet for the scaffolded shell and theme.
const APP_CSS: &str = r#"/* MAINTAINED by the site team — suspect docs never overwrites this file. */
:root {
  --ink: #1a1a2e;
  --muted: #5b6472;
  --line: #d9dee5;
  --accent: #4a6fa5;
  --surface: #f0f4f8;
}

* { box-sizing: border-box; }

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
  color: var(--ink);
}

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

code {
  background: var(--surface);
  padding: 0.1rem 0.35rem;
  border-radius: 3px;
  font-size: 0.9em;
}

table {
  border-collapse: collapse;
  width: 100%;
  margin: 0.6rem 0 1.2rem;
}
th, td {
  border: 1px solid var(--line);
  padding: 0.4rem 0.6rem;
  text-align: left;
  vertical-align: top;
}
th { background: var(--surface); }

.landing {
  max-width: 48rem;
  margin: 4rem auto;
  padding: 0 1rem;
}
.landing .cta {
  display: inline-block;
  margin-top: 0.6rem;
  padding: 0.5rem 1rem;
  background: var(--accent);
  color: #fff;
  border-radius: 6px;
}
.landing .cta:hover { text-decoration: none; filter: brightness(1.1); }

.docs-shell {
  display: grid;
  grid-template-columns: 16rem 1fr;
  min-height: 100vh;
}

.docs-sidebar {
  border-right: 1px solid var(--line);
  padding: 1.2rem 1rem;
  background: #fbfcfe;
}
.docs-sidebar .docs-home {
  display: block;
  font-weight: 700;
  font-size: 1.05rem;
  color: var(--ink);
}
.docs-sidebar .docs-version { color: var(--muted); font-size: 0.8rem; margin: 0.1rem 0 0; }
.docs-sidebar .docs-section {
  text-transform: uppercase;
  letter-spacing: 0.06em;
  font-size: 0.72rem;
  color: var(--muted);
  margin: 1.2rem 0 0.3rem;
}
.docs-sidebar a:not(.docs-home) {
  display: flex;
  justify-content: space-between;
  padding: 0.28rem 0.5rem;
  border-radius: 5px;
  color: var(--ink);
  font-size: 0.92rem;
}
.docs-sidebar a.active { background: var(--surface); font-weight: 600; }
.docs-sidebar .count { color: var(--muted); font-size: 0.78rem; }

.docs-main {
  max-width: 56rem;
  padding: 1.6rem 2.2rem 4rem;
}

.docs-main h1 { border-bottom: 2px solid var(--accent); padding-bottom: 0.3rem; }
.docs-version-line { color: var(--muted); }

.operation { border-top: 1px solid var(--line); margin-top: 2rem; padding-top: 1rem; }
.operation .method {
  display: inline-block;
  font-weight: 700;
  font-size: 0.75rem;
  padding: 0.12rem 0.5rem;
  border-radius: 4px;
  color: #fff;
  vertical-align: middle;
}
.method.GET { background: #2e7d32; }
.method.POST { background: #1565c0; }
.method.PUT { background: #e65100; }
.method.PATCH { background: #6a1b9a; }
.method.DELETE { background: #c62828; }
.method.OPTIONS, .method.HEAD, .method.TRACE { background: #616161; }

.deprecated { color: #b26a00; font-weight: 600; }
.opid { color: var(--muted); font-size: 0.9rem; }

.servers li { margin: 0.2rem 0; }
.card-list li { margin: 0.3rem 0; }
.card-list .count { color: var(--muted); margin-left: 0.5rem; font-size: 0.85rem; }

.markdown p { line-height: 1.55; }
"#;

#[cfg(test)]
mod tests {
    use super::super::{extract, fixture};
    use super::*;

    #[test]
    fn scaffolds_then_regen_updates_only_generated_layer() {
        let model = extract(&fixture::sample());
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("site");

        // First run: everything scaffolded.
        let first = render_sveltekit(&model, &out).unwrap();
        assert!(first.skipped.is_empty());
        assert!(
            first
                .scaffolded
                .contains(&"src/lib/docs-theme/Sidebar.svelte".to_owned())
        );
        assert!(
            first
                .generated
                .contains(&"src/lib/generated/docs/index.js".to_owned())
        );
        assert!(
            first
                .generated
                .contains(&"src/routes/docs/[...slug]/+page.js".to_owned())
        );
        let scaffolded_count = first.scaffolded.len();
        assert!(scaffolded_count >= 15, "full scaffold: {scaffolded_count}");

        // A maintainer personalizes the theme and adds a route.
        let sidebar = out.join("src/lib/docs-theme/Sidebar.svelte");
        let personalized = std::fs::read_to_string(&sidebar).unwrap() + "\n<!-- mine -->";
        std::fs::write(&sidebar, &personalized).unwrap();
        let extra = out.join("src/routes/about/+page.svelte");
        std::fs::create_dir_all(extra.parent().unwrap()).unwrap();
        std::fs::write(&extra, "<h1>About</h1>").unwrap();

        // Second run: generated layer refreshed, maintained layer intact.
        let second = render_sveltekit(&model, &out).unwrap();
        assert!(second.scaffolded.is_empty());
        assert_eq!(second.skipped.len(), scaffolded_count);
        assert!(
            second
                .generated
                .contains(&"src/lib/generated/docs/operations/pets.js".to_owned())
        );
        assert_eq!(
            std::fs::read_to_string(&sidebar).unwrap(),
            personalized,
            "maintained theme must survive regeneration"
        );
        assert_eq!(
            std::fs::read_to_string(&extra).unwrap(),
            "<h1>About</h1>",
            "maintained routes must survive regeneration"
        );
    }

    #[test]
    fn generated_data_modules_carry_the_model() {
        let model = extract(&fixture::sample());
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("site");
        render_sveltekit(&model, &out).unwrap();

        let index = std::fs::read_to_string(out.join("src/lib/generated/docs/index.js")).unwrap();
        assert!(index.contains("import * as op_pets from './operations/pets.js';"));
        assert!(index.contains("import * as schema_pet from './schemas/pet.js';"));
        assert!(index.contains("'pets': op_pets,"));
        assert!(index.contains("'pet': schema_pet,"));

        let toc = std::fs::read_to_string(out.join("src/lib/generated/docs/toc.js")).unwrap();
        assert!(toc.contains("title: 'Test API'"));
        assert!(toc.contains("href: '/docs/operations/pets', count: 2"));
        assert!(toc.contains("href: '/docs/schemas/pet'"));

        let pets =
            std::fs::read_to_string(out.join("src/lib/generated/docs/operations/pets.js")).unwrap();
        assert!(pets.contains("\"method\": \"GET\""));
        assert!(pets.contains("\"operationId\": \"listPets\""));
        assert!(pets.contains("\"type\": \"Pet\""));

        let load = std::fs::read_to_string(out.join("src/routes/docs/[...slug]/+page.js")).unwrap();
        assert!(load.contains("operationModules[slug.slice('operations/'.length)]"));
        assert!(load.contains("error(404, 'Docs page not found')"));

        // Route slugs are deduplicated across groups and schemas.
        let pet =
            std::fs::read_to_string(out.join("src/lib/generated/docs/schemas/pet.js")).unwrap();
        assert!(pet.contains("export const schema = {"));
        assert!(pet.contains("\"required\": true"));
    }

    #[test]
    fn slugs_deduplicate_across_kinds() {
        let mut issued = std::collections::BTreeSet::new();
        assert_eq!(dedupe("pets", &mut issued), "pets");
        assert_eq!(dedupe("pets", &mut issued), "pets-2");
        assert_eq!(dedupe("pets", &mut issued), "pets-3");
    }

    #[test]
    fn package_json_is_valid_json_and_readme_documents_the_contract() {
        let model = extract(&fixture::sample());
        let dir = tempfile::tempdir().unwrap();
        let out = dir.path().join("site");
        render_sveltekit(&model, &out).unwrap();

        let package = std::fs::read_to_string(out.join("package.json")).unwrap();
        let json: serde_json::Value = serde_json::from_str(&package).unwrap();
        assert_eq!(json["name"], "test-api-docs");
        assert_eq!(json["scripts"]["build"], "vite build");

        let readme = std::fs::read_to_string(out.join("README.md")).unwrap();
        assert!(readme.contains("**Overwritten every run**"));
        assert!(readme.contains("src/lib/generated/"));
        assert!(readme.contains("suspect docs <openapi.yaml> --style sveltekit --out ."));
    }
}
