[package]
name = "suspect-lint"
description = "Spectral-compatible linting engine and builtin rule packs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
suspect-low.workspace = true
suspect-source.workspace = true
suspect-jsonpath.workspace = true
suspect-syntax.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
regex.workspace = true
rayon.workspace = true
serde.workspace = true
suspect-ir.workspace = true

[dev-dependencies]
serde_json.workspace = true
criterion.workspace = true
suspect-ref.workspace = true

[[bench]]
name = "lint"
harness = false
