//! Plans generated files before touching output, then replaces changed files
//! atomically through confined directory handles. Unchanged files are never
//! rewritten. Optional versioned ownership manifests allow obsolete generated
//! files to be removed only after checking their recorded full-byte identity.

#![deny(missing_docs)]

use std::borrow::Cow;
use std::collections::BTreeSet;
use std::ffi::{OsStr, OsString};
use std::fmt;
use std::io::{self, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use cap_fs_ext::{DirExt, FollowSymlinks, OpenOptionsFollowExt};
use cap_std::ambient_authority;
use cap_std::fs::{Dir, OpenOptions, Permissions};
use unicode_normalization::UnicodeNormalization;

mod ownership;
pub use ownership::{
    Adoption, OWNERSHIP_MANIFEST, OwnedBatch, OwnershipChange, OwnershipChangeKind, OwnershipReport,
};

/// An invalid artifact plan or a failed filesystem operation.
#[derive(Debug)]
pub struct ArtifactError(String);

impl fmt::Display for ArtifactError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for ArtifactError {}

impl From<io::Error> for ArtifactError {
    fn from(error: io::Error) -> Self {
        Self(error.to_string())
    }
}

/// One generated output, borrowed until its batch has been committed.
pub struct Artifact<'a> {
    /// A relative path using forward slashes, with no `..` components.
    pub path: &'a Path,
    /// Complete file bytes.
    pub content: &'a [u8],
}

/// How a generated file differs from the existing output.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Change {
    /// No existing file occupies the target.
    Created,
    /// The existing file has different bytes.
    Changed,
    /// Existing and generated bytes are identical.
    Unchanged,
}

/// An output and the existing bytes inspected during preflight.
pub struct PlannedArtifact<'a> {
    path: PathBuf,
    content: Cow<'a, [u8]>,
    existing: Option<Vec<u8>>,
    permissions: Option<Permissions>,
    managed: Option<ownership::ManagedContent>,
}

impl PlannedArtifact<'_> {
    /// Normalized path relative to the output root.
    #[must_use]
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Existing file bytes, or `None` for a new file.
    #[must_use]
    pub fn existing(&self) -> Option<&[u8]> {
        self.existing.as_deref()
    }

    /// Complete planned file bytes.
    #[must_use]
    pub fn content(&self) -> &[u8] {
        &self.content
    }

    /// Replaces planned bytes, for example after preserving user sections.
    pub fn replace_content(&mut self, content: Vec<u8>) {
        self.content = Cow::Owned(content);
    }

    /// Compares the planned content with the preflight snapshot.
    #[must_use]
    pub fn change(&self) -> Change {
        match self.existing() {
            None => Change::Created,
            Some(existing) if existing == self.content() => Change::Unchanged,
            Some(_) => Change::Changed,
        }
    }
}

/// A validated output set with existing-file snapshots.
///
/// Preparation is read-only. Callers may inspect changes and adjust content
/// before committing. The root and child directories are accessed through
/// directory handles, and symlinks are never followed below the output root.
pub struct ArtifactBatch<'a> {
    root: OutputRoot,
    files: Vec<PlannedArtifact<'a>>,
}

impl<'a> ArtifactBatch<'a> {
    /// Validates every target and reads existing files without writing output.
    ///
    /// Duplicate, case-colliding and file/directory-conflicting paths are
    /// rejected before filesystem writes. Paths must be nonempty, UTF-8,
    /// relative, and contain neither parent traversal nor backslashes.
    /// Windows device names, alternate streams and trailing dots/spaces are
    /// rejected on every platform for portable output plans.
    ///
    /// # Errors
    /// Returns an error for invalid targets, symlinks, non-file targets, or
    /// filesystem failures. Missing output directories are allowed.
    pub fn prepare(
        root: &Path,
        artifacts: impl IntoIterator<Item = Artifact<'a>>,
    ) -> Result<Self, ArtifactError> {
        let mut files = Vec::new();
        let mut targets = BTreeSet::new();
        for artifact in artifacts {
            let path = normalize_target(artifact.path)?;
            let folded = PathBuf::from(
                path.to_string_lossy()
                    .to_lowercase()
                    .to_uppercase()
                    .nfc()
                    .collect::<String>(),
            );
            if !targets.insert(folded) {
                return Err(ArtifactError(format!(
                    "duplicate or case-colliding artifact target {}",
                    path.display()
                )));
            }
            files.push(PlannedArtifact {
                path,
                content: Cow::Borrowed(artifact.content),
                existing: None,
                permissions: None,
                managed: None,
            });
        }
        for target in &targets {
            for ancestor in target.ancestors().skip(1) {
                if targets.contains(ancestor) {
                    return Err(ArtifactError(format!(
                        "artifact target {} conflicts with file target {}",
                        target.display(),
                        ancestor.display()
                    )));
                }
            }
        }
        let root = OutputRoot::open(root)?;
        if let Some(directory) = root.directory(false)? {
            for file in &mut files {
                if let Some((bytes, permissions)) = read_existing(&directory, &file.path)? {
                    file.existing = Some(bytes);
                    file.permissions = Some(permissions);
                }
            }
        }
        Ok(Self { root, files })
    }

    /// Absolute output root used for diagnostic and preview paths.
    #[must_use]
    pub fn root(&self) -> &Path {
        &self.root.path
    }

    /// Planned artifacts in the input order.
    #[must_use]
    pub fn files(&self) -> &[PlannedArtifact<'a>] {
        &self.files
    }

    /// Planned artifacts whose content may be adjusted before commit.
    pub fn files_mut(&mut self) -> &mut [PlannedArtifact<'a>] {
        &mut self.files
    }

    /// Stages every changed file, then atomically replaces each destination.
    ///
    /// Identical files keep their inode and modification time. Staging errors
    /// leave existing files intact. Replacement is atomic per file, not a
    /// transaction across the whole batch; an error during the rename phase
    /// can leave earlier files updated. Existing file permissions are kept.
    ///
    /// # Errors
    /// Returns an error if content changes or unsafe paths are observed when
    /// rechecking preflight, or staging/replacement fails. These checks are
    /// best effort: they do not lock out concurrent filesystem changes.
    pub fn commit(self) -> Result<(), ArtifactError> {
        self.verify_existing()?;
        if self
            .files
            .iter()
            .all(|file| file.change() == Change::Unchanged)
        {
            return Ok(());
        }
        let root = self.root.directory(true)?.expect("created output root");
        let mut staged = self.stage_changes(&root)?;
        self.verify_existing()?;
        for file in &mut staged {
            file.replace()?;
        }
        Ok(())
    }

    fn stage_changes(&self, root: &Dir) -> Result<Vec<StagedFile>, ArtifactError> {
        let mut staged = Vec::new();
        for file in &self.files {
            if file.change() == Change::Unchanged {
                continue;
            }
            let parent = open_directories(root, file.path.parent().unwrap_or(Path::new("")), true)?
                .expect("created parent directories");
            staged.push(StagedFile::create(
                parent,
                file.path.file_name().expect("validated file name"),
                file.content(),
                file.permissions.clone(),
            )?);
        }
        Ok(staged)
    }

    fn verify_existing(&self) -> Result<(), ArtifactError> {
        let root = self.root.directory(false)?;
        for file in &self.files {
            let current = match &root {
                Some(root) => read_existing(root, &file.path)?.map(|(bytes, _)| bytes),
                None => None,
            };
            if current != file.existing {
                return Err(ArtifactError(format!(
                    "artifact {} changed since preflight",
                    file.path.display()
                )));
            }
        }
        Ok(())
    }
}

fn normalize_target(path: &Path) -> Result<PathBuf, ArtifactError> {
    let text = path
        .to_str()
        .ok_or_else(|| ArtifactError("artifact target must be UTF-8".into()))?;
    if text.contains(['\\', '\0', ':']) {
        return Err(ArtifactError(format!("invalid artifact target {text:?}")));
    }
    let mut normalized = PathBuf::new();
    for component in path.components() {
        match component {
            Component::Normal(name) => {
                let name_text = name.to_str().expect("validated UTF-8 target");
                let base = name_text.split('.').next().unwrap().to_ascii_uppercase();
                let numbered_device = base
                    .strip_prefix("COM")
                    .or_else(|| base.strip_prefix("LPT"))
                    .is_some_and(|suffix| {
                        matches!(
                            suffix,
                            "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "¹" | "²" | "³"
                        )
                    });
                if name_text.ends_with(['.', ' '])
                    || matches!(base.as_str(), "CON" | "PRN" | "AUX" | "NUL")
                    || numbered_device
                {
                    return Err(ArtifactError(format!(
                        "non-portable artifact target {text:?}"
                    )));
                }
                normalized.push(name);
            }
            Component::CurDir => {}
            _ => {
                return Err(ArtifactError(format!(
                    "artifact target {text:?} must be relative without parent traversal"
                )));
            }
        }
    }
    if normalized.as_os_str().is_empty() {
        return Err(ArtifactError("artifact target must name a file".into()));
    }
    Ok(normalized)
}

struct OutputRoot {
    path: PathBuf,
    anchor: Dir,
    missing: PathBuf,
}

impl OutputRoot {
    fn open(path: &Path) -> Result<Self, ArtifactError> {
        let path = std::path::absolute(path)?;
        let mut ancestor = path.clone();
        let mut missing = Vec::<OsString>::new();
        loop {
            match std::fs::symlink_metadata(&ancestor) {
                Ok(metadata) => {
                    if missing.is_empty() && metadata.is_symlink() {
                        return Err(ArtifactError("output root must not be a symlink".into()));
                    }
                    // Keep the root's final component relative to its parent so
                    // every later access checks it without following symlinks.
                    // Ancestors of the configured root may use trusted system
                    // aliases such as /tmp on macOS.
                    if missing.is_empty()
                        && let Some(name) = ancestor.file_name()
                    {
                        missing.push(name.to_os_string());
                        ancestor.pop();
                    }
                    let anchor = Dir::open_ambient_dir(&ancestor, ambient_authority())?;
                    return Ok(Self {
                        path,
                        anchor,
                        missing: missing.into_iter().rev().collect(),
                    });
                }
                Err(error) if error.kind() == io::ErrorKind::NotFound => {
                    missing.push(
                        ancestor
                            .file_name()
                            .ok_or_else(|| {
                                ArtifactError("output root has no existing ancestor".into())
                            })?
                            .to_os_string(),
                    );
                    ancestor.pop();
                }
                Err(error) => return Err(error.into()),
            }
        }
    }

    fn directory(&self, create: bool) -> Result<Option<Dir>, ArtifactError> {
        open_directories(&self.anchor, &self.missing, create)
    }
}

fn open_directories(root: &Dir, path: &Path, create: bool) -> Result<Option<Dir>, ArtifactError> {
    let mut directory = root.try_clone()?;
    for component in path.components() {
        let Component::Normal(name) = component else {
            return Err(ArtifactError("invalid directory component".into()));
        };
        match directory.symlink_metadata(name) {
            Ok(metadata) if metadata.is_symlink() || !metadata.is_dir() => {
                return Err(ArtifactError(format!(
                    "output directory {} must not be a symlink or file",
                    Path::new(name).display()
                )));
            }
            Ok(_) => {}
            Err(error) if error.kind() == io::ErrorKind::NotFound => {}
            Err(error) => return Err(error.into()),
        }
        match directory.open_dir_nofollow(name) {
            Ok(child) => directory = child,
            Err(error) if error.kind() == io::ErrorKind::NotFound && create => {
                match directory.create_dir(name) {
                    Ok(()) => {}
                    Err(error) if error.kind() == io::ErrorKind::AlreadyExists => {}
                    Err(error) => return Err(error.into()),
                }
                directory = directory.open_dir_nofollow(name)?;
            }
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
            Err(error) => return Err(error.into()),
        }
    }
    Ok(Some(directory))
}

fn read_existing(root: &Dir, path: &Path) -> Result<Option<(Vec<u8>, Permissions)>, ArtifactError> {
    let Some(parent) = open_directories(root, path.parent().unwrap_or(Path::new("")), false)?
    else {
        return Ok(None);
    };
    let name = path.file_name().expect("validated file name");
    let metadata = match parent.symlink_metadata(name) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(error) => return Err(error.into()),
    };
    if !metadata.is_file() || metadata.is_symlink() {
        return Err(ArtifactError(format!(
            "artifact target {} must be a regular file, not a symlink or directory",
            path.display()
        )));
    }
    let mut options = OpenOptions::new();
    options.read(true).follow(FollowSymlinks::No);
    let mut file = parent.open_with(name, &options)?;
    let metadata = file.metadata()?;
    if !metadata.is_file() {
        return Err(ArtifactError(format!(
            "artifact target {} is not a regular file",
            path.display()
        )));
    }
    let mut content = Vec::new();
    file.read_to_end(&mut content)?;
    Ok(Some((content, metadata.permissions())))
}

struct StagedFile {
    parent: Dir,
    temporary: Option<OsString>,
    destination: OsString,
}

impl StagedFile {
    fn create(
        parent: Dir,
        destination: &OsStr,
        content: &[u8],
        permissions: Option<Permissions>,
    ) -> Result<Self, ArtifactError> {
        static NEXT_FILE: AtomicU64 = AtomicU64::new(0);
        let mut options = OpenOptions::new();
        options
            .write(true)
            .create_new(true)
            .follow(FollowSymlinks::No);
        let (mut file, temporary) = loop {
            let number = NEXT_FILE.fetch_add(1, Ordering::Relaxed);
            let name = OsString::from(format!(".suspect-{}-{number}.tmp", std::process::id()));
            match parent.open_with(&name, &options) {
                Ok(file) => break (file, name),
                Err(error) if error.kind() == io::ErrorKind::AlreadyExists => continue,
                Err(error) => return Err(error.into()),
            }
        };
        let staged = Self {
            parent,
            temporary: Some(temporary),
            destination: destination.to_os_string(),
        };
        let result = (|| {
            file.write_all(content)?;
            if let Some(permissions) = permissions {
                file.set_permissions(permissions)?;
            }
            file.sync_all()
        })();
        drop(file);
        result?;
        Ok(staged)
    }

    fn replace(&mut self) -> Result<(), ArtifactError> {
        self.parent.rename(
            self.temporary.as_ref().expect("staged file exists"),
            &self.parent,
            &self.destination,
        )?;
        self.temporary = None;
        Ok(())
    }
}

impl Drop for StagedFile {
    fn drop(&mut self) {
        if let Some(temporary) = &self.temporary {
            let _ = self.parent.remove_file(temporary);
        }
    }
}
