//! Versioned ownership over the existing confined artifact batch.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};

use super::*;

/// Root-local versioned ownership registry. This path is reserved in owned batches.
pub const OWNERSHIP_MANIFEST: &str = ".suspect-artifacts.json";
const FORMAT: &str = "suspect-artifacts";
const VERSION: u32 = 1;

/// Explicit policy for preexisting outputs that have no ownership record.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum Adoption {
    /// Preserve all unowned files, even when their bytes equal generated output.
    #[default]
    Refuse,
    /// Deliberately migrate only files byte-identical to the complete planned output.
    /// Once adopted, unedited obsolete files become eligible for deletion.
    Identical,
}

/// Ownership-aware drift for an output path.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OwnershipChangeKind {
    /// An intended output is missing.
    Created,
    /// An unedited owned output needs new generated bytes.
    Changed,
    /// Existing output matches the intended bytes.
    Unchanged,
    /// An unedited, fully owned output is no longer generated and can be removed.
    Obsolete,
    /// An obsolete ownership entry's file is already absent.
    MissingObsolete,
    /// User edits, retained user content, or another owner prevent the operation.
    Conflict,
}

/// One path's drift and any reason that prevents mutation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipChange {
    /// Output-root-relative path.
    pub path: PathBuf,
    /// Ownership-aware action or conflict.
    pub kind: OwnershipChangeKind,
    /// Human-readable conflict explanation, otherwise absent.
    pub conflict: Option<String>,
}

/// Read-only check result, including ownership metadata drift.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipReport {
    /// Intended and obsolete paths, in stable path order.
    pub changes: Vec<OwnershipChange>,
    /// Whether the versioned manifest is missing, stale, or unchanged.
    pub manifest: Change,
}

impl OwnershipReport {
    /// True only when owned outputs and their ownership metadata are current.
    #[must_use]
    pub fn is_current(&self) -> bool {
        self.manifest == Change::Unchanged
            && self
                .changes
                .iter()
                .all(|change| change.kind == OwnershipChangeKind::Unchanged)
    }

    /// Conflicts that must be resolved before any output can be changed.
    pub fn conflicts(&self) -> impl Iterator<Item = &OwnershipChange> {
        self.changes
            .iter()
            .filter(|change| change.kind == OwnershipChangeKind::Conflict)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Fingerprint {
    sha256: String,
    bytes: u64,
}

impl Fingerprint {
    fn of(bytes: &[u8]) -> Self {
        Self {
            sha256: format!("{:x}", Sha256::digest(bytes)),
            bytes: bytes.len() as u64,
        }
    }
    fn matches(&self, bytes: &[u8]) -> bool {
        self.bytes == bytes.len() as u64 && self.sha256 == format!("{:x}", Sha256::digest(bytes))
    }
    fn validate(&self) -> Result<(), ArtifactError> {
        if self.sha256.len() != 64
            || !self
                .sha256
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(ArtifactError(
                "ownership manifest contains an invalid SHA-256 digest".into(),
            ));
        }
        Ok(())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct ManagedRecord {
    policy: String,
    fingerprint: Fingerprint,
}

pub(super) struct ManagedContent {
    existing: Fingerprint,
    planned: ManagedRecord,
    retained_user_content: bool,
}

impl PlannedArtifact<'_> {
    /// Supply a versioned comparison of generator-owned regions after preserving
    /// user sections. The caller must normalize only its documented editable
    /// regions, using the same policy for the existing and planned bytes.
    ///
    /// This can authorize updates outside preserved regions. It never replaces
    /// the full-byte fingerprint used for deletion. `retained_user_content`
    /// protects the resulting file from obsolete deletion even when unchanged.
    /// Passing `false` does not clear protection already recorded for this owner.
    pub fn set_managed_content(
        &mut self,
        policy: &str,
        existing: &[u8],
        planned: &[u8],
        retained_user_content: bool,
    ) {
        self.managed = Some(ManagedContent {
            existing: Fingerprint::of(existing),
            planned: ManagedRecord {
                policy: policy.into(),
                fingerprint: Fingerprint::of(planned),
            },
            retained_user_content,
        });
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct FileRecord {
    path: String,
    fingerprint: Fingerprint,
    #[serde(skip_serializing_if = "Option::is_none")]
    managed: Option<ManagedRecord>,
    retained_user_content: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Owner {
    id: String,
    files: Vec<FileRecord>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Registry {
    format: String,
    version: u32,
    owners: Vec<Owner>,
}

impl Default for Registry {
    fn default() -> Self {
        Self {
            format: FORMAT.into(),
            version: VERSION,
            owners: Vec::new(),
        }
    }
}

struct Obsolete {
    path: PathBuf,
    existing: Option<Vec<u8>>,
    remove: bool,
}

/// Ownership preflight and manifest publication around a confined artifact batch.
/// The owner is a stable logical identity; callers should not serialize absolute
/// checkout paths as identities. Each owner supplies its complete desired file set.
pub struct OwnedBatch<'a> {
    batch: ArtifactBatch<'a>,
    manifest: PlannedArtifact<'static>,
    obsolete: Vec<Obsolete>,
    report: OwnershipReport,
}

impl<'a> ArtifactBatch<'a> {
    /// Add versioned ownership checks after all content transformations are done.
    /// Missing registries do not prove ownership. Unsupported/malformed versions
    /// block mutations rather than being overwritten or implicitly migrated.
    ///
    /// # Errors
    /// Invalid owner identities, unsafe/colliding registry paths, corrupt metadata,
    /// symlinks and filesystem failures. Edited/unowned files are reported as
    /// conflicts, allowing read-only previews; commit rejects the entire plan.
    pub fn with_ownership(
        self,
        owner: &str,
        adoption: Adoption,
    ) -> Result<OwnedBatch<'a>, ArtifactError> {
        validate_identity(owner)?;
        let directory = self.root.directory(false)?;
        let old_manifest = match &directory {
            Some(root) => read_existing(root, Path::new(OWNERSHIP_MANIFEST))?,
            None => None,
        };
        let mut registry = match &old_manifest {
            Some((bytes, _)) => parse_registry(bytes)?,
            None => Registry::default(),
        };
        let registered = registry
            .owners
            .iter()
            .flat_map(|owner| {
                owner
                    .files
                    .iter()
                    .map(move |file| (file.path.as_str(), (owner.id.as_str(), file)))
            })
            .collect::<BTreeMap<_, _>>();
        validate_plan_paths(&self.files, &registered)?;
        let mut changes = Vec::new();
        let mut next_files = Vec::new();
        let current_paths: BTreeSet<_> = self.files.iter().map(|file| file.path.clone()).collect();
        for file in &self.files {
            let path = file.path.to_str().expect("validated UTF-8 path");
            let previous = registered.get(path);
            let conflict=match previous {
                Some((previous_owner,_)) if *previous_owner != owner => Some(format!("owned by `{previous_owner}`; owner `{owner}` cannot overwrite or adopt it")),
                Some((_,record)) => match file.existing() {
                    None => None,
                    Some(existing) if record.fingerprint.matches(existing) || existing == file.content() => None,
                    Some(_) if record.managed.as_ref().zip(file.managed.as_ref()).is_some_and(|(old,new)| old.policy == new.planned.policy && old.fingerprint == new.existing) => None,
                    Some(_) => Some("owned output was edited after its recorded generation; preserving user changes".into()),
                },
                None if file.existing().is_none() => None,
                None if adoption == Adoption::Identical && file.existing() == Some(file.content()) => None,
                None => Some("unowned file occupies the output path; explicit byte-identical adoption is required".into()),
            };
            let kind = if conflict.is_some() {
                OwnershipChangeKind::Conflict
            } else {
                match file.change() {
                    Change::Created => OwnershipChangeKind::Created,
                    Change::Changed => OwnershipChangeKind::Changed,
                    Change::Unchanged => OwnershipChangeKind::Unchanged,
                }
            };
            changes.push(OwnershipChange {
                path: file.path.clone(),
                kind,
                conflict,
            });
            if let Some(managed) = &file.managed {
                validate_identity(&managed.planned.policy)?;
            }
            next_files.push(FileRecord {
                path: path.into(),
                fingerprint: Fingerprint::of(file.content()),
                managed: file.managed.as_ref().map(|managed| managed.planned.clone()),
                // A later template may make retained user code a default, or
                // the same owner may use a frontend without region metadata.
                // Neither transition releases the previously recorded user
                // content: only retiring the record after deliberate removal
                // can do so.
                retained_user_content: previous.is_some_and(|(previous_owner, record)| {
                    *previous_owner == owner && record.retained_user_content
                }) || file
                    .managed
                    .as_ref()
                    .is_some_and(|managed| managed.retained_user_content),
            });
        }
        let mut obsolete = Vec::new();
        if let Some(previous) = registry.owners.iter().find(|entry| entry.id == owner) {
            for record in &previous.files {
                let path = PathBuf::from(&record.path);
                if current_paths.contains(&path) {
                    continue;
                }
                let existing = match &directory {
                    Some(root) => read_existing(root, &path)?.map(|(bytes, _)| bytes),
                    None => None,
                };
                let conflict = match existing.as_deref() {
                    None => None,
                    Some(_) if record.retained_user_content => Some(
                        "obsolete output contains retained user content; it will not be removed"
                            .into(),
                    ),
                    Some(bytes) if record.fingerprint.matches(bytes) => None,
                    Some(_) => {
                        Some("obsolete owned output was edited; it will not be removed".into())
                    }
                };
                let remove = existing.is_some() && conflict.is_none();
                changes.push(OwnershipChange {
                    path: path.clone(),
                    kind: if conflict.is_some() {
                        OwnershipChangeKind::Conflict
                    } else if remove {
                        OwnershipChangeKind::Obsolete
                    } else {
                        OwnershipChangeKind::MissingObsolete
                    },
                    conflict,
                });
                obsolete.push(Obsolete {
                    path,
                    existing,
                    remove,
                });
            }
        }
        next_files.sort_by(|a, b| a.path.cmp(&b.path));
        registry.owners.retain(|entry| entry.id != owner);
        registry.owners.push(Owner {
            id: owner.into(),
            files: next_files,
        });
        registry.owners.sort_by(|a, b| a.id.cmp(&b.id));
        let mut bytes = serde_json::to_vec_pretty(&registry)
            .map_err(|error| ArtifactError(error.to_string()))?;
        bytes.push(b'\n');
        let (existing, permissions) = old_manifest.map_or((None, None), |(bytes, permissions)| {
            (Some(bytes), Some(permissions))
        });
        let manifest = PlannedArtifact {
            path: OWNERSHIP_MANIFEST.into(),
            content: Cow::Owned(bytes),
            existing,
            permissions,
            managed: None,
        };
        changes.sort_by(|a, b| a.path.cmp(&b.path));
        let report = OwnershipReport {
            changes,
            manifest: manifest.change(),
        };
        Ok(OwnedBatch {
            batch: self,
            manifest,
            obsolete,
            report,
        })
    }
}

impl<'a> OwnedBatch<'a> {
    /// Generated artifacts with final preservation-aware content.
    #[must_use]
    pub fn files(&self) -> &[PlannedArtifact<'a>] {
        self.batch.files()
    }
    /// The planned ownership metadata, including its existing-byte snapshot.
    #[must_use]
    pub fn manifest(&self) -> &PlannedArtifact<'static> {
        &self.manifest
    }
    /// Read-only drift and conflict report.
    #[must_use]
    pub fn report(&self) -> &OwnershipReport {
        &self.report
    }
    /// Existing obsolete output for previewing its proposed removal.
    #[must_use]
    pub fn obsolete_content(&self, path: &Path) -> Option<&[u8]> {
        self.obsolete
            .iter()
            .find(|file| file.path == path)
            .and_then(|file| file.existing.as_deref())
    }

    /// Stage all changed output and the new manifest, replace generated files,
    /// remove only rechecked full-byte-identical obsolete files, and publish the
    /// manifest last. Unchanged data and metadata retain inode and mtime.
    ///
    /// There is no whole-batch transaction, filesystem lock, or compare-and-swap
    /// deletion. Rechecks are best effort against concurrent edits. Interruption
    /// can leave partial output with stale metadata; recorded files matching the
    /// next intended output can be reconciled, while unrecorded new files require
    /// explicit byte-identical adoption. No directory or arbitrary temp cleanup occurs.
    ///
    /// # Errors
    /// Any preflight conflict, changed snapshot, unsafe path, staging/replacement
    /// failure or deletion failure. Earlier per-file replacements may have completed.
    pub fn commit(self) -> Result<(), ArtifactError> {
        let conflicts: Vec<_> = self
            .report
            .conflicts()
            .map(|change| {
                format!(
                    "{}: {}",
                    change.path.display(),
                    change.conflict.as_deref().unwrap_or("ownership conflict")
                )
            })
            .collect();
        if !conflicts.is_empty() {
            return Err(ArtifactError(format!(
                "ownership conflicts:\n{}",
                conflicts.join("\n")
            )));
        }
        self.verify()?;
        if self.report.is_current() {
            return Ok(());
        }
        let root = self
            .batch
            .root
            .directory(true)?
            .expect("created output root");
        let mut staged = self.batch.stage_changes(&root)?;
        let mut manifest = if self.manifest.change() != Change::Unchanged {
            Some(StagedFile::create(
                root.try_clone()?,
                OsStr::new(OWNERSHIP_MANIFEST),
                self.manifest.content(),
                self.manifest.permissions.clone(),
            )?)
        } else {
            None
        };
        self.verify()?;
        for file in &mut staged {
            file.replace()?;
        }
        for obsolete in &self.obsolete {
            if !obsolete.remove {
                continue;
            }
            verify_snapshot(&root, &obsolete.path, obsolete.existing.as_deref())?;
            let parent = open_directories(
                &root,
                obsolete.path.parent().unwrap_or(Path::new("")),
                false,
            )?
            .ok_or_else(|| ArtifactError("obsolete output parent disappeared".into()))?;
            parent.remove_file(obsolete.path.file_name().expect("validated obsolete path"))?;
        }
        // A concurrent owner update must not be knowingly overwritten after
        // output publication. This remains a recheck, not an atomic CAS.
        verify_snapshot(
            &root,
            Path::new(OWNERSHIP_MANIFEST),
            self.manifest.existing(),
        )?;
        if let Some(manifest) = &mut manifest {
            manifest.replace()?;
        }
        Ok(())
    }

    fn verify(&self) -> Result<(), ArtifactError> {
        self.batch.verify_existing()?;
        if let Some(root) = self.batch.root.directory(false)? {
            verify_snapshot(
                &root,
                Path::new(OWNERSHIP_MANIFEST),
                self.manifest.existing(),
            )?;
            for obsolete in &self.obsolete {
                verify_snapshot(&root, &obsolete.path, obsolete.existing.as_deref())?;
            }
        } else if self.manifest.existing().is_some()
            || self.obsolete.iter().any(|file| file.existing.is_some())
        {
            return Err(ArtifactError(
                "ownership output root disappeared since preflight".into(),
            ));
        }
        Ok(())
    }
}

fn verify_snapshot(root: &Dir, path: &Path, expected: Option<&[u8]>) -> Result<(), ArtifactError> {
    if read_existing(root, path)?
        .as_ref()
        .map(|(bytes, _)| bytes.as_slice())
        != expected
    {
        return Err(ArtifactError(format!(
            "artifact {} changed since ownership preflight",
            path.display()
        )));
    }
    Ok(())
}

fn validate_identity(identity: &str) -> Result<(), ArtifactError> {
    if identity.is_empty()
        || identity.len() > 256
        || identity.trim() != identity
        || identity.chars().any(char::is_control)
    {
        return Err(ArtifactError("ownership identity must be a nonempty stable logical name without control characters (maximum 256 bytes)".into()));
    }
    Ok(())
}

fn parse_registry(bytes: &[u8]) -> Result<Registry, ArtifactError> {
    let raw: serde_json::Value = serde_json::from_slice(bytes)
        .map_err(|error| ArtifactError(format!("malformed ownership manifest: {error}")))?;
    if raw.get("format").and_then(serde_json::Value::as_str) != Some(FORMAT)
        || raw.get("version").and_then(serde_json::Value::as_u64) != Some(u64::from(VERSION))
    {
        return Err(ArtifactError(
            "unsupported ownership manifest format/version; no implicit migration is performed"
                .into(),
        ));
    }
    let registry: Registry = serde_json::from_slice(bytes)
        .map_err(|error| ArtifactError(format!("malformed ownership manifest: {error}")))?;
    let mut owners = BTreeSet::new();
    let mut paths = BTreeMap::new();
    for owner in &registry.owners {
        validate_identity(&owner.id)?;
        if !owners.insert(&owner.id) {
            return Err(ArtifactError(
                "duplicate owner in ownership manifest".into(),
            ));
        }
        for record in &owner.files {
            let path = normalize_target(Path::new(&record.path))?;
            if path.to_str() != Some(&record.path) {
                return Err(ArtifactError(
                    "ownership manifest paths must already be normalized".into(),
                ));
            }
            check_reserved(&path)?;
            record.fingerprint.validate()?;
            if let Some(managed) = &record.managed {
                validate_identity(&managed.policy)?;
                managed.fingerprint.validate()?;
            }
            if paths.insert(fold(&path), path).is_some() {
                return Err(ArtifactError(
                    "duplicate or case/Unicode-colliding path in ownership manifest".into(),
                ));
            }
        }
    }
    check_ancestors(paths.keys())?;
    Ok(registry)
}

fn validate_plan_paths(
    files: &[PlannedArtifact<'_>],
    registered: &BTreeMap<&str, (&str, &FileRecord)>,
) -> Result<(), ArtifactError> {
    let mut paths: BTreeMap<PathBuf, PathBuf> = registered
        .keys()
        .map(|path| (fold(Path::new(path)), PathBuf::from(path)))
        .collect();
    for file in files {
        check_reserved(&file.path)?;
        let key = fold(&file.path);
        if paths
            .get(&key)
            .is_some_and(|previous| previous != &file.path)
        {
            return Err(ArtifactError(format!(
                "artifact {} collides with a recorded ownership path",
                file.path.display()
            )));
        }
        paths.insert(key, file.path.clone());
    }
    check_ancestors(paths.keys())
}

fn check_reserved(path: &Path) -> Result<(), ArtifactError> {
    let folded = fold(path);
    let reserved = fold(Path::new(OWNERSHIP_MANIFEST));
    if folded == reserved || folded.starts_with(&reserved) {
        return Err(ArtifactError(format!(
            "artifact {} collides with the reserved ownership manifest",
            path.display()
        )));
    }
    Ok(())
}

fn fold(path: &Path) -> PathBuf {
    PathBuf::from(
        path.to_string_lossy()
            .to_lowercase()
            .to_uppercase()
            .nfc()
            .collect::<String>(),
    )
}
fn check_ancestors<'a>(paths: impl Iterator<Item = &'a PathBuf>) -> Result<(), ArtifactError> {
    let paths: BTreeSet<PathBuf> = paths.cloned().collect();
    for path in &paths {
        for ancestor in path.ancestors().skip(1) {
            if paths.contains(ancestor) {
                return Err(ArtifactError(format!(
                    "ownership path {} has a file/directory collision",
                    path.display()
                )));
            }
        }
    }
    Ok(())
}
