"""Exact bounded JSON runtime for generated Python packages.

Generated by suspect-codegen. Do not edit.

Representation-only: schema validation, model conversion and HTTP clients
are separate layers. Standard library only, Python 3.11 syntax profile.

- Numbers keep their exact source spelling; no float/Decimal/str(float) path.
- Rejects malformed JSON/UTF-8, duplicate decoded keys, NaN/Infinity,
  trailing content, and lone surrogates (scalars-only policy, matching the
  Rust runtime; escaped surrogate pairs decode to one scalar).
- Limits bound input bytes, output bytes, depth (ceiling 256), and abstract
  work units per call. Global interpreter state is never mutated.
"""

from __future__ import annotations

import re

__all__ = [
    "JsonError", "JsonLimits", "JsonNumber", "JsonValue", "parse_json",
    "stringify_json", "SYNTAX", "INVALID_UTF8", "DUPLICATE_KEY",
    "RESOURCE_LIMIT", "NOT_INTEGER", "UNSUPPORTED_VALUE", "CYCLE",
]

from collections.abc import Callable
from typing import NoReturn, TypeAlias, Union, cast, TYPE_CHECKING, ForwardRef

# Stable machine-readable error kinds.
SYNTAX = "syntax"
INVALID_UTF8 = "invalid_utf8"
DUPLICATE_KEY = "duplicate_key"
RESOURCE_LIMIT = "resource_limit"
NOT_INTEGER = "not_integer"
UNSUPPORTED_VALUE = "unsupported_value"
CYCLE = "cycle"

# Recursive descent stays simple and auditable, but the configured schema
# limit can never approach the interpreter recursion limit, so no global
# recursion setting is touched.
_HARD_DEPTH_CEILING = 256

_DIGITS = frozenset("0123456789")
_WHITESPACE = frozenset(" \t\n\r")
_RAW_CONTROL = re.compile(r"[\x00-\x1f]")
_STRING_DELIMITER = re.compile(r'["\\]')
_ESCAPE_TO_CHAR = {'"': '"', "\\": "\\", "/": "/", "b": "\b", "f": "\f",
                   "n": "\n", "r": "\r", "t": "\t"}
_CHAR_TO_ESCAPE = {'"': '\\"', "\\": "\\\\", "\b": "\\b", "\f": "\\f",
                   "\n": "\\n", "\r": "\\r", "\t": "\\t"}


class JsonLimits:
    """Resource limits for one call; ``max_depth`` is capped by the 256 ceiling."""

    __slots__ = ("max_input_bytes", "max_output_bytes", "max_depth", "max_work")

    def __init__(
        self,
        max_input_bytes: int = 8 * 1024 * 1024,
        max_output_bytes: int = 8 * 1024 * 1024,
        max_depth: int = 128,
        max_work: int = 32 * 1024 * 1024,
    ) -> None:
        for name, value in (
            ("max_input_bytes", max_input_bytes),
            ("max_output_bytes", max_output_bytes),
            ("max_depth", max_depth),
            ("max_work", max_work),
        ):
            if type(value) is not int or value < 0:
                raise ValueError(f"limit {name} must be a non-negative int")
        self.max_input_bytes = max_input_bytes
        self.max_output_bytes = max_output_bytes
        self.max_depth = max_depth
        self.max_work = max_work

    def __repr__(self) -> str:
        return (
            f"JsonLimits({self.max_input_bytes}, {self.max_output_bytes},"
            f" {self.max_depth}, {self.max_work})"
        )


class JsonError(Exception):
    """Bounded JSON failure: stable ``kind``, ``offset`` (bytes input) or
    character offset (str input; ``None`` for whole-operation failures), and
    a JSONPath-like ``path`` such as ``$.a[2].b`` for structural failures.
    Messages never embed the input document."""

    __slots__ = ("kind", "message", "offset", "path")

    def __init__(
        self,
        kind: str,
        message: str,
        offset: int | None = None,
        path: str | None = None,
    ) -> None:
        super().__init__(message)
        self.kind = kind
        self.message = message
        self.offset = offset
        self.path = path

    def __str__(self) -> str:
        location = ""
        if self.path is not None:
            location += f" at path {_diagnostic_text(self.path)}"
        if self.offset is not None:
            location += f" at offset {self.offset}"
        return f"json {self.kind}: {_diagnostic_text(self.message)}{location}"


def _diagnostic_text(text: str, limit: int = 256) -> str:
    pieces: list[str] = []
    width = 0
    for char in text:
        code = ord(char)
        escaped = f"\\u{code:04x}" if code < 32 or 127 <= code <= 159 or code in (0x2028, 0x2029) else char
        if width + len(escaped) > limit:
            pieces.append("...")
            break
        pieces.append(escaped)
        width += len(escaped)
    return "".join(pieces)


def _digits_to_int(text: str, start: int, end: int, spend: Callable[[int], None] | None = None) -> int:
    """Exact chunked decimal conversion; chunks stay below any global int
    digit-limit threshold and no float is involved."""
    value = 0
    at = start
    while at < end:
        chunk = text[at : min(at + 9, end)]
        value = value * 10 ** len(chunk) + int(chunk)
        at += len(chunk)
        if spend is not None:
            spend(len(chunk))
    return value


def _render_path(parts: list[str | int]) -> str | None:
    if not parts:
        return None
    rendered = "$"
    for part in parts:
        if type(part) is int:
            rendered += f"[{part}]"
        else:
            escaped = "".join(
                _CHAR_TO_ESCAPE.get(char, f"\\u{ord(char):04x}" if ord(char) < 32 or 127 <= ord(char) <= 159 or ord(char) in (0x2028, 0x2029) else char)
                for char in cast(str, part)
            )
            rendered += f'["{escaped}"]'
    return rendered


def _scan_number(text: str, start: int, spend: Callable[[int], None] | None = None) -> tuple[int, bool, str, int]:
    """Validate JSON number grammar (RFC 8259) at ``start``.

    Returns ``(end, negative, digits, exponent)``: ``digits`` is the mantissa
    digit string without sign or point (leading zeros stripped), ``exponent``
    the decimal scale applied to it. NaN/Infinity/hex fail here. Exponents
    with more than 40 digits are stored as the signed lower bound ``10**39``:
    every decision (``is_integer``, ``to_int`` budgets) compares the exponent
    against input-bounded lengths or ``max_digits``, which this bound
    dominates, and an exact value could never fit a succeeding budget.
    """
    length = len(text)
    at = start
    negative = False
    if at < length and text[at] == "-":
        negative = True
        at += 1
    if at >= length:
        raise JsonError(SYNTAX, "invalid JSON number", start)
    first = text[at]
    if first == "0":
        at += 1
    elif first in _DIGITS:
        at += 1
        while at < length and text[at] in _DIGITS:
            at += 1
    else:
        raise JsonError(SYNTAX, "invalid JSON number", start)
    mantissa_start = start + (1 if negative else 0)
    fraction_length = 0
    if at < length and text[at] == ".":
        at += 1
        fraction_start = at
        while at < length and text[at] in _DIGITS:
            at += 1
        if at == fraction_start:
            raise JsonError(SYNTAX, "invalid JSON number fraction", start)
        fraction_length = at - fraction_start
    mantissa = text[mantissa_start:at]
    exponent = 0
    if at < length and text[at] in "eE":
        at += 1
        exponent_negative = False
        if at < length and text[at] in "+-":
            exponent_negative = text[at] == "-"
            at += 1
        exponent_start = at
        while at < length and text[at] in _DIGITS:
            at += 1
        if at == exponent_start:
            raise JsonError(SYNTAX, "invalid JSON number exponent", start)
        significant_start = exponent_start
        while significant_start < at and text[significant_start] == "0":
            significant_start += 1
        if at - significant_start > 40:
            magnitude = 10**39
        else:
            magnitude = _digits_to_int(text, significant_start, at, spend)
        exponent = -magnitude if exponent_negative else magnitude
    digits = mantissa.replace(".", "").lstrip("0")
    if not digits:
        digits = "0"
    exponent -= fraction_length
    if spend is not None:
        spend(at - start)
    return at, negative, digits, exponent


class JsonNumber:
    """Immutable, validated exact JSON number token preserving its source
    spelling; no float/Decimal path. ``is_integer`` is symbolic (no
    exponent-sized allocation); ``to_int`` is a bounded exact conversion."""

    __slots__ = ("_token", "_negative", "_digits", "_exponent")

    def __init__(self, token: str) -> None:
        if type(token) is not str:
            raise TypeError("number token must be str")
        end, negative, digits, exponent = _scan_number(token, 0)
        if end != len(token):
            raise JsonError(SYNTAX, "trailing characters after JSON number token", end)
        self._token = token
        self._negative = negative
        self._digits = digits
        self._exponent = exponent

    @classmethod
    def parse(cls, token: str) -> "JsonNumber":
        """Validated constructor alias: ``JsonNumber.parse("1.25e3")``."""
        return cls(token)

    @property
    def token(self) -> str:
        """The exact source spelling of this number."""
        return self._token

    def _trailing_zeros(self) -> int:
        count = 0
        for char in reversed(self._digits):
            if char != "0":
                break
            count += 1
        return count

    def is_integer(self) -> bool:
        """True when the exact value is integral; works on ``1e999999999``
        and ``0.0`` alike without materializing either value."""
        if self._digits == "0":
            return True
        exponent = self._exponent
        if exponent >= 0:
            return True
        needed = -exponent
        if needed > len(self._digits):
            return False
        return self._trailing_zeros() >= needed

    def to_int(self, max_digits: int = 4096) -> int:
        """Bounded exact integer conversion; never calls str(float). Raises
        ``NOT_INTEGER`` for non-integral values and ``RESOURCE_LIMIT`` past
        ``max_digits`` (capped at 10**9 so the oversized-exponent bound in
        ``_scan_number`` always dominates every budget comparison)."""
        if type(max_digits) is not int or not 1 <= max_digits <= 10**9:
            raise ValueError("max_digits must be an int between 1 and 10**9")
        digits = self._digits
        if digits == "0":
            return 0
        exponent = self._exponent
        if exponent < 0:
            if self._trailing_zeros() >= -exponent:
                digits = digits[: len(digits) + exponent]
                exponent = 0
            else:
                raise JsonError(NOT_INTEGER, "JSON number is not an exact integer")
        total = len(digits) + exponent
        if total > max_digits:
            raise JsonError(RESOURCE_LIMIT, "exact integer conversion exceeds max_digits")
        rendered = _digits_to_int(digits + "0" * exponent, 0, total)
        return -rendered if self._negative else rendered

    def __eq__(self, other: object) -> bool:
        if type(other) is JsonNumber:
            return self._token == other._token
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._token)

    def __repr__(self) -> str:
        return f"JsonNumber({self._token!r})"


_HEX_VALUES = {char: int(char, 16) for char in "0123456789abcdefABCDEF"}


class _Parser:
    """Recursive descent over validated UTF-8 text. Depth is explicit and
    ceiling-bounded; no global recursion limit is read or changed."""

    __slots__ = ("_text", "_at", "_work", "_limits", "_path")

    def __init__(self, text: str, limits: JsonLimits) -> None:
        self._text = text
        self._at = 0
        self._work = limits.max_work
        self._limits = limits
        self._path: list[str | int] = []

    def _spend(self, amount: int) -> None:
        self._work -= amount
        if self._work < 0:
            raise JsonError(RESOURCE_LIMIT, "JSON work limit exceeded", self._at)

    def _fail(self, kind: str, message: str, offset: int | None = None) -> NoReturn:
        raise JsonError(kind, message, self._at if offset is None else offset, self._path_text())

    def _path_text(self) -> str | None:
        return _render_path(self._path)

    def parse(self) -> JsonValue:
        self._skip_ws()
        value = self._value(0)
        self._skip_ws()
        if self._at != len(self._text):
            self._fail(SYNTAX, "unexpected trailing JSON input")
        return value

    def _skip_ws(self) -> None:
        text = self._text
        at = self._at
        length = len(text)
        while at < length and text[at] in _WHITESPACE:
            at += 1
        if at != self._at:
            self._spend(at - self._at)
            self._at = at

    def _literal(self, word: str) -> None:
        if self._text.startswith(word, self._at):
            self._spend(len(word))
            self._at += len(word)
        else:
            self._fail(SYNTAX, "invalid JSON literal")

    def _enter(self, depth: int) -> int:
        next_depth = depth + 1
        if next_depth > self._limits.max_depth:
            self._fail(RESOURCE_LIMIT, "JSON nesting limit exceeded")
        return next_depth

    def _value(self, depth: int) -> JsonValue:
        self._spend(1)
        text = self._text
        if self._at >= len(text):
            self._fail(SYNTAX, "expected a JSON value")
        char = text[self._at]
        if char == "n":
            self._literal("null")
            return None
        if char == "t":
            self._literal("true")
            return True
        if char == "f":
            self._literal("false")
            return False
        if char == '"':
            return self._string()
        if char == "[":
            return self._array(depth)
        if char == "{":
            return self._object(depth)
        if char == "-" or char in _DIGITS:
            return self._number()
        self._fail(SYNTAX, "expected a JSON value")

    def _array(self, depth: int) -> list[JsonValue]:
        next_depth = self._enter(depth)
        self._at += 1
        text = self._text
        values: list[JsonValue] = []
        self._skip_ws()
        if self._at < len(text) and text[self._at] == "]":
            self._at += 1
            return values
        self._path.append(0)
        index = 0
        try:
            while True:
                self._path[-1] = index
                values.append(self._value(next_depth))
                index += 1
                self._skip_ws()
                if self._at >= len(text):
                    self._fail(SYNTAX, "expected comma or end of JSON array")
                char = text[self._at]
                if char == ",":
                    self._at += 1
                    self._skip_ws()
                elif char == "]":
                    self._at += 1
                    return values
                else:
                    self._fail(SYNTAX, "expected comma or end of JSON array")
        finally:
            self._path.pop()

    def _object(self, depth: int) -> dict[str, JsonValue]:
        next_depth = self._enter(depth)
        self._at += 1
        text = self._text
        values: dict[str, JsonValue] = {}
        self._skip_ws()
        if self._at < len(text) and text[self._at] == "}":
            self._at += 1
            return values
        while True:
            if self._at >= len(text) or text[self._at] != '"':
                self._fail(SYNTAX, "expected JSON object key")
            key = self._string()
            self._skip_ws()
            if self._at >= len(text) or text[self._at] != ":":
                self._fail(SYNTAX, "expected colon after JSON property name")
            self._at += 1
            self._skip_ws()
            self._path.append(key)
            try:
                if key in values:
                    self._fail(DUPLICATE_KEY, "duplicate decoded JSON object key")
                values[key] = self._value(next_depth)
            finally:
                self._path.pop()
            self._skip_ws()
            if self._at >= len(text):
                self._fail(SYNTAX, "expected comma or end of JSON object")
            char = text[self._at]
            if char == ",":
                self._at += 1
                self._skip_ws()
            elif char == "}":
                self._at += 1
                return values
            else:
                self._fail(SYNTAX, "expected comma or end of JSON object")

    def _number(self) -> JsonNumber:
        start = self._at
        end = _scan_number(self._text, start, self._spend)[0]
        self._at = end
        return JsonNumber(self._text[start:end])

    def _string(self) -> str:
        text = self._text
        length = len(text)
        at = self._at + 1
        pieces = []
        while True:
            # One bounded search stops at the first delimiter. Independent
            # quote/backslash searches would rescan every following short string.
            end = min(length, at + self._work + 1)
            delimiter = _STRING_DELIMITER.search(text, at, end)
            stop = delimiter.start() if delimiter is not None else end
            self._spend(stop - at)
            run = text[at:stop]
            if run:
                self._check_run(run, at)
                pieces.append(run)
            at = stop
            if at >= length:
                self._fail(SYNTAX, "unterminated JSON string")
            self._spend(1)
            if text[at] == '"':
                self._at = at + 1
                return "".join(pieces)
            at = self._escape(pieces, at + 1)

    def _check_run(self, run: str, at: int) -> None:
        control = _RAW_CONTROL.search(run)
        if control is not None:
            self._fail(
                SYNTAX,
                "unescaped control character in JSON string",
                offset=at + control.start(),
            )
        if run.isascii():
            return
        try:
            run.encode("utf-8", "strict")
        except UnicodeEncodeError as error:
            self._fail(
                SYNTAX,
                "lone surrogate character in JSON string input",
                offset=at + error.start,
            )

    def _escape(self, pieces: list[str], at: int) -> int:
        text = self._text
        if at >= len(text):
            self._fail(SYNTAX, "incomplete JSON string escape")
        char = _ESCAPE_TO_CHAR.get(text[at])
        if char is not None:
            pieces.append(char)
            return at + 1
        if text[at] != "u":
            self._fail(SYNTAX, "invalid JSON string escape")
        first, at = self._hex4(at + 1)
        if 0xD800 <= first <= 0xDBFF:
            if text[at : at + 2] != "\\u":
                self._fail(SYNTAX, "unpaired high surrogate in JSON string")
            self._spend(2)
            second, at = self._hex4(at + 2)
            if not 0xDC00 <= second <= 0xDFFF:
                self._fail(SYNTAX, "invalid UTF-16 surrogate pair in JSON string")
            scalar = 0x10000 + ((first - 0xD800) << 10) + (second - 0xDC00)
        elif 0xDC00 <= first <= 0xDFFF:
            self._fail(SYNTAX, "unpaired low surrogate in JSON string")
        else:
            scalar = first
        pieces.append(chr(scalar))
        return at

    def _hex4(self, at: int) -> tuple[int, int]:
        text = self._text
        if at + 4 > len(text):
            self._fail(SYNTAX, "incomplete Unicode escape")
        self._spend(4)
        value = 0
        try:
            for index in range(at, at + 4):
                value = value * 16 + _HEX_VALUES[text[index]]
        except KeyError:
            self._fail(SYNTAX, "invalid Unicode escape")
        return value, at + 4


class _Writer:
    """Deterministic exact writer. Accepted types are exact: ``bool`` before
    ``int``, ``int``, ``str``, ``JsonNumber``, ``list``, ``dict`` with exact
    ``str`` keys. Float, Decimal, subclasses, tuples, sets, and custom types
    are rejected — no dispatch through untrusted ``__str__``/hook methods.
    Output length is UTF-8 bytes, bounded before every append."""

    __slots__ = ("_limits", "_work", "_output", "_length", "_seen", "_path")

    def __init__(self, limits: JsonLimits) -> None:
        self._limits = limits
        self._work = limits.max_work
        self._output: list[str] = []
        self._length = 0
        self._seen: set[int] = set()
        self._path: list[str | int] = []

    def finish(self) -> str:
        return "".join(self._output)

    def _spend(self, amount: int) -> None:
        self._work -= amount
        if self._work < 0:
            raise JsonError(RESOURCE_LIMIT, "JSON work limit exceeded")

    def _push(self, text: str) -> None:
        width = len(text) if text.isascii() else len(text.encode("utf-8", "strict"))
        if self._length + width > self._limits.max_output_bytes:
            raise JsonError(RESOURCE_LIMIT, "JSON output exceeds its byte limit")
        self._spend(width)
        self._length += width
        self._output.append(text)

    def _path_text(self) -> str | None:
        return _render_path(self._path)

    def _enter(self, value: object, depth: int) -> int:
        next_depth = depth + 1
        marker = id(value)
        if marker in self._seen:
            raise JsonError(CYCLE, "JSON value contains a cycle", path=self._path_text())
        if next_depth > self._limits.max_depth:
            raise JsonError(
                RESOURCE_LIMIT, "JSON nesting limit exceeded", path=self._path_text()
            )
        self._seen.add(marker)
        return next_depth

    def value(self, value: object, depth: int) -> None:
        self._spend(1)
        kind = type(value)
        if kind is bool:
            self._push("true" if value else "false")
        elif kind is int:
            self._integer(cast(int, value))
        elif kind is str:
            self._string(cast(str, value))
        elif value is None:
            self._push("null")
        elif kind is JsonNumber:
            self._push(cast(JsonNumber, value).token)
        elif kind is list:
            self._array(cast(list[object], value), depth)
        elif kind is dict:
            self._object(cast(dict[object, object], value), depth)
        else:
            raise JsonError(
                UNSUPPORTED_VALUE,
                f"unsupported type {kind.__name__}: exact JSON encoding accepts"
                " None, bool, int, str, JsonNumber, list, and dict with str keys",
                path=self._path_text(),
            )

    def _integer(self, value: int) -> None:
        # Exact base-10 rendering without str(int): the global int->str digit
        # limit must not gate encoding, and no float may appear.
        if value == 0:
            self._push("0")
            return
        negative = value < 0
        magnitude = -value if negative else value
        # 30102/100000 is below log10(2): this lower bound cannot reject
        # a fitting value. _push checks the exact final byte count.
        estimate = ((magnitude.bit_length() - 1) * 30102) // 100000 + 1 + int(negative)
        if self._length + estimate > self._limits.max_output_bytes:
            raise JsonError(RESOURCE_LIMIT, "JSON output exceeds its byte limit")
        chunks = []
        while magnitude:
            self._spend(max(1, (magnitude.bit_length() + 29) // 30))
            magnitude, remainder = divmod(magnitude, 1000000000)
            chunks.append(remainder)
        text = str(chunks[-1]) + "".join(
            f"{chunk:09d}" for chunk in reversed(chunks[:-1])
        )
        self._push("-" + text if negative else text)

    def _string(self, value: str) -> None:
        self._push('"')
        for char in value:
            escape = _CHAR_TO_ESCAPE.get(char)
            if escape is not None:
                self._push(escape)
            elif char < " ":
                self._push(f"\\u{ord(char):04x}")
            else:
                code = ord(char)
                if 0xD800 <= code <= 0xDFFF:
                    raise JsonError(
                        UNSUPPORTED_VALUE,
                        "lone surrogate character cannot be represented in exact"
                        " JSON output; this runtime emits Unicode scalars only",
                        path=self._path_text(),
                    )
                self._push(char)
        self._push('"')

    def _array(self, values: list[object], depth: int) -> None:
        next_depth = self._enter(values, depth)
        self._path.append(0)
        try:
            self._push("[")
            for index, item in enumerate(values):
                if index:
                    self._push(",")
                self._path[-1] = index
                self.value(item, next_depth)
            self._push("]")
        finally:
            self._path.pop()
            self._seen.discard(id(values))

    def _object(self, values: dict[object, object], depth: int) -> None:
        next_depth = self._enter(values, depth)
        self._path.append("")
        try:
            self._push("{")
            first = True
            for key, item in values.items():
                if type(key) is not str:
                    raise JsonError(
                        UNSUPPORTED_VALUE,
                        "JSON object keys must be exactly str",
                        path=self._path_text(),
                    )
                if not first:
                    self._push(",")
                first = False
                self._path[-1] = key
                self._string(key)
                self._push(":")
                self.value(item, next_depth)
            self._push("}")
        finally:
            self._path.pop()
            self._seen.discard(id(values))


if TYPE_CHECKING:
    JsonValue: TypeAlias = Union[None, bool, int, str, JsonNumber, list["JsonValue"], dict[str, "JsonValue"]]
else:
    # Python 3.14 can evaluate imported ForwardRefs in a caller class's scope.
    # This expression resolves only this trusted runtime module, keeping recursive
    # aliases correct even when the caller defines a different JsonValue name.
    _json_forward = ForwardRef(
        f"__import__({__name__!r}, fromlist=['JsonValue']).JsonValue",
        module=__name__,
    )
    JsonValue = Union[None, bool, int, str, JsonNumber,
                      list[_json_forward], dict[str, _json_forward]]
"""Exact JSON value representation: ``None``, ``bool``, ``str``,
``int``, ``JsonNumber``, ``list``, and ``dict`` (exact ``str`` keys)."""


def _effective_limits(limits: JsonLimits | None) -> JsonLimits:
    if limits is None:
        return JsonLimits()
    if type(limits) is not JsonLimits:
        raise TypeError("limits must be JsonLimits")
    for name in ("max_input_bytes", "max_output_bytes", "max_depth", "max_work"):
        value = getattr(limits, name)
        if type(value) is not int or value < 0:
            raise ValueError(f"limit {name} must be a non-negative int")
    if limits.max_depth > _HARD_DEPTH_CEILING:
        raise JsonError(RESOURCE_LIMIT, "JSON nesting limit exceeds the runtime ceiling")
    return limits


def parse_json(text_or_bytes: str | bytes | bytearray | memoryview, limits: JsonLimits | None = None) -> JsonValue:
    """Parse exactly one JSON value with exact number tokens.

    ``bytes``/``bytearray``/``memoryview`` decode as strict UTF-8
    (``invalid_utf8`` on failure). Rejects duplicate decoded keys, lone
    surrogates, malformed JSON, and trailing content.
    """
    limits = _effective_limits(limits)
    byte_input = isinstance(text_or_bytes, (bytes, bytearray, memoryview))
    if isinstance(text_or_bytes, (bytes, bytearray, memoryview)):
        size = text_or_bytes.nbytes if isinstance(text_or_bytes, memoryview) else len(text_or_bytes)
        if size > limits.max_input_bytes:
            raise JsonError(RESOURCE_LIMIT, "JSON input exceeds its byte limit")
        if size > limits.max_work:
            raise JsonError(RESOURCE_LIMIT, "JSON input decoding exceeds its work limit")
        remaining = limits.max_work - size
        try:
            text = bytes(text_or_bytes).decode("utf-8", "strict")
        except UnicodeDecodeError as error:
            raise JsonError(
                INVALID_UTF8, "input is not well-formed UTF-8", error.start
            ) from None
    elif isinstance(text_or_bytes, str):
        text = text_or_bytes
        if len(text) > limits.max_input_bytes:
            raise JsonError(RESOURCE_LIMIT, "JSON input exceeds its byte limit")
        remaining = limits.max_work
        size = 0
        for index, char in enumerate(text):
            remaining -= 1
            if remaining < 0:
                raise JsonError(RESOURCE_LIMIT, "JSON input scanning exceeds its work limit", index)
            code = ord(char)
            if 0xD800 <= code <= 0xDFFF:
                raise JsonError(SYNTAX, "input contains a lone surrogate", index)
            size += 1 if code <= 0x7F else 2 if code <= 0x7FF else 3 if code <= 0xFFFF else 4
            if size > limits.max_input_bytes:
                raise JsonError(RESOURCE_LIMIT, "JSON input exceeds its byte limit", index)
    else:
        raise TypeError("parse_json accepts str or bytes-like input")
    parser = _Parser(text, limits)
    parser._work = remaining
    try:
        return parser.parse()
    except JsonError as error:
        if byte_input and error.offset is not None:
            error.offset = len(text[:error.offset].encode("utf-8"))
        raise


def stringify_json(value: object, limits: JsonLimits | None = None) -> str:
    """Write an exact JSON value deterministically.

    Number tokens keep their spelling; keys keep insertion order (the Rust
    runtime sorts keys — cross-language consumers normalize, see docs).
    Rejects cycles, unsupported types, and lone surrogates with a located
    error; output is bounded before every append.
    """
    limits = _effective_limits(limits)
    writer = _Writer(limits)
    writer.value(value, 0)
    return writer.finish()
