// <auto-generated />
#nullable enable
using global::System;

namespace __NAMESPACE__;

// Emitted only for a bound credential_env v1 policy. Values are read on factory
// invocation and handed to the existing attachment validators, never logged.
internal static class CredentialEnvironment
{
    internal static string? Read(string variable, Action<string> validate) =>
        Read(variable, global::System.Environment.GetEnvironmentVariable, validate);

    internal static string? Read(string variable, Func<string, string?> read, Action<string> validate)
    {
        try
        {
            var value = read(variable);
            if (string.IsNullOrEmpty(value) || value.Length > 8192) return null;
            validate(value);
            return value;
        }
        catch (Exception error) when (error is global::System.Security.SecurityException
            or NotSupportedException or SdkException or CodecException
            or global::System.Text.EncoderFallbackException)
        {
            // One unavailable variable cannot block an anonymous operation or
            // another satisfiable source security alternative.
            return null;
        }
    }
}
