// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.Globalization;
using global::System.IO;
using global::System.Numerics;
using global::System.Text;
using global::System.Text.Json;

namespace __NAMESPACE__;

/// <summary>A source codec failure category; incomplete evaluation is never ordinary invalidity.</summary>
public enum CodecErrorKind
{
    /// <summary>Malformed JSON, duplicate keys, invalid UTF-8 or invalid Unicode.</summary>
    InvalidJson,
    /// <summary>A completed source-schema evaluation rejected the value.</summary>
    InvalidValue,
    /// <summary>Schema evaluation did not complete.</summary>
    EvaluationFailure,
    /// <summary>A finite JSON or conversion resource ceiling was exceeded.</summary>
    ResourceLimit,
    /// <summary>A native value cannot be represented by the declared wire shape.</summary>
    Conversion
}

/// <summary>A typed codec error with original schema identity and RFC 6901 instance path.</summary>
public sealed class CodecException : Exception
{
    /// <summary>Failure category, separate from its human-readable message.</summary>
    public CodecErrorKind Kind { get; }
    /// <summary>Original document URI plus schema pointer, when known.</summary>
    public string SchemaSource { get; }
    /// <summary>Escaped pointer into the instance; empty means its root.</summary>
    public string InstancePath { get; }
    internal CodecException(CodecErrorKind kind, string message, string source = "", string path = "", Exception? inner = null)
        : base(message, inner) { Kind = kind; SchemaSource = source; InstancePath = path; }
}

/// <summary>Declared absence, independent of T's null value. Default is absent.</summary>
public readonly struct Optional<T>
{
    private readonly T _value;
    /// <summary>Whether the wire property is present, including an explicit null.</summary>
    public bool HasValue { get; }
    /// <summary>The present value; throws if the property is absent.</summary>
    public T Value => HasValue ? _value : throw new InvalidOperationException("Optional value is absent");
    private Optional(T value) { _value = value; HasValue = true; }
    /// <summary>Construct a present value, including null when T permits it.</summary>
    public static Optional<T> Present(T value) => new(value);
    /// <summary>Construct a present value with ordinary object-initializer syntax.</summary>
    public static implicit operator Optional<T>(T value) => Present(value);
}

/// <summary>The only JSON null value, used for null-only schemas.</summary>
public readonly record struct JsonNull;

/// <summary>An uninhabited source domain. Consumers cannot construct a value.</summary>
public sealed class Never { private Never() { } }

/// <summary>An exact JSON numeric token. Neither binary floating point nor decimal is used.</summary>
public readonly struct JsonNumber : IEquatable<JsonNumber>, IComparable<JsonNumber>
{
    private readonly string? _token;
    /// <summary>Original token spelling, including negative zero, trailing zeros and exponent.</summary>
    public string Token => _token ?? throw new CodecException(CodecErrorKind.Conversion, "Default JsonNumber is not a JSON value");
    /// <summary>Normalized signed arbitrary-precision coefficient, without trailing decimal zeros.</summary>
    public BigInteger Coefficient => ExactNumber.Parse(Token).Coefficient;
    /// <summary>Normalized symbolic base-ten exponent; its magnitude is never expanded.</summary>
    public BigInteger Exponent => ExactNumber.Parse(Token).Exponent;
    /// <summary>Mathematical integrality, independent of token spelling.</summary>
    public bool IsInteger => ExactNumber.Parse(Token).Integral;
    /// <summary>Parse one exact JSON token under the 4096-byte operand ceiling.</summary>
    public JsonNumber(string token)
    {
        if (token is null) throw new CodecException(CodecErrorKind.InvalidJson, "A JSON number token is required");
        JsonRuntime.CheckNumber(token);
        _token = token;
    }
    /// <summary>Create an exact number from a native arbitrary-precision integer.</summary>
    public static JsonNumber FromInteger(BigInteger value)
    {
        // A conservative binary-size guard bounds decimal formatting, without rejecting any fitting decimal token.
        if (value.GetByteCount() > JsonRuntime.MaxNumberBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "Native integer exceeds the numeric operand ceiling");
        return new(value.ToString(CultureInfo.InvariantCulture));
    }
    /// <summary>Mathematical comparison with no exponent expansion.</summary>
    public int CompareTo(JsonNumber other) => ExactNumber.Parse(Token).Compare(ExactNumber.Parse(other.Token));
    /// <summary>Token identity. Use CompareTo for mathematical equality.</summary>
    public bool Equals(JsonNumber other) => StringComparer.Ordinal.Equals(_token, other._token);
    /// <summary>Token identity.</summary>
    public override bool Equals(object? value) => value is JsonNumber number && Equals(number);
    /// <summary>A hash of the retained token, consistent with token identity.</summary>
    public override int GetHashCode() => _token is null ? 0 : StringComparer.Ordinal.GetHashCode(_token);
    /// <summary>The original token.</summary>
    public override string ToString() => Token;
}

/// <summary>An exact, mathematically integral JSON token, retaining its original exponent and spelling.</summary>
public readonly struct JsonInteger : IEquatable<JsonInteger>
{
    private readonly JsonNumber _number;
    /// <summary>The original JSON numeric token.</summary>
    public string Token => _number.Token;
    /// <summary>Normalized signed arbitrary-precision coefficient.</summary>
    public BigInteger Coefficient => _number.Coefficient;
    /// <summary>Symbolic base-ten exponent, without expansion.</summary>
    public BigInteger Exponent => _number.Exponent;
    /// <summary>Parse a mathematically integral token, including forms such as 1.00e2.</summary>
    public JsonInteger(string token)
    {
        _number = new JsonNumber(token);
        if (!_number.IsInteger) throw new CodecException(CodecErrorKind.Conversion, "JSON number is not mathematically integral");
    }
    /// <summary>Construct from a native integer without floating point.</summary>
    public static implicit operator JsonInteger(int value) => new(value.ToString(CultureInfo.InvariantCulture));
    /// <summary>Construct from a native integer without floating point.</summary>
    public static implicit operator JsonInteger(long value) => new(value.ToString(CultureInfo.InvariantCulture));
    /// <summary>Construct from an arbitrary-precision integer.</summary>
    public static JsonInteger FromInteger(BigInteger value) => new(JsonNumber.FromInteger(value).Token);
    /// <summary>Materialize only if the expanded integer fits a caller-selected decimal-digit budget (at most 4096).</summary>
    public BigInteger ToBigInteger(int maxDigits = 4096)
    {
        if (maxDigits < 1 || maxDigits > 4096) throw new ArgumentOutOfRangeException(nameof(maxDigits));
        var exact = ExactNumber.Parse(Token);
        if (exact.Sign == 0) return BigInteger.Zero;
        if (exact.Exponent + exact.Digits.Length > maxDigits)
            throw new CodecException(CodecErrorKind.ResourceLimit, "Expanded integer exceeds the requested digit budget");
        return exact.Coefficient * BigInteger.Pow(10, (int)exact.Exponent);
    }
    /// <summary>Token identity; equivalent mathematical spellings remain distinguishable.</summary>
    public bool Equals(JsonInteger other) => _number.Equals(other._number);
    /// <summary>Token identity.</summary>
    public override bool Equals(object? value) => value is JsonInteger integer && Equals(integer);
    /// <summary>A hash of the original token.</summary>
    public override int GetHashCode() => _number.GetHashCode();
    /// <summary>The original JSON numeric token.</summary>
    public override string ToString() => Token;
}

internal sealed class ExactNumber
{
    internal int Sign { get; }
    internal string Digits { get; }
    internal BigInteger Exponent { get; }
    internal BigInteger Coefficient => Sign * BigInteger.Parse(Digits, NumberStyles.None, CultureInfo.InvariantCulture);
    internal bool Integral => Sign == 0 || Exponent.Sign >= 0;
    private ExactNumber(int sign, string digits, BigInteger exponent) { Sign = sign; Digits = digits; Exponent = exponent; }
    internal static ExactNumber Parse(string token)
    {
        var start = token[0] == '-' ? 1 : 0;
        var e = token.IndexOfAny(new[] { 'e', 'E' });
        var end = e < 0 ? token.Length : e;
        var dot = token.IndexOf('.');
        var digits = token.Substring(start, end - start).Replace(".", "", StringComparison.Ordinal).TrimStart('0');
        if (digits.Length == 0) return new ExactNumber(0, "0", BigInteger.Zero);
        var normalized = digits.TrimEnd('0');
        var exponent = e < 0 ? BigInteger.Zero : BigInteger.Parse(token.AsSpan(e + 1), NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture);
        exponent += digits.Length - normalized.Length - (dot < 0 ? 0 : end - dot - 1);
        return new ExactNumber(start == 1 ? -1 : 1, normalized, exponent);
    }
    internal int Compare(ExactNumber other)
    {
        if (Sign != other.Sign) return Sign.CompareTo(other.Sign);
        if (Sign == 0) return 0;
        var order = (Exponent + Digits.Length).CompareTo(other.Exponent + other.Digits.Length);
        if (order == 0)
        {
            var size = Math.Max(Digits.Length, other.Digits.Length);
            order = StringComparer.Ordinal.Compare(Digits.PadRight(size, '0'), other.Digits.PadRight(size, '0'));
        }
        return Sign * Math.Sign(order);
    }
    internal bool MultipleOf(ExactNumber divisor, Action<int> spend)
    {
        if (Sign == 0) return true;
        var shift = Exponent - divisor.Exponent;
        if (shift.Sign < 0) return false;
        spend(Digits.Length + divisor.Digits.Length);
        var numerator = BigInteger.Abs(Coefficient);
        var denominator = BigInteger.Abs(divisor.Coefficient);
        foreach (var prime in new[] { 2, 5 })
        {
            var powers = BigInteger.Zero;
            while (denominator % prime == 0 && powers < shift)
            {
                spend(1); denominator /= prime; powers++;
            }
        }
        return numerator % denominator == 0;
    }
}

internal static class JsonRuntime
{
    internal const int MaxBytes = 8 * 1024 * 1024;
    internal const int MaxDepth = 128;
    internal const int MaxWork = 1_000_000;
    internal const int MaxNumberBytes = 4096;
    internal static readonly UTF8Encoding Utf8 = new(false, true);
    internal static string Child(string path, string key) => path + "/" + key.Replace("~", "~0", StringComparison.Ordinal).Replace("/", "~1", StringComparison.Ordinal);
    internal static string CheckedString(string? value, string path)
    {
        if (value is null) throw new CodecException(CodecErrorKind.Conversion, "A non-null string is required", path: path);
        for (var i = 0; i < value.Length; i++)
        {
            if (char.IsHighSurrogate(value[i]))
            {
                if (++i == value.Length || !char.IsLowSurrogate(value[i]))
                    throw new CodecException(CodecErrorKind.InvalidJson, "Unpaired UTF-16 surrogate", path: path);
            }
            else if (char.IsLowSurrogate(value[i])) throw new CodecException(CodecErrorKind.InvalidJson, "Unpaired UTF-16 surrogate", path: path);
        }
        return value;
    }
    internal static byte[] Bytes(string text)
    {
        if (text is not null && text.Length > MaxBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "JSON input byte budget exhausted");
        text = CheckedString(text, "");
        if (Utf8.GetByteCount(text) > MaxBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "JSON input byte budget exhausted");
        return Utf8.GetBytes(text);
    }
    internal static void CheckNumber(string token)
    {
        if (token.Length > MaxNumberBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "Numeric operand byte budget exhausted");
        var i = token.StartsWith('-') ? 1 : 0;
        var valid = i < token.Length;
        if (valid && token[i] == '0') i++;
        else if (valid && token[i] is >= '1' and <= '9') { while (i < token.Length && token[i] is >= '0' and <= '9') i++; }
        else valid = false;
        if (i < token.Length && token[i] == '.')
        {
            var first = ++i; while (i < token.Length && token[i] is >= '0' and <= '9') i++;
            valid &= i > first;
        }
        if (i < token.Length && token[i] is 'e' or 'E')
        {
            i++; if (i < token.Length && token[i] is '+' or '-') i++;
            var first = i; while (i < token.Length && token[i] is >= '0' and <= '9') i++;
            valid &= i > first;
        }
        if (!valid || i != token.Length) throw new CodecException(CodecErrorKind.InvalidJson, "Invalid JSON numeric token");
    }
    internal static JsonElement Parse(ReadOnlySpan<byte> bytes)
    {
        if (bytes.Length > MaxBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "JSON input byte budget exhausted");
        try
        {
            _ = Utf8.GetCharCount(bytes);
            var reader = new Utf8JsonReader(bytes, new JsonReaderOptions { MaxDepth = MaxDepth + 1 });
            var objects = new Stack<HashSet<string>>();
            var work = MaxWork;
            while (reader.Read())
            {
                if (--work < 0) throw new CodecException(CodecErrorKind.ResourceLimit, "JSON token work budget exhausted");
                if (reader.TokenType is JsonTokenType.StartObject or JsonTokenType.StartArray && reader.CurrentDepth >= MaxDepth)
                    throw new CodecException(CodecErrorKind.ResourceLimit, "JSON depth budget exhausted");
                switch (reader.TokenType)
                {
                    case JsonTokenType.StartObject: objects.Push(new HashSet<string>(StringComparer.Ordinal)); break;
                    case JsonTokenType.EndObject: objects.Pop(); break;
                    case JsonTokenType.PropertyName:
                        var name = CheckedString(reader.GetString(), "");
                        if (!objects.Peek().Add(name)) throw new CodecException(CodecErrorKind.InvalidJson, "Duplicate decoded JSON object key");
                        break;
                    case JsonTokenType.String: CheckedString(reader.GetString(), ""); break;
                    case JsonTokenType.Number:
                        if (reader.ValueSpan.Length > MaxNumberBytes) throw new CodecException(CodecErrorKind.ResourceLimit, "Numeric operand byte budget exhausted");
                        break;
                }
            }
            using var document = JsonDocument.Parse(bytes.ToArray(), new JsonDocumentOptions { MaxDepth = MaxDepth });
            return document.RootElement.Clone();
        }
        catch (Exception error) when (error is JsonException or InvalidOperationException or DecoderFallbackException)
        { throw new CodecException(CodecErrorKind.InvalidJson, "Malformed JSON or invalid Unicode", inner: error); }
    }
    internal static void WriteElement(Utf8JsonWriter writer, JsonElement value, ConversionContext context, string path)
    {
        using var scope = context.EnterRead(path);
        switch (value.ValueKind)
        {
            case JsonValueKind.Null: writer.WriteNullValue(); break;
            case JsonValueKind.True: writer.WriteBooleanValue(true); break;
            case JsonValueKind.False: writer.WriteBooleanValue(false); break;
            case JsonValueKind.String: writer.WriteStringValue(context.String(value.GetString(), path)); break;
            case JsonValueKind.Number:
                writer.WriteRawValue(context.Number(value.GetRawText(), path), true); break;
            case JsonValueKind.Array:
                writer.WriteStartArray(); var index = 0;
                foreach (var child in value.EnumerateArray()) WriteElement(writer, child, context, Child(path, (index++).ToString(CultureInfo.InvariantCulture)));
                writer.WriteEndArray(); break;
            case JsonValueKind.Object:
                writer.WriteStartObject(); var names = new HashSet<string>(StringComparer.Ordinal);
                foreach (var property in value.EnumerateObject())
                {
                    if (!names.Add(property.Name)) throw new CodecException(CodecErrorKind.InvalidJson, "Duplicate decoded JSON key", path: path);
                    writer.WritePropertyName(context.String(property.Name, path));
                    WriteElement(writer, property.Value, context, Child(path, property.Name));
                }
                writer.WriteEndObject(); break;
            default: throw new CodecException(CodecErrorKind.Conversion, "Undefined JsonElement is not JSON", path: path);
        }
    }
    internal static JsonElement CloneElement(JsonElement value, ConversionContext context, string path)
    {
        CheckElement(value, context, path);
        return value.Clone();
    }
    private static void CheckElement(JsonElement value, ConversionContext context, string path)
    {
        using var scope = context.EnterRead(path);
        switch (value.ValueKind)
        {
            case JsonValueKind.String: context.String(value.GetString(), path); break;
            case JsonValueKind.Number: context.Number(value.GetRawText(), path); break;
            case JsonValueKind.Array:
                var index = 0;
                foreach (var child in value.EnumerateArray()) CheckElement(child, context, Child(path, (index++).ToString(CultureInfo.InvariantCulture)));
                break;
            case JsonValueKind.Object:
                var names = new HashSet<string>(StringComparer.Ordinal);
                foreach (var property in value.EnumerateObject())
                {
                    context.String(property.Name, path);
                    if (!names.Add(property.Name)) throw new CodecException(CodecErrorKind.InvalidJson, "Duplicate decoded JSON key", path: path);
                    CheckElement(property.Value, context, Child(path, property.Name));
                }
                break;
            case JsonValueKind.Null: case JsonValueKind.True: case JsonValueKind.False: break;
            default: throw new CodecException(CodecErrorKind.Conversion, "Undefined JsonElement is not JSON", path: path);
        }
    }
}

internal sealed class LimitedStream : MemoryStream
{
    private readonly int _maximum;
    internal LimitedStream(int maximum = JsonRuntime.MaxBytes) { _maximum = maximum; }
    private void Check(int count) { if (count > _maximum - Length) throw new CodecException(CodecErrorKind.ResourceLimit, "JSON output byte budget exhausted"); }
    public override void Write(byte[] buffer, int offset, int count) { Check(count); base.Write(buffer, offset, count); }
    public override void Write(ReadOnlySpan<byte> buffer) { Check(buffer.Length); base.Write(buffer); }
    public override void WriteByte(byte value) { Check(1); base.WriteByte(value); }
}

internal sealed class ConversionContext
{
    internal ValidationSession Validation { get; } = new();
    private int _depth;
    private int _remaining = JsonRuntime.MaxWork;
    private readonly HashSet<object> _active = new(ReferenceEqualityComparer.Instance);
    internal IDisposable EnterRead(string path) => Enter(null, path, false);
    internal void Spend(int amount, string path)
    {
        if (amount < 0 || amount > _remaining) throw new CodecException(CodecErrorKind.ResourceLimit, "Conversion work/byte budget exhausted", path: path);
        _remaining -= amount;
    }
    internal T Scalar<T>(T value, string path) { Spend(1, path); return value; }
    internal string String(string? value, string path)
    {
        if (value is null) throw new CodecException(CodecErrorKind.Conversion, "A non-null string is required", path: path);
        Spend(1, path);
        // Admission precedes scanning/counting/copying; even empty scalar values consume a visit.
        Spend(value.Length, path);
        JsonRuntime.CheckedString(value, path);
        Spend(JsonRuntime.Utf8.GetByteCount(value) - value.Length, path);
        return value;
    }
    internal string Number(string token, string path)
    { JsonRuntime.CheckNumber(token); Spend(token.Length, path); return token; }
    internal IDisposable Enter(object? value, string path, bool track = true)
    {
        Spend(1, path);
        if (++_depth > JsonRuntime.MaxDepth) throw new CodecException(CodecErrorKind.ResourceLimit, "Conversion depth budget exhausted", path: path);
        if (track && value is null) throw new CodecException(CodecErrorKind.Conversion, "Non-null native value required", path: path);
        if (track && !_active.Add(value!)) throw new CodecException(CodecErrorKind.Conversion, "Cyclic native value graph", path: path);
        return new Scope(this, track ? value : null);
    }
    private sealed class Scope : IDisposable
    {
        private readonly ConversionContext _context;
        private readonly object? _value;
        internal Scope(ConversionContext context, object? value) { _context = context; _value = value; }
        public void Dispose() { _context._depth--; if (_value is not null) _context._active.Remove(_value); }
    }
}

internal static class CodecRuntime
{
    internal static Never ReadNever(string path) => throw new CodecException(CodecErrorKind.Conversion, "Uninhabited source value", path: path);
    internal static T Decode<T>(ReadOnlySpan<byte> bytes, int root, Func<JsonElement, ConversionContext, string, T> read)
    {
        try
        {
            var value = JsonRuntime.Parse(bytes); var context = new ConversionContext();
            context.Spend(bytes.Length, "");
            context.Validation.Check(root, value, "");
            return read(value, context, "");
        }
        catch (CodecException) { throw; }
        catch (Exception error) when (error is JsonException or InvalidOperationException or ArgumentException or FormatException or OverflowException)
        { throw new CodecException(CodecErrorKind.Conversion, "JSON value could not be converted to the source-native representation"); }
    }
    internal static byte[] Encode<T>(T value, int root, Action<Utf8JsonWriter, T, ConversionContext, string> write)
    {
        try
        {
            var context = new ConversionContext();
            var bytes = EncodeValue(value, context, "", write);
            context.Spend(bytes.Length, "");
            context.Validation.Check(root, JsonRuntime.Parse(bytes), "");
            return bytes;
        }
        catch (CodecException) { throw; }
        catch (Exception error) when (error is JsonException or InvalidOperationException or ArgumentException or FormatException or OverflowException)
        { throw new CodecException(CodecErrorKind.Conversion, "Native value could not be converted to the source JSON representation"); }
    }
    private static byte[] EncodeValue<T>(T value, ConversionContext context, string path, Action<Utf8JsonWriter, T, ConversionContext, string> write)
    {
        using var output = new LimitedStream();
        using (var writer = new Utf8JsonWriter(output, new JsonWriterOptions { MaxDepth = JsonRuntime.MaxDepth }))
        { write(writer, value, context, path); writer.Flush(); }
        context.Spend((int)output.Length, path);
        return output.ToArray();
    }
    internal static void WriteBranch<T>(Utf8JsonWriter writer, T value, ConversionContext context, string path, int root, Action<Utf8JsonWriter, T, ConversionContext, string> write)
    {
        var bytes = EncodeValue(value, context, path, write);
        context.Spend(bytes.Length, path);
        context.Validation.Check(root, JsonRuntime.Parse(bytes), path);
        writer.WriteRawValue(bytes, true);
    }
    internal static List<T> ReadList<T>(JsonElement value, ConversionContext context, string path, Func<JsonElement, ConversionContext, string, T> read)
    {
        using var scope = context.EnterRead(path); var result = new List<T>(); var index = 0;
        foreach (var item in value.EnumerateArray()) result.Add(read(item, context, JsonRuntime.Child(path, (index++).ToString(CultureInfo.InvariantCulture))));
        return result;
    }
    internal static void WriteList<T>(Utf8JsonWriter writer, List<T> value, ConversionContext context, string path, Action<Utf8JsonWriter, T, ConversionContext, string> write)
    {
        using var scope = context.Enter(value, path); writer.WriteStartArray();
        for (var i = 0; i < value.Count; i++) write(writer, value[i], context, JsonRuntime.Child(path, i.ToString(CultureInfo.InvariantCulture)));
        writer.WriteEndArray();
    }
    internal static Dictionary<string, T> ReadMap<T>(JsonElement value, ConversionContext context, string path, Func<JsonElement, ConversionContext, string, T> read)
    {
        using var scope = context.EnterRead(path); var result = new Dictionary<string, T>(StringComparer.Ordinal);
        foreach (var property in value.EnumerateObject()) result.Add(context.String(property.Name, path), read(property.Value, context, JsonRuntime.Child(path, property.Name)));
        return result;
    }
    internal static void WriteMap<T>(Utf8JsonWriter writer, Dictionary<string, T> value, ConversionContext context, string path, Action<Utf8JsonWriter, T, ConversionContext, string> write)
    {
        using var scope = context.Enter(value, path); writer.WriteStartObject();
        context.Spend(value.Count, path);
        var keys = new List<string>(value.Keys); keys.Sort(StringComparer.Ordinal);
        foreach (var key in keys) { writer.WritePropertyName(context.String(key, path)); write(writer, value[key], context, JsonRuntime.Child(path, key)); }
        writer.WriteEndObject();
    }
}
