// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.IO;
using global::System.Linq;
using global::System.Net.Http.Headers;
using global::System.Text;
using global::System.Text.Json;
namespace __NAMESPACE__;

// Positional multipart is an ordered sequence, not a dictionary of invented names.
internal static class PositionalRuntime
{
    private const int MaxParts=1024;
    private const int MaxHeaders=65_536;
    internal static int PrefixCount(bool[] present)
    {
        if(present.Length>MaxParts)throw new SdkException(SdkErrorKind.ResourceLimit);
        var count=0;var absent=false;
        foreach(var value in present){if(value&&absent)throw new SdkException(SdkErrorKind.RequestRepresentation);if(value)count++;else absent=true;}
        return count;
    }
    internal static void Count(JsonElement plan,int count)
    {
        if(count<0||count>MaxParts)throw new SdkException(SdkErrorKind.ResourceLimit);
        if(plan.GetProperty("min_items").ValueKind==JsonValueKind.Object&&(ulong)count<plan.GetProperty("min_items").GetProperty("value").GetUInt64()||
            plan.GetProperty("max_items").ValueKind==JsonValueKind.Object&&(ulong)count>plan.GetProperty("max_items").GetProperty("value").GetUInt64()||
            plan.GetProperty("items").GetProperty("kind").GetString()=="forbidden"&&count>plan.GetProperty("prefix").GetArrayLength())
            throw new SdkException(SdkErrorKind.RequestValidation);
    }
    internal static JsonElement Part(JsonElement plan,int index)
    {
        var prefix=plan.GetProperty("prefix");if(index<prefix.GetArrayLength())return prefix[index];
        var additional=plan.GetProperty("items");if(additional.GetProperty("kind").GetString()=="allowed")return additional.GetProperty("part");
        throw new SdkException(SdkErrorKind.RequestValidation);
    }
    internal static void Add(JsonElement plan,List<RawPart> parts,RawPart part)
    {
        if(parts.Count>=MaxParts)throw new SdkException(SdkErrorKind.ResourceLimit);
        var bytes=part.Data.Length;
        foreach(var existing in parts){if(existing.Data.Length>JsonRuntime.MaxBytes-bytes)throw new SdkException(SdkErrorKind.ResourceLimit);bytes+=existing.Data.Length;}
        PartsRuntime.ValidatePart(Part(plan,parts.Count),part);parts.Add(part);
    }
    private static string Boundary(string contentType)
    {
        var media=MediaRuntime.Parse(contentType);var raw=media.Parameters.FirstOrDefault(p=>p.Name.Equals("boundary",StringComparison.OrdinalIgnoreCase))?.Value;
        if(raw is null)throw new CodecException(CodecErrorKind.Conversion,"Multipart boundary is absent");
        var value=MediaRuntime.Unquote(raw);
        if(value.Length<1||value.Length>70||value.EndsWith(' ')||value.Any(c=>!(c is >= 'a' and <= 'z' or >= 'A' and <= 'Z' or >= '0' and <= '9'||"'()+_,-./:=? ".Contains(c))))
            throw new CodecException(CodecErrorKind.Conversion,"Invalid MIME boundary");
        return value;
    }
    private static bool FormData(string media)=>MediaRuntime.Parse(media).MediaType!.Equals("multipart/form-data",StringComparison.OrdinalIgnoreCase);
    private static string Quoted(string value)=>"\""+value.Replace("\\","\\\\",StringComparison.Ordinal).Replace("\"","\\\"",StringComparison.Ordinal)+"\"";
    private static ContentDispositionHeaderValue? Disposition(IReadOnlyDictionary<string,IReadOnlyList<string>> headers,bool formData)
    {
        if(!headers.TryGetValue("Content-Disposition",out var values))
        {if(formData)throw new CodecException(CodecErrorKind.Conversion,"Positional form-data requires a declared named disposition");return null;}
        if(values.Count!=1||!ContentDispositionHeaderValue.TryParse(values[0],out var parsed)||parsed.FileNameStar is not null)
            throw new CodecException(CodecErrorKind.Conversion,"Unsupported positional part disposition");
        var names=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if(parsed.Parameters.Any(p=>!names.Add(p.Name))||formData&&(!parsed.DispositionType.Equals("form-data",StringComparison.OrdinalIgnoreCase)||string.IsNullOrEmpty(parsed.Name)))
            throw new CodecException(CodecErrorKind.Conversion,"Ambiguous positional part disposition");
        return parsed;
    }
    internal static EncodedBody Encode(JsonElement media,int index,List<RawPart> parts,string? actual)
    {
        var plan=media.GetProperty("representation").GetProperty("multipart");Count(plan,parts.Count);
        var type=actual??media.GetProperty("media_type").GetProperty("declared").GetString()!;
        var parsed=MediaRuntime.Parse(type);
        if(!parsed.Parameters.Any(p=>p.Name.Equals("boundary",StringComparison.OrdinalIgnoreCase)))type+="; boundary=suspect-"+Guid.NewGuid().ToString("N");
        var boundary=Boundary(type);var marker=Encoding.ASCII.GetBytes(boundary);var formData=FormData(type);
        using var output=new LimitedStream();
        void Text(string value)=>output.Write(JsonRuntime.Utf8.GetBytes(value));
        for(var i=0;i<parts.Count;i++)
        {
            var part=parts[i];PartsRuntime.ValidatePart(Part(plan,i),part);
            if(part.Data.AsSpan().IndexOf(marker)>=0)throw new SdkException(SdkErrorKind.RequestRepresentation);
            var disposition=Disposition(part.Headers,formData);
            if(disposition is not null&&part.FileName is not null&&(disposition.FileName is null||MediaRuntime.Unquote(disposition.FileName)!=part.FileName))throw new SdkException(SdkErrorKind.RequestRepresentation);
            Text("--"+boundary+"\r\n");
            var headerBytes=0;var headerCount=0;
            void Header(string name,string value)
            {
                if(++headerCount>128||name.Length>MaxHeaders||value.Length>MaxHeaders||!HttpRuntime.HeaderName(name)||value.Any(c=>c<32&&c!='\t'||c==127))throw new SdkException(SdkErrorKind.RequestRepresentation);
                headerBytes+=JsonRuntime.Utf8.GetByteCount(name)+JsonRuntime.Utf8.GetByteCount(value)+4;
                if(headerBytes>MaxHeaders)throw new SdkException(SdkErrorKind.ResourceLimit);
                Text(name+": "+value+"\r\n");
            }
            if(part.ContentType is not null)Header("Content-Type",part.ContentType);
            if(disposition is null&&part.FileName is not null)Header("Content-Disposition","attachment; filename="+Quoted(part.FileName));
            foreach(var (name,values) in part.Headers)
            {
                if(name.Equals("Content-Type",StringComparison.OrdinalIgnoreCase)||name.Equals("Content-Transfer-Encoding",StringComparison.OrdinalIgnoreCase))throw new SdkException(SdkErrorKind.RequestRepresentation);
                foreach(var value in values)Header(name,value);
            }
            Text("\r\n");output.Write(part.Data);Text("\r\n");
        }
        Text("--"+boundary+"--\r\n");return new EncodedBody(output.ToArray(),index,type);
    }
    // A valid delimiter is a complete MIME delimiter line, not a byte substring
    // such as CRLF--boundarySuffix inside an otherwise arbitrary binary payload.
    private static bool Delimiter(byte[] bytes,int at,byte[] marker,out int after,out bool closing)
    {
        after=at;closing=false;if(at<0||!bytes.AsSpan(at).StartsWith(marker))return false;
        var cursor=at+marker.Length;
        if(bytes.AsSpan(cursor).StartsWith("--"u8)){closing=true;cursor+=2;}
        while(cursor<bytes.Length&&bytes[cursor] is 32 or 9)cursor++;
        if(closing&&cursor==bytes.Length){after=cursor;return true;}
        if(!bytes.AsSpan(cursor).StartsWith("\r\n"u8))return false;
        after=cursor+2;return true;
    }
    private static int Next(byte[] bytes,int start,byte[] marker,out int after,out bool closing)
    {
        for(var position=start;position<bytes.Length;)
        {
            var found=bytes.AsSpan(position).IndexOf(marker);if(found<0)break;var at=position+found;
            if((at==0||at>=2&&bytes[at-2]==13&&bytes[at-1]==10)&&Delimiter(bytes,at,marker,out after,out closing))return at;
            position=at+marker.Length;
        }
        after=0;closing=false;throw new CodecException(CodecErrorKind.Conversion,"Multipart closing delimiter is absent");
    }
    private static Dictionary<string,IReadOnlyList<string>> Headers(byte[] bytes,ref int position)
    {
        if(bytes.AsSpan(position).StartsWith("\r\n"u8)){position+=2;return new(StringComparer.OrdinalIgnoreCase);}
        var end=bytes.AsSpan(position).IndexOf("\r\n\r\n"u8);
        if(end<0)throw new CodecException(CodecErrorKind.Conversion,"Multipart part headers are incomplete");
        if(end>MaxHeaders)throw new CodecException(CodecErrorKind.ResourceLimit,"Multipart part headers exceed the byte ceiling");
        var text=JsonRuntime.Utf8.GetString(bytes,position,end);position+=end+4;
        var lines=new List<string>();
        foreach(var line in text.Split("\r\n"))
        {
            if(line.Length>0&&line[0] is ' ' or '\t')
            {if(lines.Count==0)throw new CodecException(CodecErrorKind.Conversion,"Header continuation has no field");lines[^1]+=" "+line.TrimStart(' ','\t');}
            else lines.Add(line);
        }
        if(lines.Count>128)throw new CodecException(CodecErrorKind.ResourceLimit,"Too many positional part headers");
        var result=new Dictionary<string,IReadOnlyList<string>>(StringComparer.OrdinalIgnoreCase);
        foreach(var line in lines)
        {
            var colon=line.IndexOf(':');if(colon<1||!HttpRuntime.HeaderName(line[..colon])||line.Any(c=>c<32&&c!='\t'||c==127))throw new CodecException(CodecErrorKind.Conversion,"Invalid positional part header");
            var name=line[..colon];var value=line[(colon+1)..].Trim(' ','\t');
            if(result.TryGetValue(name,out var previous))result[name]=Array.AsReadOnly(previous.Concat(new[]{value}).ToArray());else result.Add(name,Array.AsReadOnly(new[]{value}));
        }
        return result;
    }
    internal static List<RawPart> Decode(JsonElement media,byte[] bytes,string contentType)
    {
        if(bytes.Length>JsonRuntime.MaxBytes)throw new SdkException(SdkErrorKind.ResourceLimit);
        var plan=media.GetProperty("representation").GetProperty("multipart");var marker=Encoding.ASCII.GetBytes("--"+Boundary(contentType));var formData=FormData(contentType);
        var parts=new List<RawPart>();_ = Next(bytes,0,marker,out var position,out var closing);
        while(!closing)
        {
            if(parts.Count>=MaxParts)throw new SdkException(SdkErrorKind.ResourceLimit);
            var descriptor=Part(plan,parts.Count);var headers=Headers(bytes,ref position);
            if(headers.ContainsKey("Content-Transfer-Encoding"))throw new CodecException(CodecErrorKind.Conversion,"Transfer-encoded positional parts are unsupported");
            var disposition=Disposition(headers,formData);
            string? content=null;if(headers.TryGetValue("Content-Type",out var types)){if(types.Count!=1)throw new CodecException(CodecErrorKind.Conversion,"Repeated part Content-Type is ambiguous");content=types[0];}
            var effectiveType=content??"text/plain";
            if(!PartsRuntime.PartMediaMatches(descriptor.GetProperty("content_types"),effectiveType))throw new CodecException(CodecErrorKind.Conversion,"Positional part Content-Type differs");
            if(descriptor.GetProperty("representation").GetProperty("kind").GetString()=="text"&&MediaRuntime.Parse(effectiveType).CharSet is { } charset&&!MediaRuntime.Unquote(charset).Equals("utf-8",StringComparison.OrdinalIgnoreCase))throw new CodecException(CodecErrorKind.Conversion,"Positional text charset is unsupported");
            var at=Next(bytes,position,marker,out var after,out closing);var length=at-2-position;
            if(length<0)throw new CodecException(CodecErrorKind.Conversion,"Invalid positional MIME framing");
            var representation=descriptor.GetProperty("representation");var maximum=representation.GetProperty("kind").GetString()=="binary"?representation.GetProperty("bytes").GetProperty("max_bytes").GetUInt64():1024UL*1024;
            if((ulong)length>maximum)throw new CodecException(CodecErrorKind.ResourceLimit,"Positional part byte ceiling exceeded");
            Add(plan,parts,new RawPart(bytes.AsSpan(position,length).ToArray(),disposition?.FileName is { } name?MediaRuntime.Unquote(name):null,content,headers));position=after;
        }
        Count(plan,parts.Count);return parts;
    }
}
