// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.Collections.ObjectModel;
using global::System.Linq;
using global::System.Net.Http.Headers;
using global::System.Text.Json;
using global::System.Threading;
using global::System.Threading.Tasks;
namespace __NAMESPACE__;

/// <summary>The source-declared base category of an API URL, separate from logical references.</summary>
public enum ApiUrlBase
{
    /// <summary>The effective physical retrieval document containing the Server Object.</summary>
    ServerDocument,
    /// <summary>The selected effective server; used by OAuth/OIDC endpoint metadata.</summary>
    EffectiveServer
}
/// <summary>Inert logical resource metadata with independent physical ownership.</summary>
public sealed class ResourceInfo
{
    private readonly JsonElement _data;
    internal ResourceInfo(JsonElement data) { _data = data; }
    /// <summary>Physical lookup source, including its original pointer.</summary>
    public string Source => ProtocolRuntime.Source(_data.GetProperty("source"));
    /// <summary>Physical resource-boundary source.</summary>
    public string ResourceSource => ProtocolRuntime.Source(_data.GetProperty("resource"));
    /// <summary>Canonical logical resource identifier, exactly as indexed.</summary>
    public string CanonicalUri => _data.GetProperty("canonical_uri").GetString()!;
    /// <summary>Logical reference base; this does not relocate an API server.</summary>
    public string BaseUri => _data.GetProperty("base_uri").GetString()!;
    /// <summary>The nearest indexed resource-relative address; no child address is invented.</summary>
    public string ScopeAddress => _data.GetProperty("scope_address").GetString()!;
    /// <summary>Physical source of the logical base declaration, when present.</summary>
    public string? BaseSource => _data.GetProperty("base_source").ValueKind == JsonValueKind.Null ? null : ProtocolRuntime.Source(_data.GetProperty("base_source"));
    /// <summary>Supplied aliases, including requested retrieval aliases; no URI is fetched.</summary>
    public IReadOnlyList<string> Aliases => Array.AsReadOnly(_data.GetProperty("aliases").EnumerateArray().Select(v => v.GetString()!).ToArray());
}

/// <summary>The explicit absence of a body forbidden by HTTP, distinct from JSON null or empty bytes.</summary>
public readonly record struct HttpNoContent;
/// <summary>Caller-supplied Basic credentials. This adapter's Basic encoding is ASCII; no charset negotiation is inferred.</summary>
public sealed record BasicCredential(string UserName, string Password);
/// <summary>Caller-selected Authorization scheme and parameter. OAuth/OIDC does not imply a token type.</summary>
public sealed record AuthorizationValue(string Scheme, string Parameter);
/// <summary>Caller-owned credential attachment hook; acquisition, discovery and refresh are outside the SDK.</summary>
public delegate ValueTask<AuthorizationValue> AuthorizationProvider(CredentialContext context, CancellationToken cancellationToken);
/// <summary>Source-backed OAuth flow metadata, supplied inertly to credential hooks.</summary>
public sealed class OAuthFlowInfo
{
    private readonly JsonElement _data;
    internal OAuthFlowInfo(JsonElement data) { _data=data; }
    /// <summary>Relative endpoint metadata uses the selected effective server.</summary>
    public ApiUrlBase UrlBase => ApiUrlBase.EffectiveServer;
    /// <summary>Declared flow kind.</summary>
    public string Kind => _data.GetProperty("kind").GetString()!;
    /// <summary>Declared authorization URL.</summary>
    public string? AuthorizationUrl => ProtocolRuntime.LocatedString(_data,"authorization_url");
    /// <summary>Declared token URL.</summary>
    public string? TokenUrl => ProtocolRuntime.LocatedString(_data,"token_url");
    /// <summary>Declared refresh URL.</summary>
    public string? RefreshUrl => ProtocolRuntime.LocatedString(_data,"refresh_url");
    /// <summary>Declared device authorization URL.</summary>
    public string? DeviceAuthorizationUrl => ProtocolRuntime.LocatedString(_data,"device_authorization_url");
    /// <summary>Declared scope names and descriptions.</summary>
    public IReadOnlyDictionary<string,string> Scopes => new ReadOnlyDictionary<string,string>(_data.GetProperty("scopes").EnumerateObject().ToDictionary(p=>p.Name,p=>p.Value.GetProperty("value").GetString()!,StringComparer.Ordinal));
}
/// <summary>The exact operation, requirement, scopes/roles and flow/discovery metadata for one attachment.</summary>
public sealed class CredentialContext
{
    private readonly JsonElement _requirement;
    internal CredentialContext(string source,JsonElement requirement,string serverUrl) { OperationSource=source;_requirement=requirement;ServerUrl=serverUrl; }
    /// <summary>The selected effective API server, including explicit caller overrides.</summary>
    public string ServerUrl { get; }
    /// <summary>Relative OAuth/OIDC endpoints use ServerUrl, not a logical resource URI.</summary>
    public ApiUrlBase UrlBase => ApiUrlBase.EffectiveServer;
    /// <summary>Logical scheme context, separate from physical SchemeSource and ServerUrl.</summary>
    public ResourceInfo? SchemeResource => ProtocolRuntime.Resource(_requirement.GetProperty("scheme"),"terminal_resource");
    /// <summary>Original operation document and pointer.</summary>
    public string OperationSource { get; }
    /// <summary>Declared security scheme name.</summary>
    public string SchemeName => _requirement.GetProperty("name").GetString()!;
    /// <summary>Original terminal scheme identity.</summary>
    public string SchemeSource => ProtocolRuntime.Source(_requirement.GetProperty("scheme").GetProperty("terminal"));
    /// <summary>Original requirement use site, distinct from the scheme definition.</summary>
    public string RequirementSource => ProtocolRuntime.Source(_requirement.GetProperty("source"));
    /// <summary>Source-provided credential guidance, without inferring authorization policy.</summary>
    public string? Description => ProtocolRuntime.LocatedString(_requirement,"description");
    /// <summary>Scopes and non-OAuth roles remain distinct.</summary>
    public string PermissionKind => _requirement.GetProperty("permissions").GetProperty("kind").GetString()!;
    /// <summary>Declared permissions, in source order.</summary>
    public IReadOnlyList<string> Permissions => Array.AsReadOnly(_requirement.GetProperty("permissions").GetProperty("names").EnumerateArray().Select(v=>v.GetProperty("value").GetString()!).ToArray());
    /// <summary>Original source locations for each permission, in the same order.</summary>
    public IReadOnlyList<string> PermissionSources => Array.AsReadOnly(_requirement.GetProperty("permissions").GetProperty("names").EnumerateArray().Select(v=>ProtocolRuntime.Source(v.GetProperty("source"))).ToArray());
    /// <summary>Declared OAuth flows; the SDK does not choose or execute one.</summary>
    public IReadOnlyList<OAuthFlowInfo> Flows => Array.AsReadOnly(_requirement.GetProperty("credential").TryGetProperty("flows",out var flows)?flows.EnumerateArray().Select(f=>new OAuthFlowInfo(f)).ToArray():Array.Empty<OAuthFlowInfo>());
    /// <summary>Declared OIDC discovery URL; the SDK does not fetch it.</summary>
    public string? DiscoveryUrl => ProtocolRuntime.LocatedString(_requirement.GetProperty("credential"),"discovery_url");
    /// <summary>Declared OAuth metadata URL; the SDK does not fetch it.</summary>
    public string? MetadataUrl => ProtocolRuntime.LocatedString(_requirement.GetProperty("credential"),"metadata_url");
}
/// <summary>A server variable's source default and optional allowed values.</summary>
public sealed class ServerVariableInfo
{
    private readonly JsonElement _data;
    internal ServerVariableInfo(JsonElement data) { _data=data; }
    /// <summary>Variable name.</summary>
    public string Name => _data.GetProperty("name").GetString()!;
    /// <summary>Source-declared default.</summary>
    public string Default => _data.GetProperty("default").GetProperty("value").GetString()!;
    /// <summary>Optional source enum.</summary>
    public IReadOnlyList<string>? Values => _data.GetProperty("values").ValueKind==JsonValueKind.Array?Array.AsReadOnly(_data.GetProperty("values").EnumerateArray().Select(v=>v.GetProperty("value").GetString()!).ToArray()):null;
}
/// <summary>A declared server choice, preserving its template and variables.</summary>
public sealed class ServerInfo
{
    private readonly JsonElement _data;
    internal ServerInfo(JsonElement data) { _data=data; }
    /// <summary>Physical declaration or default origin, retaining its source pointer.</summary>
    public string Source => ProtocolRuntime.Source(_data.GetProperty("source").ValueKind == JsonValueKind.Null ? _data.GetProperty("default_from") : _data.GetProperty("source").GetProperty("terminal"));
    /// <summary>Physical retrieval document URL. Requested aliases and logical names do not replace it.</summary>
    public string DocumentUrl => _data.GetProperty("document_base").GetProperty("source").GetProperty("document").GetString()!;
    /// <summary>Physical document-root source and pointer.</summary>
    public string DocumentSource => ProtocolRuntime.Source(_data.GetProperty("document_base"));
    /// <summary>The API URL's base category.</summary>
    public ApiUrlBase UrlBase => ApiUrlBase.ServerDocument;
    /// <summary>Logical resource context for an explicit declaration, separate from DocumentUrl.</summary>
    public ResourceInfo? Resource => _data.GetProperty("source").ValueKind == JsonValueKind.Null ? null : ProtocolRuntime.Resource(_data.GetProperty("source"),"terminal_resource");
    /// <summary>Resolve the source template using its physical document or an explicit HTTP(S) document override. No request or acquisition occurs.</summary>
    public string ResolveUrl(IReadOnlyDictionary<string,string>? variables = null, string? documentUrl = null) => ServerRuntime.Resolve(_data, variables, documentUrl);
    /// <summary>Original URL template.</summary>
    public string Template => _data.GetProperty("template").GetString()!;
    /// <summary>Optional source description.</summary>
    public string? Description => ProtocolRuntime.LocatedString(_data,"description");
    /// <summary>Source variable declarations.</summary>
    public IReadOnlyList<ServerVariableInfo> Variables => Array.AsReadOnly(_data.GetProperty("variables").EnumerateArray().Select(v=>new ServerVariableInfo(v)).ToArray());
}
/// <summary>Inert response Link metadata. No linked operation is selected or invoked.</summary>
public sealed class ResponseLinkInfo
{
    private readonly JsonElement _data;
    internal ResponseLinkInfo(JsonElement data) { _data=data; }
    /// <summary>Declared link name.</summary>
    public string Name => _data.GetProperty("name").GetString()!;
    /// <summary>Original link definition.</summary>
    public string Source => ProtocolRuntime.Source(_data.GetProperty("source").GetProperty("terminal"));
    /// <summary>operation-id or operation-ref.</summary>
    public string TargetKind => _data.GetProperty("target").GetProperty("kind").GetString()!;
    /// <summary>Declared target text.</summary>
    public string Target => _data.GetProperty("target").GetProperty("value").GetProperty("value").GetString()!;
    /// <summary>Literal or expression values remain exact JSON metadata.</summary>
    public IReadOnlyDictionary<string,JsonElement> Parameters => new ReadOnlyDictionary<string,JsonElement>(_data.GetProperty("parameters").EnumerateObject().ToDictionary(p=>p.Name,p=>p.Value.GetProperty("value").Clone(),StringComparer.Ordinal));
    /// <summary>Optional literal or expression request body.</summary>
    public Optional<JsonElement> RequestBody => _data.GetProperty("request_body").ValueKind==JsonValueKind.Null?default:Optional<JsonElement>.Present(_data.GetProperty("request_body").GetProperty("value").Clone());
    /// <summary>Optional link-local server metadata.</summary>
    public ServerInfo? Server => _data.GetProperty("server").ValueKind==JsonValueKind.Null?null:new ServerInfo(_data.GetProperty("server"));
}
/// <summary>Source-backed discoverability metadata for an allocated client operation.</summary>
public sealed class OperationInfo
{
    private readonly JsonElement _data;
    internal OperationInfo(JsonElement data) { _data=data; }
    /// <summary>Exact HTTP method token.</summary>
    public string Method => _data.GetProperty("method").GetString()!;
    /// <summary>Original path template.</summary>
    public string Path => _data.GetProperty("path").GetString()!;
    /// <summary>Original operation location.</summary>
    public string Source => ProtocolRuntime.Source(_data.GetProperty("source").GetProperty("use_site"));
    /// <summary>Physical terminal operation definition, including its pointer.</summary>
    public string TerminalSource => ProtocolRuntime.Source(_data.GetProperty("source").GetProperty("terminal"));
    /// <summary>Logical use-site context, independent of physical Source.</summary>
    public ResourceInfo? UseSiteResource => ProtocolRuntime.Resource(_data.GetProperty("source"),"use_site_resource");
    /// <summary>Logical terminal context, independent of physical TerminalSource.</summary>
    public ResourceInfo? TerminalResource => ProtocolRuntime.Resource(_data.GetProperty("source"),"terminal_resource");
    /// <summary>Physical reference hops in their original order.</summary>
    public IReadOnlyList<string> References => Array.AsReadOnly(_data.GetProperty("source").GetProperty("references").EnumerateArray().Select(ProtocolRuntime.Source).ToArray());
    /// <summary>Logical contexts aligned one-for-one with References.</summary>
    public IReadOnlyList<ResourceInfo?> ReferenceResources => Array.AsReadOnly(_data.GetProperty("source").GetProperty("reference_resources").EnumerateArray().Select(v => v.ValueKind == JsonValueKind.Null ? null : new ResourceInfo(v)).ToArray());
    /// <summary>Ordered effective server choices.</summary>
    public IReadOnlyList<ServerInfo> Servers => Array.AsReadOnly(_data.GetProperty("servers").GetProperty("candidates").EnumerateArray().Select(v=>new ServerInfo(v)).ToArray());
}

internal static class ProtocolRuntime
{
    internal static ResourceInfo? Resource(JsonElement provenance,string name) => provenance.TryGetProperty(name,out var value) && value.ValueKind == JsonValueKind.Object ? new ResourceInfo(value) : null;
    internal static string Source(JsonElement location)
    {
        var source=location.TryGetProperty("source",out var nested)?nested:location;
        return source.GetProperty("document").GetString()+"#"+source.GetProperty("pointer").GetString();
    }
    internal static string? LocatedString(JsonElement value,string name) => value.TryGetProperty(name,out var field)&&field.ValueKind==JsonValueKind.Object?field.GetProperty("value").GetString():null;
    internal static int Root(JsonElement codec)
    {
        var id=codec.GetProperty("schema").GetProperty("id");
        foreach(var root in ValidationProgram.Data.GetProperty("roots").EnumerateArray())
            if(root.GetProperty("source").GetProperty("document").GetString()==id.GetProperty("document").GetString()&&root.GetProperty("source").GetProperty("pointer").GetString()==id.GetProperty("pointer").GetString()) return root.GetProperty("target").GetInt32();
        throw new CodecException(CodecErrorKind.EvaluationFailure,"Protocol codec root was not compiled");
    }
    internal static string ScalarFor(JsonElement codec)
    {
        var seen=new HashSet<int>();var pending=new Stack<int>();pending.Push(Root(codec));
        while(pending.Count!=0){var i=pending.Pop();if(!seen.Add(i))continue;foreach(var check in ValidationProgram.Data.GetProperty("nodes")[i].GetProperty("checks").EnumerateArray()){
            if(check.GetProperty("op").GetString()=="ref")pending.Push(check.GetProperty("target").GetInt32());
            if(check.GetProperty("op").GetString()=="type")foreach(var t in check.GetProperty("types").EnumerateArray())if(t.GetString() is "string" or "boolean" or "integer" or "number")return t.GetString()!;
        }}
        throw new CodecException(CodecErrorKind.EvaluationFailure,"Text codec has no admitted scalar domain");
    }
    internal static byte[] EncodeJson(JsonElement value)
    {
        using var output=new LimitedStream();using var writer=new Utf8JsonWriter(output);var context=new ConversionContext();JsonRuntime.WriteElement(writer,value,context,"");writer.Flush();context.Spend((int)output.Length,"");return output.ToArray();
    }
    internal static byte[] TextBytes(byte[] json) => JsonRuntime.Bytes(WireEncoding.Text(JsonRuntime.Parse(json)));
    internal static byte[] TextJson(byte[] bytes,JsonElement representation) => WireEncoding.ScalarJson(JsonRuntime.Utf8.GetString(bytes),representation.GetProperty("scalar").GetString()!);
    internal static string SelectServer(JsonElement op, ClientOptions options, RequestOptions? request)
    {
        return ServerRuntime.Select(op, options, request);
    }
}

internal static class MediaRuntime
{
    internal static bool IsJson(JsonElement media) => media.GetProperty("range").TryGetProperty("subtype",out var subtype)&&(subtype.GetString()!.EndsWith("+json",StringComparison.Ordinal)||subtype.GetString()=="json"&&media.GetProperty("range").GetProperty("type_name").GetString()=="application");
    internal static MediaTypeHeaderValue Parse(string text)
    {
        if(text.Length>65_536||text.Any(c=>char.IsControl(c)&&c!='\t')||!MediaTypeHeaderValue.TryParse(text,out var parsed)||parsed.MediaType is null||parsed.MediaType.Contains('*'))throw new SdkException(SdkErrorKind.RequestRepresentation);
        var names=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var parameter in parsed.Parameters)if(!names.Add(parameter.Name)||parameter.Value is null)throw new SdkException(SdkErrorKind.RequestRepresentation);
        return parsed;
    }
    internal static string Unquote(string value) => value.StartsWith('"')&&value.EndsWith('"')?value[1..^1].Replace("\\\"","\"",StringComparison.Ordinal).Replace("\\\\","\\",StringComparison.Ordinal):value;
    internal static int Match(JsonElement media,string actual)
    {
        var parsed=Parse(actual);var split=parsed.MediaType!.Split('/');var best=-1;var rank=-1;
        for(var i=0;i<media.GetArrayLength();i++)
        {
            var type=media[i].GetProperty("media_type");var range=type.GetProperty("range");var kind=range.GetProperty("kind").GetString();
            if(kind!="any"&&!range.GetProperty("type_name").GetString()!.Equals(split[0],StringComparison.OrdinalIgnoreCase))continue;
            if(kind=="concrete"&&!range.GetProperty("subtype").GetString()!.Equals(split[1],StringComparison.OrdinalIgnoreCase))continue;
            var matches=true;var count=0;
            foreach(var parameter in type.GetProperty("parameters").EnumerateObject())
            {
                count++;var found=parsed.Parameters.FirstOrDefault(p=>p.Name.Equals(parameter.Name,StringComparison.OrdinalIgnoreCase));
                if(found is null||!string.Equals(Unquote(found.Value!),parameter.Value.GetString(),parameter.Name=="charset"?StringComparison.OrdinalIgnoreCase:StringComparison.Ordinal))matches=false;
            }
            var candidate=(kind=="concrete"?2:kind=="type"?1:0)*1_000+count;
            if(matches&&candidate>rank){best=i;rank=candidate;}
        }
        if(best<0)throw new SdkException(SdkErrorKind.UnexpectedResponse);
        var representation=media[best].GetProperty("representation").GetProperty("kind").GetString();
        if(representation is "text" or "stream" or "form" && parsed.CharSet is not null && !Unquote(parsed.CharSet).Equals("utf-8",StringComparison.OrdinalIgnoreCase))throw new SdkException(SdkErrorKind.UnexpectedResponse);
        return best;
    }
    internal static bool Forbidden(string method,int status) => method=="HEAD"||status is >=100 and <200 or 204 or 304;
    internal static int Response(JsonElement op,int status)
    {
        if(status<100||status>=600)throw new SdkException(SdkErrorKind.UnexpectedResponse);
        var responses=op.GetProperty("responses");var best=-1;var rank=0;
        for(var i=0;i<responses.GetArrayLength();i++)
        {
            var pattern=responses[i].GetProperty("status");var kind=pattern.GetProperty("kind").GetString();
            var candidate=kind=="exact"&&pattern.GetProperty("value").GetInt32()==status?3:kind=="range"&&pattern.GetProperty("value").GetInt32()==status/100?2:kind=="default"?1:0;
            if(candidate>rank){best=i;rank=candidate;}
        }
        return best;
    }
}
