// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.Text.Json;

namespace __NAMESPACE__;

// The v3 evaluator composes the frozen scoped instruction implementation with
// this resource context. Metadata is checked and cloned before any evaluation.
internal sealed partial class ValidationSession
{
    private readonly JsonElement _resourceData;
    private readonly int[] _nodeResources;
    private readonly List<int> _resourceStack = new();
    private readonly HashSet<int> _enteredResources = new();
    private readonly Dictionary<(int Context, int Resource), int> _contexts = new();
    private int _resourceContext;

    private int EnterResource(int resource, string at, string path)
    {
        if (_enteredResources.Contains(resource)) return -1;
        Spend(at, path);
        var previous = _resourceContext;
        // Dictionary equality retains the exact ordered prefix and next resource.
        // A hash collision cannot identify distinct contexts as the same cycle.
        if (!_contexts.TryGetValue((previous, resource), out var next))
        {
            next = _contexts.Count + 1;
            _contexts.Add((previous, resource), next);
        }
        _resourceContext = next;
        _enteredResources.Add(resource);
        _resourceStack.Add(resource);
        return previous;
    }
    private void LeaveResource(int previous)
    {
        if (previous < 0) return;
        var last = _resourceStack.Count - 1;
        _enteredResources.Remove(_resourceStack[last]);
        _resourceStack.RemoveAt(last);
        _resourceContext = previous;
    }
    private int DynamicTarget(JsonElement check, string at, string path)
    {
        var initial = check.GetProperty("target").GetInt32();
        var anchor = check.GetProperty("anchor");
        // Empty, pointer and static-anchor fallback modes do not perform lookup.
        if (anchor.ValueKind == JsonValueKind.Null) return initial;
        var name = anchor.GetString()!;
        var resources = _resourceData.GetProperty("resources");
        // The initial target's resource is not entered before the lookup. Only
        // resources entered on this evaluation path participate, outermost first.
        foreach (var resource in _resourceStack)
        {
            Spend(at, path);
            foreach (var binding in resources[resource].GetProperty("dynamicAnchors").EnumerateArray())
            {
                Spend(at, path);
                if (binding[0].GetString() == name) return binding[2].GetInt32();
            }
        }
        return initial;
    }
}
