// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.Globalization;
using global::System.Linq;
using global::System.Text;
using global::System.Text.Json;

namespace __NAMESPACE__;

// The v2 executable profile. Emission selects this asset only for a checked v2
// closure; the frozen v1 evaluator is a separate asset. No raw schema is executed.
internal sealed class ValidationSession
{
    private readonly JsonElement _nodes;
    private readonly HashSet<int> _roots = new();
    private readonly HashSet<(int, Instance)> _active = new();
    private readonly int _maxDepth;
    private readonly int _maxNumberBytes;
    private int _steps;
    private int _equalities;
    private CodecException? _first;

    internal ValidationSession() : this(ValidationProgram.Data) { }
    internal ValidationSession(JsonElement program)
    {
        ValidationProgramGuard.Check(program);
        // A caller-owned JsonDocument may be disposed as soon as this returns.
        _nodes = program.GetProperty("nodes").Clone();
        foreach (var root in program.GetProperty("roots").EnumerateArray()) _roots.Add(root.GetProperty("target").GetInt32());
        var limits = program.GetProperty("limits");
        _maxDepth = limits.GetProperty("maxDepth").GetInt32();
        _maxNumberBytes = limits.GetProperty("maxNumberBytes").GetInt32();
        _steps = limits.GetProperty("maxEvaluationSteps").GetInt32();
        _equalities = limits.GetProperty("maxEqualitySteps").GetInt32();
    }

    private static string Source(JsonElement at) => at.GetProperty("document").GetString() + "#" + at.GetProperty("pointer").GetString();
    private static string Child(string source, string name) => JsonRuntime.Child(source, name);
    private static CodecException Failure(string at, string path, string message) => new(CodecErrorKind.EvaluationFailure, message, at, path);
    private void Spend(string at, string path)
    {
        if (_steps == 0) throw Failure(at, path, "Schema evaluation work budget exhausted");
        _steps--;
    }
    private bool Mismatch(string at, string path, string message)
    {
        // The public codec reports its first mismatch. Reporting never terminates
        // evaluation: later work/numeric/equality failures must still win.
        _first ??= new CodecException(CodecErrorKind.InvalidValue, message, at, path);
        return false;
    }
    private ExactNumber Number(string token, string at, string path)
    {
        if (token.Length > _maxNumberBytes) throw Failure(at, path, "Numeric operand byte budget exhausted");
        return ExactNumber.Parse(token);
    }
    private ExactNumber Number(Instance instance, string at, string path) =>
        instance.Number ??= Number(instance.Value.GetRawText(), at, path);

    internal void Check(int root, JsonElement value, string path)
    {
        _first = null;
        Selected(root, path);
        if (!Evaluate(root, new Instance(value), path, 0).Valid)
            throw _first ?? Failure(Source(_nodes[root].GetProperty("source")), path, "Invalid value had no finding");
    }
    internal bool Matches(int root, JsonElement value, string path)
    {
        Selected(root, path);
        return Trial(root, new Instance(value), path, 0).Valid;
    }
    private void Selected(int root, string path)
    {
        if (!_roots.Contains(root)) throw Failure("", path, "Validation root was not selected");
    }
    private Evaluated Trial(int target, Instance instance, string path, int depth)
    {
        var saved = _first;
        _first = null;
        try { return Evaluate(target, instance, path, depth); }
        finally { _first = saved; }
    }
    private Evaluated Evaluate(int index, Instance instance, string path, int depth)
    {
        var node = _nodes[index];
        var source = Source(node.GetProperty("source"));
        Spend(source, path);
        if (depth >= _maxDepth) throw Failure(source, path, "Schema evaluation depth budget exhausted");
        if (!_active.Add((index, instance))) throw Failure(source, path, "Nonproductive recursive schema evaluation");
        try
        {
            var local = new Annotations();
            var valid = true;
            foreach (var check in node.GetProperty("checks").EnumerateArray())
            {
                var at = Source(check.GetProperty("source"));
                Spend(at, path);
                valid = Apply(node, check, instance, path, depth, local, at) & valid;
            }
            return new Evaluated(valid, valid ? local : new Annotations());
        }
        finally { _active.Remove((index, instance)); }
    }
    private void Merge(Annotations into, Annotations from, string at, string path)
    {
        foreach (var name in from.Properties) { Spend(at, path); into.Properties.Add(name); }
        foreach (var index in from.Items) { Spend(at, path); into.Items.Add(index); }
    }
    private bool Apply(JsonElement node, JsonElement check, Instance instance, string path, int depth, Annotations local, string at)
    {
        var op = check.GetProperty("op").GetString()!;
        var produced = new Annotations();
        var valid = true;
        switch (op)
        {
            case "ref":
                var reference = Evaluate(check.GetProperty("target").GetInt32(), instance, path, depth + 1);
                valid = reference.Valid; produced = reference.Annotations;
                break;
            case "allOf": case "anyOf": case "oneOf":
                valid = Alternatives(check, instance, path, depth, produced, at, op);
                break;
            case "not":
                valid = !Trial(check.GetProperty("target").GetInt32(), instance, path, depth + 1).Valid;
                if (!valid) Mismatch(at, path, "Negated schema accepted the value");
                break;
            case "if":
                var condition = Trial(check.GetProperty("condition").GetInt32(), instance, path, depth + 1);
                var branch = check.GetProperty(condition.Valid ? "thenTarget" : "elseTarget");
                if (condition.Valid) Merge(local, condition.Annotations, at, path);
                if (branch.ValueKind != JsonValueKind.Null)
                {
                    var selected = Evaluate(branch.GetInt32(), instance, path, depth + 1);
                    valid = selected.Valid; produced = selected.Annotations;
                }
                break;
            case "dependentRequired":
                valid = DependentRequired(check, instance, path, at);
                break;
            case "dependentSchemas":
                valid = DependentSchemas(check, instance, path, depth, produced, at);
                break;
            case "contains":
                valid = Contains(node, check, instance, path, depth, local, at);
                break;
            case "properties":
                if (instance.Value.ValueKind == JsonValueKind.Object)
                    foreach (var property in check.GetProperty("properties").EnumerateArray())
                    {
                        Spend(at, path); var name = property.GetProperty("name").GetString()!;
                        if (instance.Properties.TryGetValue(name, out var child))
                        {
                            valid = Evaluate(property.GetProperty("target").GetInt32(), child, Child(path, name), depth + 1).Valid & valid;
                            produced.Properties.Add(name);
                        }
                    }
                break;
            case "patternProperties":
                valid = PatternProperties(check, instance, path, depth, produced, at);
                break;
            case "additionalProperties": case "additionalPropertiesWithPatterns":
                valid = Additional(node, check, instance, path, depth, produced, at, op == "additionalPropertiesWithPatterns");
                break;
            case "propertyNames":
                if (instance.Value.ValueKind == JsonValueKind.Object)
                    foreach (var (name, _) in instance.Properties)
                    {
                        Spend(at, path);
                        // Key text is a fresh instance, distinct from the member's
                        // value even though both report the same instance pointer.
                        var key = new Instance(JsonSerializer.SerializeToElement(name));
                        valid = Evaluate(check.GetProperty("target").GetInt32(), key, Child(path, name), depth + 1).Valid & valid;
                    }
                break;
            case "items": case "prefixItems":
                if (instance.Value.ValueKind == JsonValueKind.Array)
                {
                    var prefix = op == "prefixItems";
                    var targets = prefix ? check.GetProperty("targets") : default;
                    var start = prefix ? 0 : check.GetProperty("start").GetInt32();
                    var end = prefix ? Math.Min(targets.GetArrayLength(), instance.Value.GetArrayLength()) : instance.Value.GetArrayLength();
                    for (var i = start; i < end; i++)
                    {
                        Spend(at, path);
                        valid = Evaluate(prefix ? targets[i].GetInt32() : check.GetProperty("target").GetInt32(), instance.Item(i), Child(path, i.ToString(CultureInfo.InvariantCulture)), depth + 1).Valid & valid;
                        produced.Items.Add(i);
                    }
                }
                break;
            case "unevaluatedProperties":
                if (instance.Value.ValueKind == JsonValueKind.Object)
                    foreach (var (name, child) in instance.Properties)
                    {
                        Spend(at, path);
                        if (!local.Properties.Contains(name))
                        {
                            valid = Evaluate(check.GetProperty("target").GetInt32(), child, Child(path, name), depth + 1).Valid & valid;
                            produced.Properties.Add(name);
                        }
                    }
                break;
            case "unevaluatedItems":
                if (instance.Value.ValueKind == JsonValueKind.Array)
                    for (var i = 0; i < instance.Value.GetArrayLength(); i++)
                    {
                        Spend(at, path);
                        if (!local.Items.Contains(i))
                        {
                            valid = Evaluate(check.GetProperty("target").GetInt32(), instance.Item(i), Child(path, i.ToString(CultureInfo.InvariantCulture)), depth + 1).Valid & valid;
                            produced.Items.Add(i);
                        }
                    }
                break;
            default: valid = Scalar(check, instance, path, at); break;
        }
        if (valid) Merge(local, produced, at, path);
        return valid;
    }
    private bool Alternatives(JsonElement check, Instance instance, string path, int depth, Annotations produced, string at, string op)
    {
        var targets = check.GetProperty("targets");
        var passing = new List<Annotations>();
        foreach (var target in targets.EnumerateArray())
        {
            Spend(at, path);
            var result = op == "allOf" ? Evaluate(target.GetInt32(), instance, path, depth + 1) : Trial(target.GetInt32(), instance, path, depth + 1);
            if (result.Valid) passing.Add(result.Annotations);
        }
        var valid = op == "allOf" ? passing.Count == targets.GetArrayLength() : op == "anyOf" ? passing.Count != 0 : passing.Count == 1;
        if (valid) foreach (var annotations in passing) Merge(produced, annotations, at, path);
        else if (op != "allOf") Mismatch(at, path, op + " branch count rejected the value");
        return valid;
    }
    private bool DependentRequired(JsonElement check, Instance instance, string path, string at)
    {
        var valid = true;
        if (instance.Value.ValueKind == JsonValueKind.Object)
            foreach (var dependency in check.GetProperty("dependencies").EnumerateArray())
            {
                Spend(at, path); var trigger = dependency[0].GetString()!;
                if (instance.Properties.ContainsKey(trigger))
                    foreach (var required in dependency[1].EnumerateArray())
                    {
                        Spend(at, path);
                        if (!instance.Properties.ContainsKey(required.GetString()!)) valid = Mismatch(Child(at, trigger), path, "A dependent required property is absent");
                    }
            }
        return valid;
    }
    private bool DependentSchemas(JsonElement check, Instance instance, string path, int depth, Annotations produced, string at)
    {
        var valid = true;
        var passing = new List<Annotations>();
        if (instance.Value.ValueKind == JsonValueKind.Object)
            foreach (var dependency in check.GetProperty("dependencies").EnumerateArray())
            {
                Spend(at, path);
                if (instance.Properties.ContainsKey(dependency.GetProperty("name").GetString()!))
                {
                    var result = Evaluate(dependency.GetProperty("target").GetInt32(), instance, path, depth + 1);
                    valid = result.Valid & valid;
                    if (result.Valid) passing.Add(result.Annotations);
                }
            }
        if (valid) foreach (var annotations in passing) Merge(produced, annotations, at, path);
        return valid;
    }
    private bool Contains(JsonElement node, JsonElement check, Instance instance, string path, int depth, Annotations local, string at)
    {
        if (instance.Value.ValueKind != JsonValueKind.Array) return true;
        var matched = new Annotations();
        for (var i = 0; i < instance.Value.GetArrayLength(); i++)
        {
            Spend(at, path);
            if (Trial(check.GetProperty("target").GetInt32(), instance.Item(i), Child(path, i.ToString(CultureInfo.InvariantCulture)), depth + 1).Valid) matched.Items.Add(i);
        }
        var minimum = check.GetProperty("minimum"); var maximum = check.GetProperty("maximum");
        var nodeSource = Source(node.GetProperty("source"));
        // Implicit one and observed cardinality are semantic values, not source
        // numeric operands subject to maxNumberBytes.
        var min = minimum.ValueKind == JsonValueKind.Null ? ExactNumber.Parse("1") : Number(minimum.GetString()!, Child(nodeSource, "minContains"), path);
        var count = ExactNumber.Parse(matched.Items.Count.ToString(CultureInfo.InvariantCulture));
        if (matched.Items.Count != 0 || min.Sign == 0) Merge(local, matched, at, path);
        var lower = count.Compare(min) >= 0;
        var upper = maximum.ValueKind == JsonValueKind.Null || count.Compare(Number(maximum.GetString()!, Child(nodeSource, "maxContains"), path)) <= 0;
        if (!lower) Mismatch(minimum.ValueKind == JsonValueKind.Null ? at : Child(nodeSource, "minContains"), path, "Too few contains matches");
        if (!upper) Mismatch(Child(nodeSource, "maxContains"), path, "Too many contains matches");
        return lower && upper;
    }
    private bool PatternProperties(JsonElement check, Instance instance, string path, int depth, Annotations produced, string at)
    {
        var valid = true;
        if (instance.Value.ValueKind == JsonValueKind.Object)
            foreach (var (name, child) in instance.Properties)
            {
                Spend(at, path);
                foreach (var pattern in check.GetProperty("patterns").EnumerateArray())
                {
                    Spend(at, path);
                    if (Pattern(pattern[1], name, at, path))
                    {
                        valid = Evaluate(pattern[2].GetInt32(), child, Child(path, name), depth + 1).Valid & valid;
                        produced.Properties.Add(name);
                    }
                }
            }
        return valid;
    }
    private bool Additional(JsonElement node, JsonElement check, Instance instance, string path, int depth, Annotations produced, string at, bool patterned)
    {
        if (instance.Value.ValueKind != JsonValueKind.Object) return true;
        var declared = check.GetProperty("declared").EnumerateArray().Select(v => v.GetString()!).ToHashSet(StringComparer.Ordinal);
        var patterns = patterned ? node.GetProperty("checks").EnumerateArray().Single(c => c.GetProperty("op").GetString() == "patternProperties").GetProperty("patterns") : default;
        var valid = true;
        foreach (var (name, child) in instance.Properties)
        {
            Spend(at, path);
            if (declared.Contains(name)) continue;
            var excluded = false;
            if (patterned) foreach (var pattern in patterns.EnumerateArray())
            {
                Spend(at, path);
                if (Pattern(pattern[1], name, at, path)) { excluded = true; break; }
            }
            if (excluded) continue;
            valid = Evaluate(check.GetProperty("target").GetInt32(), child, Child(path, name), depth + 1).Valid & valid;
            produced.Properties.Add(name);
        }
        return valid;
    }
    private static string Kind(JsonElement value) => value.ValueKind switch
    {
        JsonValueKind.Null => "null", JsonValueKind.True or JsonValueKind.False => "boolean",
        JsonValueKind.Number => "number", JsonValueKind.String => "string", JsonValueKind.Array => "array",
        JsonValueKind.Object => "object", _ => "undefined"
    };
    private bool Scalar(JsonElement check, Instance instance, string path, string at)
    {
        var value = instance.Value; var kind = Kind(value); var op = check.GetProperty("op").GetString();
        var valid = true;
        switch (op)
        {
            case "always": valid = check.GetProperty("value").GetBoolean(); break;
            case "type":
                var types = check.GetProperty("types").EnumerateArray().Select(v => v.GetString()).ToArray();
                valid = types.Contains(kind) || (kind == "number" && types.Contains("integer") && Number(instance, at, path).Integral);
                break;
            case "required":
                if (kind == "object") foreach (var name in check.GetProperty("names").EnumerateArray())
                { Spend(at, path); if (!instance.Properties.ContainsKey(name.GetString()!)) valid = Mismatch(at, path, "A required property is absent"); }
                break;
            case "bound":
                if (kind == "number")
                {
                    var order = Number(instance, at, path).Compare(Number(check.GetProperty("value").GetString()!, at, path));
                    var maximum = check.GetProperty("maximum").GetBoolean(); var exclusive = check.GetProperty("exclusive").GetBoolean();
                    valid = maximum ? (exclusive ? order < 0 : order <= 0) : (exclusive ? order > 0 : order >= 0);
                }
                break;
            case "multipleOf":
                if (kind == "number") valid = Number(instance, at, path).MultipleOf(Number(check.GetProperty("value").GetString()!, at, path), static _ => { });
                break;
            case "count":
                if (kind == check.GetProperty("target").GetString())
                {
                    var count = kind == "array" ? value.GetArrayLength() : kind == "object" ? instance.Properties.Count : value.GetString()!.EnumerateRunes().Count();
                    var comparison = ExactNumber.Parse(count.ToString(CultureInfo.InvariantCulture)).Compare(Number(check.GetProperty("value").GetString()!, at, path));
                    valid = check.GetProperty("maximum").GetBoolean() ? comparison <= 0 : comparison >= 0;
                }
                break;
            case "const": valid = Equal(value, check.GetProperty("value"), at, path); break;
            case "enum":
                valid = false;
                foreach (var candidate in check.GetProperty("values").EnumerateArray())
                { Spend(at, path); if (Equal(value, candidate, at, path)) { valid = true; break; } }
                break;
            case "uniqueItems":
                if (kind == "array") for (var i = 0; i < value.GetArrayLength() && valid; i++)
                {
                    Spend(at, path);
                    for (var j = 0; j < i; j++)
                    { Spend(at, path); if (Equal(value[i], value[j], at, path)) { valid = false; break; } }
                }
                break;
            case "pattern": if (kind == "string") valid = Pattern(check.GetProperty("program"), value.GetString()!, at, path); break;
            default: throw Failure(at, path, "Unknown validation opcode: " + op);
        }
        return valid || Mismatch(at, path, op + " assertion rejected the value");
    }
    private bool Equal(JsonElement left, JsonElement right, string at, string path)
    {
        var pending = new Stack<(JsonElement, JsonElement, int)>(); pending.Push((left, right, 0));
        while (pending.Count != 0)
        {
            var (a, b, depth) = pending.Pop();
            if (_equalities == 0) throw Failure(at, path, "Structural equality work budget exhausted");
            _equalities--;
            if (depth > _maxDepth) throw Failure(at, path, "Structural equality depth budget exhausted");
            var kind = Kind(a); if (kind != Kind(b)) return false;
            switch (kind)
            {
                case "number": if (Number(a.GetRawText(), at, path).Compare(Number(b.GetRawText(), at, path)) != 0) return false; break;
                case "string": if (a.GetString() != b.GetString()) return false; break;
                case "boolean": if (a.GetBoolean() != b.GetBoolean()) return false; break;
                case "null": break;
                case "array":
                    if (a.GetArrayLength() != b.GetArrayLength()) return false;
                    if (a.GetArrayLength() > _equalities - pending.Count) throw Failure(at, path, "Structural equality work budget exhausted");
                    for (var i = a.GetArrayLength() - 1; i >= 0; i--) pending.Push((a[i], b[i], depth + 1));
                    break;
                case "object":
                    var leftFields = a.EnumerateObject().OrderBy(p => p.Name, ScalarOrder.Instance).ToArray();
                    var rightFields = b.EnumerateObject().ToArray();
                    if (leftFields.Length != rightFields.Length) return false;
                    if (leftFields.Length > _equalities - pending.Count) throw Failure(at, path, "Structural equality work budget exhausted");
                    var map = new Dictionary<string, JsonElement>(StringComparer.Ordinal);
                    foreach (var property in rightFields) if (!map.TryAdd(property.Name, property.Value)) throw Failure(at, path, "Duplicate decoded equality key");
                    var seen = new HashSet<string>(StringComparer.Ordinal);
                    for (var i = leftFields.Length - 1; i >= 0; i--)
                    {
                        var property = leftFields[i];
                        if (!seen.Add(property.Name)) throw Failure(at, path, "Duplicate decoded equality key");
                        if (!map.TryGetValue(property.Name, out var other)) return false;
                        pending.Push((property.Value, other, depth + 1));
                    }
                    break;
                default: throw Failure(at, path, "Undefined value in structural equality");
            }
        }
        return true;
    }
    private bool Pattern(JsonElement program, string text, string at, string path)
    {
        var states = program.GetProperty("states");
        var seen = new int[states.GetArrayLength()];
        var stack = new Stack<int>(); var active = new List<int>(); var seeds = new List<int>(); var next = new List<int>();
        var epoch = 0; var offset = 0; var scalars = text.EnumerateRunes();
        void Enqueue(int index)
        { Spend(at, path); if (seen[index] != epoch) { seen[index] = epoch; stack.Push(index); } }
        while (true)
        {
            Spend(at, path); epoch++;
            stack.Clear(); active.Clear();
            Enqueue(program.GetProperty("start").GetInt32());
            foreach (var seed in seeds) Enqueue(seed);
            seeds.Clear();
            while (stack.Count != 0)
            {
                Spend(at, path); var index = stack.Pop(); var state = states[index];
                switch (state.GetProperty("op").GetString())
                {
                    case "match": return true;
                    case "split": Enqueue(state.GetProperty("second").GetInt32()); Enqueue(state.GetProperty("first").GetInt32()); break;
                    case "jump": Enqueue(state.GetProperty("target").GetInt32()); break;
                    case "start": if (offset == 0) Enqueue(state.GetProperty("target").GetInt32()); break;
                    case "end": if (offset == text.Length) Enqueue(state.GetProperty("target").GetInt32()); break;
                    case "char": active.Add(index); break;
                }
            }
            if (!scalars.MoveNext()) return false;
            var scalar = scalars.Current; offset += scalar.Utf16SequenceLength;
            next.Clear();
            foreach (var index in active)
            {
                var state = states[index];
                foreach (var range in state.GetProperty("ranges").EnumerateArray())
                {
                    Spend(at, path);
                    if (scalar.Value < range[0].GetInt32()) break;
                    if (scalar.Value <= range[1].GetInt32()) { next.Add(state.GetProperty("target").GetInt32()); break; }
                }
            }
            (seeds, next) = (next, seeds);
        }
    }

    private sealed class Instance(JsonElement value)
    {
        internal readonly JsonElement Value = value;
        internal ExactNumber? Number;
        private SortedDictionary<string, Instance>? _properties;
        private Instance?[]? _items;
        internal SortedDictionary<string, Instance> Properties
        {
            get
            {
                if (_properties is null)
                {
                    _properties = new(ScalarOrder.Instance);
                    foreach (var property in Value.EnumerateObject()) _properties.Add(property.Name, new Instance(property.Value));
                }
                return _properties;
            }
        }
        internal Instance Item(int index)
        { _items ??= new Instance[Value.GetArrayLength()]; return _items[index] ??= new Instance(Value[index]); }
    }
    private sealed class Annotations
    {
        internal readonly SortedSet<string> Properties = new(ScalarOrder.Instance);
        internal readonly SortedSet<int> Items = new();
    }
    private readonly record struct Evaluated(bool Valid, Annotations Annotations);
    private sealed class ScalarOrder : IComparer<string>
    {
        internal static readonly ScalarOrder Instance = new();
        public int Compare(string? left, string? right)
        {
            if (ReferenceEquals(left, right)) return 0;
            if (left is null) return -1;
            if (right is null) return 1;
            var a = left.EnumerateRunes(); var b = right.EnumerateRunes();
            while (true)
            {
                var moreA = a.MoveNext(); var moreB = b.MoveNext();
                if (!moreA || !moreB) return moreA.CompareTo(moreB);
                var order = a.Current.Value.CompareTo(b.Current.Value);
                if (order != 0) return order;
            }
        }
    }
}
