// <auto-generated />
#nullable enable
using global::System;
using global::System.Collections.Generic;
using global::System.Linq;
using global::System.Text;
using global::System.Text.Json;

namespace __NAMESPACE__;

// Checks executable descriptors, never source schemas. Generation also calls
// OwnedProgram.check(); this guard keeps malformed native inputs fail-closed.
internal sealed class ValidationProgramGuard
{
    private JsonElement _nodes;
    private int _numberBytes;
    private int _work = 1_000_000;
    private string _at = "";
    internal static void Check(JsonElement program)
    {
        var guard = new ValidationProgramGuard();
        try { guard.Program(program); }
        catch (CodecException error) when (error.Kind != CodecErrorKind.EvaluationFailure)
        { throw Error(guard._at, "Malformed validation operand: " + error.Message); }
        catch (Exception error) when (error is JsonException or InvalidOperationException or KeyNotFoundException or ArgumentException or FormatException or OverflowException)
        { throw Error(guard._at, "Malformed validation program operand"); }
    }
    private static CodecException Error(string at, string message) => new(CodecErrorKind.EvaluationFailure, message, at);
    private void Need(bool condition, string message)
    { if (!condition) throw Error(_at, message); }
    private void Visit()
    { if (_work-- == 0) throw Error(_at, "Validation program admission work budget exhausted"); }
    private void Object(JsonElement value, params string[] fields)
    {
        Visit(); Need(value.ValueKind == JsonValueKind.Object, "Expected a descriptor object");
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var property in value.EnumerateObject())
            Need(fields.Contains(property.Name, StringComparer.Ordinal) && seen.Add(property.Name), "Unknown or duplicate descriptor member");
        Need(seen.Count == fields.Length, "Missing descriptor operand");
    }
    private JsonElement Array(JsonElement value)
    { Need(value.ValueKind == JsonValueKind.Array, "Expected an operand array"); return value; }
    private string Text(JsonElement value)
    { Need(value.ValueKind == JsonValueKind.String, "Expected a string operand"); return JsonRuntime.CheckedString(value.GetString(), ""); }
    private int Integer(JsonElement value, int maximum = int.MaxValue)
    { Need(value.ValueKind == JsonValueKind.Number && value.TryGetInt32(out _), "Expected a finite integer operand"); var number = value.GetInt32(); Need(number >= 0 && number <= maximum, "Integer operand is outside the native profile"); return number; }
    private string Source(JsonElement value)
    {
        Object(value, "document", "pointer");
        var document = Text(value.GetProperty("document")); var pointer = Text(value.GetProperty("pointer"));
        Need(Uri.TryCreate(document, UriKind.Absolute, out var uri) && uri.Fragment.Length == 0 && !document.Contains('#'), "Source document must be absolute and fragment-free");
        Need(pointer.Length == 0 || pointer[0] == '/', "Source requires an escaped JSON Pointer");
        for (var i = 0; i < pointer.Length; i++) if (pointer[i] == '~') Need(++i < pointer.Length && pointer[i] is '0' or '1', "Invalid JSON Pointer escape");
        return document + "#" + pointer;
    }
    private static string Child(string source, string name) => JsonRuntime.Child(source, name);
    private void Target(JsonElement value, string? expected = null)
    {
        var index = Integer(value); Need(index < _nodes.GetArrayLength(), "Target is outside the finite schema graph");
        if (expected is not null) Need(Source(_nodes[index].GetProperty("source")) == expected, "Target does not match its source child identity");
    }
    private HashSet<string> Names(JsonElement array)
    {
        var result = new HashSet<string>(StringComparer.Ordinal);
        foreach (var value in Array(array).EnumerateArray()) { Visit(); Need(result.Add(Text(value)), "Duplicate name operand"); }
        return result;
    }
    private ExactNumber Number(JsonElement value, bool count = false, bool positive = false)
    {
        var token = Text(value); Need(token.Length <= _numberBytes, "Numeric operand byte budget exhausted");
        JsonRuntime.CheckNumber(token); var number = ExactNumber.Parse(token);
        Need(!count || (number.Integral && number.Sign >= 0), "Count must be a nonnegative mathematical integer");
        Need(!positive || number.Sign > 0, "Divisor must be strictly positive");
        return number;
    }
    private void Program(JsonElement program)
    {
        var text = program.GetRawText();
        Need(text.Length <= JsonRuntime.MaxBytes && Encoding.UTF8.GetByteCount(text) <= JsonRuntime.MaxBytes, "Validation program exceeds 8 MiB");
        Object(program, "version", "profile", "roots", "nodes", "limits");
        Need(Text(program.GetProperty("version")) == "suspect.validation.experimental.v2" && Text(program.GetProperty("profile")) == "oas31-jsonschema202012-static-applicators", "Unsupported validation program version/profile");
        var limits = program.GetProperty("limits");
        Object(limits, "maxDepth", "maxErrors", "maxNumberBytes", "maxEqualitySteps", "maxEvaluationSteps");
        Integer(limits.GetProperty("maxDepth"), 128);
        Integer(limits.GetProperty("maxErrors"));
        _numberBytes = Integer(limits.GetProperty("maxNumberBytes"), 4096);
        Integer(limits.GetProperty("maxEqualitySteps"), 1_000_000);
        Integer(limits.GetProperty("maxEvaluationSteps"), 1_000_000);
        _nodes = Array(program.GetProperty("nodes"));
        Need(_nodes.GetArrayLength() <= 65_536, "Validation node limit exceeded");
        var sources = new HashSet<string>(StringComparer.Ordinal);
        foreach (var node in _nodes.EnumerateArray())
        {
            Object(node, "source", "checks"); _at = Source(node.GetProperty("source"));
            Need(sources.Add(_at), "Duplicate schema source identity");
        }
        foreach (var node in _nodes.EnumerateArray()) Node(node);
        sources.Clear();
        foreach (var root in Array(program.GetProperty("roots")).EnumerateArray())
        {
            Object(root, "source", "target"); _at = Source(root.GetProperty("source"));
            Need(sources.Add(_at), "Duplicate selected root"); Target(root.GetProperty("target"), _at);
        }
    }
    private void Node(JsonElement node)
    {
        var source = Source(node.GetProperty("source"));
        var checks = Array(node.GetProperty("checks"));
        var locations = new HashSet<string>(StringComparer.Ordinal);
        var properties = new HashSet<string>(StringComparer.Ordinal);
        HashSet<string>? declared = null;
        var prefixLength = 0; int? start = null;
        var patternCount = 0; var additionalPatterns = false; var tail = false;
        foreach (var check in checks.EnumerateArray())
        {
            Visit(); _at = Source(check.GetProperty("source"));
            var op = Text(check.GetProperty("op"));
            var unevaluated = op is "unevaluatedProperties" or "unevaluatedItems";
            Need(!tail || unevaluated, "Unevaluated checks must follow the other checks"); tail |= unevaluated;
            var keyword = op switch
            {
                "always" => null, "ref" => "$ref", "additionalPropertiesWithPatterns" => "additionalProperties",
                "bound" => check.GetProperty("maximum").GetBoolean() ? (check.GetProperty("exclusive").GetBoolean() ? "exclusiveMaximum" : "maximum") : (check.GetProperty("exclusive").GetBoolean() ? "exclusiveMinimum" : "minimum"),
                "count" => (Text(check.GetProperty("target")), check.GetProperty("maximum").GetBoolean()) switch
                { ("array", true) => "maxItems", ("array", false) => "minItems", ("object", true) => "maxProperties", ("object", false) => "minProperties", ("string", true) => "maxLength", ("string", false) => "minLength", _ => throw Error(_at, "Unknown count target") },
                "type" or "properties" or "additionalProperties" or "required" or "items" or "prefixItems" or "allOf" or "anyOf" or "oneOf" or "not" or "multipleOf" or "enum" or "const" or "uniqueItems" or "pattern" or "if" or "dependentRequired" or "dependentSchemas" or "contains" or "patternProperties" or "propertyNames" or "unevaluatedProperties" or "unevaluatedItems" => op,
                _ => throw Error(_at, "Unknown validation opcode")
            };
            var normalizedBound = op == "bound" && check.GetProperty("exclusive").GetBoolean() && _at == Child(source, check.GetProperty("maximum").GetBoolean() ? "maximum" : "minimum");
            Need((_at == (keyword is null ? source : Child(source, keyword)) || normalizedBound) && locations.Add(_at), "Check must uniquely identify its schema keyword");
            switch (op)
            {
                case "always": Object(check, "source", "op", "value"); _ = check.GetProperty("value").GetBoolean(); Need(checks.GetArrayLength() == 1, "Boolean schema must have one check"); break;
                case "type":
                    Object(check, "source", "op", "types"); var types = Names(check.GetProperty("types"));
                    Need(types.Count != 0 && types.All(t => t is "null" or "boolean" or "number" or "integer" or "string" or "object" or "array"), "Invalid type operands");
                    break;
                case "ref": Object(check, "source", "op", "target"); Target(check.GetProperty("target")); break;
                case "properties":
                    Object(check, "source", "op", "properties");
                    foreach (var field in Array(check.GetProperty("properties")).EnumerateArray())
                    { Object(field, "name", "target"); var name = Text(field.GetProperty("name")); Need(properties.Add(name), "Duplicate property name"); Target(field.GetProperty("target"), Child(_at, name)); }
                    break;
                case "additionalProperties": case "additionalPropertiesWithPatterns":
                    Object(check, "source", "op", "declared", "target");
                    declared = Names(check.GetProperty("declared")); additionalPatterns = op == "additionalPropertiesWithPatterns";
                    Target(check.GetProperty("target"), _at); break;
                case "required": Object(check, "source", "op", "names"); Names(check.GetProperty("names")); break;
                case "items": Object(check, "source", "op", "target", "start"); start = Integer(check.GetProperty("start")); Target(check.GetProperty("target"), _at); break;
                case "not": case "propertyNames": case "unevaluatedProperties": case "unevaluatedItems":
                    Object(check, "source", "op", "target"); Target(check.GetProperty("target"), _at); break;
                case "if":
                    Object(check, "source", "op", "condition", "thenTarget", "elseTarget"); Target(check.GetProperty("condition"), _at);
                    foreach (var branch in new[] { "then", "else" })
                    { var target = check.GetProperty(branch + "Target"); if (target.ValueKind != JsonValueKind.Null) Target(target, Child(source, branch)); }
                    break;
                case "dependentRequired":
                    Object(check, "source", "op", "dependencies"); var triggers = new HashSet<string>(StringComparer.Ordinal);
                    foreach (var dependency in Array(check.GetProperty("dependencies")).EnumerateArray())
                    { Need(Array(dependency).GetArrayLength() == 2, "Invalid dependentRequired tuple"); Need(triggers.Add(Text(dependency[0])), "Duplicate dependency trigger"); Names(dependency[1]); }
                    break;
                case "dependentSchemas":
                    Object(check, "source", "op", "dependencies"); var keys = new HashSet<string>(StringComparer.Ordinal);
                    foreach (var dependency in Array(check.GetProperty("dependencies")).EnumerateArray())
                    { Object(dependency, "name", "target"); var key = Text(dependency.GetProperty("name")); Need(keys.Add(key), "Duplicate dependency trigger"); Target(dependency.GetProperty("target"), Child(_at, key)); }
                    break;
                case "contains":
                    Object(check, "source", "op", "target", "minimum", "maximum"); Target(check.GetProperty("target"), _at);
                    var checkSource = _at;
                    foreach (var (operand, name) in new[] { ("minimum", "minContains"), ("maximum", "maxContains") })
                    { var bound = check.GetProperty(operand); if (bound.ValueKind != JsonValueKind.Null) { _at = Child(source, name); Number(bound, count: true); } }
                    _at = checkSource; break;
                case "patternProperties":
                    Object(check, "source", "op", "patterns"); var patterns = new HashSet<string>(StringComparer.Ordinal);
                    foreach (var pattern in Array(check.GetProperty("patterns")).EnumerateArray())
                    {
                        Need(Array(pattern).GetArrayLength() == 3, "Invalid patternProperties tuple"); var name = Text(pattern[0]);
                        Need(patterns.Add(name), "Duplicate property pattern"); Target(pattern[2], Child(_at, name)); Pattern(pattern[1]);
                    }
                    patternCount = patterns.Count; break;
                case "prefixItems": case "allOf": case "anyOf": case "oneOf":
                    Object(check, "source", "op", "targets"); var targets = Array(check.GetProperty("targets"));
                    Need(targets.GetArrayLength() != 0, "Applicator targets must be nonempty");
                    if (op == "prefixItems") prefixLength = targets.GetArrayLength();
                    for (var i = 0; i < targets.GetArrayLength(); i++) Target(targets[i], Child(_at, i.ToString(global::System.Globalization.CultureInfo.InvariantCulture)));
                    break;
                case "bound": Object(check, "source", "op", "value", "maximum", "exclusive"); Number(check.GetProperty("value")); break;
                case "multipleOf": Object(check, "source", "op", "value"); Number(check.GetProperty("value"), positive: true); break;
                case "count": Object(check, "source", "op", "value", "maximum", "target"); Number(check.GetProperty("value"), count: true); break;
                case "const": Object(check, "source", "op", "value"); break;
                case "enum": Object(check, "source", "op", "values"); Array(check.GetProperty("values")); break;
                case "uniqueItems": Object(check, "source", "op"); break;
                case "pattern": Object(check, "source", "op", "program"); Pattern(check.GetProperty("program")); break;
            }
        }
        _at = source;
        if (declared is not null)
        {
            _at = Child(source, "additionalProperties");
            Need(declared.SetEquals(properties), "Declared names do not match adjacent properties");
            Need(additionalPatterns == (patternCount != 0), "AdditionalProperties opcode does not match adjacent patterns");
        }
        if (start is not null) { _at = Child(source, "items"); Need(start == prefixLength, "Items start does not match adjacent prefix length"); }
    }
    private void Pattern(JsonElement pattern)
    {
        Object(pattern, "version", "start", "states");
        Need(Text(pattern.GetProperty("version")) == "suspect.pattern.experimental.v1", "Unknown pattern program version");
        var states = Array(pattern.GetProperty("states")); var count = states.GetArrayLength();
        Need(count > 0 && count <= 8192 && Integer(pattern.GetProperty("start")) < count, "Invalid finite pattern graph");
        var totalRanges = 0;
        void Edge(JsonElement value) => Need(Integer(value) < count, "Pattern target is outside graph");
        foreach (var state in states.EnumerateArray())
        {
            Visit();
            switch (Text(state.GetProperty("op")))
            {
                case "match": Object(state, "op"); break;
                case "jump": case "start": case "end": Object(state, "op", "target"); Edge(state.GetProperty("target")); break;
                case "split": Object(state, "op", "first", "second"); Edge(state.GetProperty("first")); Edge(state.GetProperty("second")); break;
                case "char":
                    Object(state, "op", "target", "ranges"); Edge(state.GetProperty("target")); var ranges = Array(state.GetProperty("ranges"));
                    Need(ranges.GetArrayLength() <= 8192 && (totalRanges += ranges.GetArrayLength()) <= 65_536, "Pattern ranges exceed portable bounds");
                    var previous = -2;
                    foreach (var range in ranges.EnumerateArray())
                    {
                        Visit(); Need(Array(range).GetArrayLength() == 2, "Invalid pattern range tuple");
                        var start = Integer(range[0], 0x10ffff); var end = Integer(range[1], 0x10ffff);
                        Need(start <= end && start > previous + 1 && !(start <= 0xdfff && end >= 0xd800), "Pattern ranges must be normalized Unicode scalar ranges"); previous = end;
                    }
                    break;
                default: throw Error(_at, "Unknown pattern opcode");
            }
        }
    }
}
