//! Build script: compiles the vendored tree-sitter grammars (JSON, YAML).
//!
//! Each grammar is compiled as its own cc unit so it picks up its own
//! generated `tree_sitter/parser.h` (ABI generations differ between them).

use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let ts_include = PathBuf::from(
        std::env::var("DEP_TREE_SITTER_INCLUDE")
            .expect("tree-sitter runtime did not emit DEP_TREE_SITTER_INCLUDE"),
    );
    // runtime src/ holds alloc.h and friends used by grammar support headers
    let ts_src = ts_include
        .parent()
        .map(|p| p.join("src"))
        .expect("tree-sitter include dir has a parent");

    println!("cargo:rerun-if-changed=grammars/");

    // JSON grammar (generated by tree-sitter CLI 0.24.x)
    let json_dir = manifest.join("grammars/json/src");
    let mut json = cc::Build::new();
    json.file(json_dir.join("parser.c"))
        .include(&json_dir)
        .include(&ts_include)
        .include(&ts_src)
        .flag_if_supported("-std=c11")
        .warnings(false);
    json.compile("suspect_ts_json");

    // YAML grammar (generated by tree-sitter CLI 0.25.x; has an external scanner)
    let yaml_dir = manifest.join("grammars/yaml/src");
    let mut yaml = cc::Build::new();
    yaml.file(yaml_dir.join("parser.c"))
        .file(yaml_dir.join("scanner.c"))
        .include(&yaml_dir)
        .include(&ts_include)
        .include(&ts_src)
        .flag_if_supported("-std=c11")
        .warnings(false);
    yaml.compile("suspect_ts_yaml");
}
