import type { ValidationSource } from '../validation.js';
import type { CallOptions, ClientOptions, CredentialContext, CredentialRequirement, OperationDescriptor, ServerChoice } from './types.js';
import { Control, RuntimeError, encodeUtf8, freezeMetadata, objectData, utf8Length } from './common.js';
import { percentEncode, token } from './wire.js';
import { parseUriReference, resolveUriDocument } from '../uri.js';

const HEADER_LIMIT = 64 * 1024;
export function setHeader(headers: Headers, name: string, value: string, operation: ValidationSource, source: ValidationSource): void {
    try {
        if (!token(name) || /[\u0000-\u0008\u000a-\u001f\u007f]/.test(value)) throw new TypeError('invalid HTTP header name or control character');
        if (utf8Length(name) + utf8Length(value) > HEADER_LIMIT) throw new RuntimeError('resource-limit', 'request header exceeds the generated byte ceiling', operation, source);
        if (headers.has(name)) throw new TypeError(`multiple inputs target header ${name}`);
        headers.set(name, value);
        if (headers.get(name) !== value) throw new TypeError('Fetch would normalize the declared header value');
    } catch (error) {
        if (error instanceof RuntimeError) throw error;
        throw new RuntimeError('request-representation', `header ${name} cannot be represented unchanged`, operation, source, error);
    }
}
function validURLReference(value: string): void {
    if (value === '' || /[\s\u0000-\u001f\u007f?#\\{}]/u.test(value) || /%(?![0-9a-fA-F]{2})/.test(value)) throw new TypeError('server URL contains invalid characters or escapes');
}
export function serverURL(descriptor: OperationDescriptor<unknown>, client: ClientOptions<object>, call: CallOptions): string {
    const source = descriptor.wire.servers.source.source;
    try {
        const choice: ServerChoice = call.server ?? client.server ?? {};
        if (client.serverURL !== undefined && call.server === undefined) {
            if (client.server !== undefined) throw new TypeError('choose serverURL or a declared server selection');
            validURLReference(client.serverURL);
            if (parseUriReference(client.serverURL).scheme === undefined) throw new TypeError('serverURL must be absolute');
            return checkedURL(resolveUriDocument('https://unused.invalid/', client.serverURL));
        }
        const options = objectData(choice);
        if (Object.keys(options).some(key => !['index', 'name', 'variables', 'documentURL'].includes(key))) throw new TypeError('unknown server selection member');
        if (options.index !== undefined && options.name !== undefined) throw new TypeError('choose a server by index or name');
        const servers = descriptor.wire.servers.candidates;
        const index = options.name === undefined ? options.index ?? 0 : servers.findIndex(server => server.name?.value === options.name);
        if (typeof index !== 'number' || !Number.isSafeInteger(index) || index < 0 || index >= servers.length) throw new TypeError('server selection does not name a declared candidate');
        const selected = servers[index]!;
        const overrides = options.variables === undefined ? Object.create(null) as Record<string, unknown> : objectData(options.variables);
        for (const name of Object.keys(overrides)) if (!selected.variables.some(variable => variable.name === name) || typeof overrides[name] !== 'string') throw new TypeError('unknown or non-string server variable override');
        for (const variable of selected.variables) {
            const value = overrides[variable.name] ?? variable.default.value;
            if (variable.values !== null && !variable.values.some(allowed => allowed.value === value)) throw new TypeError(`server variable ${variable.name} is outside its declared enum`);
        }
        const expanded = selected.template.replace(/\{([^{}]+)\}/g, (_marker, name: string) => {
            const variable = selected.variables.find(variable => variable.name === name);
            if (variable === undefined) throw new TypeError('server template has an undeclared variable');
            return overrides[name] as string | undefined ?? variable.default.value;
        });
        validURLReference(expanded);
        let base = 'https://unused.invalid/';
        if (parseUriReference(expanded).scheme === undefined) {
            const documentURL = options.documentURL ?? selected.document_base.source.document;
            if (typeof documentURL !== 'string') throw new TypeError('relative server needs the HTTP URL serving its source document');
            const parsed = parseUriReference(documentURL);
            if (parsed.scheme !== 'http' && parsed.scheme !== 'https' || parsed.authority === undefined || parsed.authority === '') throw new TypeError('a local-file relative server needs an explicit HTTP documentURL');
            base = documentURL;
        }
        return checkedURL(resolveUriDocument(base, expanded));
    } catch (error) { throw new RuntimeError('request-representation', 'server selection or variables are invalid', descriptor.source, source, error); }
}
function checkedURL(value: string): string {
    const url = new URL(value);
    if ((url.protocol !== 'http:' && url.protocol !== 'https:') || url.hostname === '' || url.username !== '' || url.password !== '' || url.hash !== '' || url.search !== '') throw new TypeError('server URL requires HTTP(S), a host, and no userinfo/query/fragment');
    // Use URL only for HTTP authority validation. Its repaired path spelling
    // must not replace the strict document-base result.
    return value;
}

function base64(bytes: Uint8Array): string {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    let result = '';
    for (let i = 0; i < bytes.length; i += 3) {
        const a = bytes[i]!, b = bytes[i + 1], c = bytes[i + 2];
        result += alphabet[a >> 2]! + alphabet[(a & 3) << 4 | (b ?? 0) >> 4]! +
            (b === undefined ? '=' : alphabet[(b & 15) << 2 | (c ?? 0) >> 6]!) + (c === undefined ? '=' : alphabet[c & 63]!);
    }
    return result;
}
function attachment(requirement: CredentialRequirement, value: unknown, operation: ValidationSource): { location: 'header' | 'query' | 'cookie'; name: string; value: string } {
    const credential = requirement.credential;
    if (credential.kind === 'bearer') {
        if (typeof value !== 'string' || !/^[A-Za-z0-9\-._~+/]+=*$/.test(value)) throw new TypeError('bearer credential must be an RFC 6750 token');
        return { location: 'header', name: 'Authorization', value: `Bearer ${value}` };
    }
    if (credential.kind === 'basic') {
        const basic = objectData(value);
        if (Object.keys(basic).some(key => !['username', 'password', 'encoding'].includes(key)) || typeof basic.username !== 'string' || typeof basic.password !== 'string' || basic.username.includes(':')) throw new TypeError('Basic credentials require username without a colon and a password');
        const text = `${basic.username}:${basic.password}`;
        if (/[\u0000-\u001f\u007f]/.test(text)) throw new TypeError('Basic credentials contain control characters');
        let bytes: Uint8Array;
        if (basic.encoding === 'utf-8') bytes = encodeUtf8(text, HEADER_LIMIT / 2, operation, requirement.scheme.terminal.source);
        else {
            if (basic.encoding !== undefined && basic.encoding !== 'latin1') throw new TypeError('Basic encoding must be utf-8 or latin1');
            if (Array.from(text).some(char => char.codePointAt(0)! > (basic.encoding === 'latin1' ? 255 : 127))) throw new TypeError('non-ASCII Basic credentials require an explicit caller-chosen encoding');
            if (text.length > HEADER_LIMIT / 2) throw new TypeError('Basic credential exceeds its byte ceiling');
            bytes = Uint8Array.from(text, char => char.charCodeAt(0));
        }
        return { location: 'header', name: 'Authorization', value: `Basic ${base64(bytes)}` };
    }
    if (credential.kind === 'api-key') {
        if (typeof value !== 'string' || value.length === 0 || /[\u0000-\u001f\u007f]/.test(value)) throw new TypeError('API key must be a nonempty string without controls');
        if (credential.location === 'path' || credential.location === 'querystring') throw new TypeError('API keys require a named header, query or cookie slot');
        return { location: credential.location, name: credential.name.value, value };
    }
    const authorization = objectData(value);
    if (Object.keys(authorization).some(key => key !== 'authorization') || typeof authorization.authorization !== 'string' ||
        !/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+ [\x21-\x7e]+(?: [\x21-\x7e]+)*$/.test(authorization.authorization)) throw new TypeError('OAuth/OIDC requires an explicit complete Authorization value, including its scheme');
    return { location: 'header', name: 'Authorization', value: authorization.authorization };
}

export async function credentials(descriptor: OperationDescriptor<unknown>, client: ClientOptions<object>, call: CallOptions, control: Control,
    headers: Headers, query: string[], cookies: string[], effectiveServerURL: string): Promise<void> {
    const security = descriptor.wire.security;
    if (security.kind !== 'alternatives') {
        if (call.securityAlternative !== undefined) throw new RuntimeError('request-representation', 'this operation has no security alternatives', descriptor.source, security.source.source);
        return;
    }
    let auth: Record<string, unknown>;
    try { auth = client.auth === undefined ? Object.create(null) as Record<string, unknown> : objectData(client.auth); }
    catch (error) { throw new RuntimeError('request-validation', 'auth must have own data credentials', descriptor.source, security.source.source, error); }
    const alternatives = security.alternatives;
    const selected = call.securityAlternative ?? alternatives.findIndex(alternative => alternative.requirements.every(requirement => Object.hasOwn(auth, requirement.name)));
    if (!Number.isSafeInteger(selected) || selected < 0 || selected >= alternatives.length) throw new RuntimeError('request-validation', 'no complete declared security alternative is available', descriptor.source, security.source.source);
    for (const requirement of alternatives[selected]!.requirements) {
        const source = requirement.scheme.terminal.source;
        try {
            if (!Object.hasOwn(auth, requirement.name)) throw new TypeError(`missing credential for ${requirement.name}`);
            let value = auth[requirement.name];
            if (typeof value === 'function') {
                const context: CredentialContext = Object.freeze({ operationSource: descriptor.source, operationId: descriptor.operationId,
                    requirement: freezeMetadata(requirement), signal: control.signal, effectiveServerURL });
                value = await control.race(Promise.resolve(value(context)));
            }
            control.check(source);
            const field = attachment(requirement, value, descriptor.source);
            if (field.location === 'header') setHeader(headers, field.name, field.value, descriptor.source, source);
            else {
                const values = field.location === 'query' ? query : cookies;
                const name = percentEncode(field.name, 'uri-component');
                const names = values.flatMap(value => value.split(field.location === 'query' ? '&' : '; ').map(pair => pair.split('=', 1)[0]!));
                if (names.some(key => decodeURIComponent(key) === field.name)) throw new TypeError(`multiple inputs target ${field.location} ${field.name}`);
                values.push(`${name}=${percentEncode(field.value, 'uri-component')}`);
            }
        } catch (error) {
            if (error instanceof RuntimeError) throw error;
            throw new RuntimeError('request-validation', `credential for ${requirement.name} cannot be attached`, descriptor.source, source, error);
        }
    }
}
