//! Emitted-only pagination walkers. The static runtime gains nothing: every
//! walker, accessor and error type below is generated into the consumer
//! package only when the plan carries source-selected paginated operations.
//!
//! Walkers reuse the emitted operation functions for transport, encoding and
//! decoding, and resolve the compiled response pointers into typed field
//! accesses over the decoded page models planned by the model planner.

use super::*;
use crate::http_protocol::OperationPagination;
use crate::rust_models::{Decl, RepresentationRole, Type};
use crate::sdk_defaults::{
    PaginationAdvance, PaginationPattern, PaginationRequestRole, PaginationResponseRole,
};

/// Everything `package` needs to emit pagination support.
pub(super) struct Emission {
    /// The generated `rust/src/pagination.rs` module content.
    pub(super) module: String,
    /// Client-impl methods appended to the emitted root by `root`.
    pub(super) methods: String,
}

/// How the walk computes and applies its continuation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    /// Offset advanced by the previous page's item count.
    ItemsReturned,
    /// Continuation value taken from a mapped response pointer.
    Pointer,
    /// One-based page parameter incremented every page.
    Increment,
}

/// The Rust carrier of a request-side pagination value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ValueKind {
    /// Exact `crate::JsonInteger` model.
    JsonInteger,
    /// A fixed-width native integer primitive.
    Native(&'static str),
    /// A plain `std::string::String`.
    Text,
}

/// Optionality wrapper observed on a model field.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Wrapper {
    None,
    Optional,
    Presence,
    Nullable,
}

/// The final value shape an accessor chain produces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Leaf {
    /// `Option<&[Element]>` over an array-valued field.
    Slice,
    /// `Option<String>` continuation token (raw string or decimal token).
    Token,
    /// `Option<i128>` numeric continuation or total.
    Number,
    /// `Option<bool>` presence flag.
    Flag,
}

/// A generated accessor chain: one expression over the `page` binding.
struct Walk {
    expr: String,
    ty: Type,
    optional: bool,
}

const NATIVE_INTEGERS: &[&str] = &[
    "i8", "i16", "i32", "i64", "i128", "u8", "u16", "u32", "u64", "u128",
];

fn operation_identity(op: &PlannedOperation) -> String {
    op.wire()
        .operation_id()
        .map(|located| located.value().clone())
        .unwrap_or_else(|| format!("{} {}", op.wire().method().as_str(), op.wire().path()))
}

/// Compile the pagination emission for one plan, or `None` when the plan has
/// no emittable paginated operation (the package then gains nothing at all).
pub(super) fn emission(plan: &HttpPlan) -> Option<Emission> {
    let outcome = plan.pagination()?;
    if outcome.paginated.is_empty() {
        return None;
    }
    // Outcome entries and planned operations both follow the protocol's
    // operation order, so entries pair up per identity in first-seen order.
    let mut by_identity: BTreeMap<&str, Vec<&OperationPagination>> = BTreeMap::new();
    for entry in &outcome.paginated {
        by_identity
            .entry(entry.operation.as_str())
            .or_default()
            .push(entry);
    }
    let mut module = String::from(
        "//! Code generated by suspect. DO NOT EDIT.\n//!\n//! Generated pagination walkers for the source-selected paginated\n//! operations of this package.\n//!\n//! Every pager is a concrete struct with a pull-based `next`. A `next` call\n//! issues at most one request and awaits the transport directly: no tasks are\n//! spawned, a request starts only while the returned future is polled, and\n//! dropping the pager (or stopping iteration) cancels a pending request and\n//! never fires another one. A page is fetched exactly once; every later page\n//! rebuilds the caller's input with only the pagination control changed. A\n//! source that repeats an identical continuation value fails the walk with\n//! `SdkErrorKind::UnexpectedResponse` and a [`PaginationLoop`] cause instead\n//! of looping.\n\n/// A pagination walk refused to continue because the source repeated an\n/// identical continuation value, which would loop forever.\n#[derive(Debug)]\npub struct PaginationLoop {\n    /// The repeated continuation token, exactly as the source returned it.\n    pub value: std::string::String,\n}\nimpl std::fmt::Display for PaginationLoop {\n    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n        write!(\n            f,\n            \"the source repeated pagination continuation {:?}\",\n            self.value\n        )\n    }\n}\nimpl std::error::Error for PaginationLoop {}\n",
    );
    let mut methods = String::new();
    let mut emitted = 0usize;
    for op in plan.operations() {
        let identity = operation_identity(op);
        let Some(pagination) = by_identity.get_mut(identity.as_str()).and_then(Vec::pop) else {
            continue;
        };
        let Some(compiled) = compile(plan, op, pagination) else {
            continue;
        };
        module.push_str(&compiled.body);
        methods.push_str(&compiled.method);
        emitted += 1;
    }
    if emitted == 0 {
        return None;
    }
    Some(Emission { module, methods })
}

struct Compiled {
    body: String,
    method: String,
}

/// The request-side pagination control the pager rewrites between pages.
#[derive(Debug, Clone)]
struct Control {
    member: String,
    model: String,
    kind: ValueKind,
    required: bool,
}

impl Control {
    fn wrap(&self, value: &str) -> String {
        if self.required {
            value.to_owned()
        } else {
            format!("std::option::Option::Some({value})")
        }
    }
}

fn compile(
    plan: &HttpPlan,
    op: &PlannedOperation,
    pagination: &OperationPagination,
) -> Option<Compiled> {
    if pagination.pattern == PaginationPattern::NextLink || operation::streams(op) {
        return None;
    }
    // Walkers read the decoded page through the single successful alternative.
    let mut success_variants = op
        .responses
        .iter()
        .flat_map(|response| &response.variants)
        .filter(|variant| variant.success);
    let single = success_variants.next()?;
    if success_variants.next().is_some() {
        return None;
    }
    let Payload::Model { schema, model } = &single.payload else {
        return None;
    };
    let (control_role, mode) = match (pagination.pattern, pagination.advance) {
        (PaginationPattern::LimitOffset, PaginationAdvance::ItemsReturned) => {
            (PaginationRequestRole::Offset, Mode::ItemsReturned)
        }
        (PaginationPattern::LimitOffset, PaginationAdvance::NextOffset) => {
            (PaginationRequestRole::Offset, Mode::Pointer)
        }
        (PaginationPattern::Cursor, _) => (PaginationRequestRole::Cursor, Mode::Pointer),
        (PaginationPattern::PageNumber, _) => (PaginationRequestRole::Page, Mode::Increment),
        _ => return None,
    };
    let control_name = pagination.request.get(&control_role)?;
    let control_param = op
        .parameters
        .iter()
        .find(|parameter| parameter.wire.name() == control_name.as_str())?;
    let control = Control {
        member: control_param.name.clone(),
        model: control_param.model.clone(),
        kind: parameter_kind(plan, control_param)?,
        required: control_param.wire.required(),
    };
    let continuation = match mode {
        Mode::Pointer => {
            let offset = pagination.response.get(&PaginationResponseRole::NextOffset);
            let cursor = pagination.response.get(&PaginationResponseRole::NextCursor);
            let (first, second) = if pagination.pattern == PaginationPattern::Cursor {
                (cursor, offset)
            } else {
                (offset, cursor)
            };
            let mut resolved: Option<Walk> = None;
            for pointer in first.into_iter().chain(second) {
                if let Some(walk) = walk_pointer(plan, schema, pointer, leaf_for(control.kind)) {
                    resolved = Some(walk);
                    break;
                }
            }
            resolved
        }
        Mode::ItemsReturned | Mode::Increment => None,
    };
    let items_pointer = pagination.response.get(&PaginationResponseRole::Items)?;
    let items = walk_pointer(plan, schema, items_pointer, Leaf::Slice)?;
    let element = plan.codecs.models().render_external_type(&items.ty);
    if element == "crate::Never" {
        return None;
    }
    // The documented SDK fallback page size rewrites the limit control on the
    // first request only, when the caller left it absent. A required limit
    // control has no absent state, so it can never take a fallback.
    let fallback_limit = pagination
        .request
        .get(&PaginationRequestRole::Limit)
        .and_then(|name| {
            let parameter = op
                .parameters
                .iter()
                .find(|parameter| parameter.wire.name() == name.as_str())?;
            Some(Control {
                member: parameter.name.clone(),
                model: parameter.model.clone(),
                kind: parameter_kind(plan, parameter)?,
                required: parameter.wire.required(),
            })
        })
        .filter(|control| !control.required);
    let has_more = match pagination.response.get(&PaginationResponseRole::HasMore) {
        Some(pointer) => Some(walk_pointer(plan, schema, pointer, Leaf::Flag)?),
        None => None,
    };
    let total = if mode == Mode::ItemsReturned {
        match pagination.response.get(&PaginationResponseRole::Total) {
            Some(pointer) => Some(walk_pointer(plan, schema, pointer, Leaf::Number)?),
            None => None,
        }
    } else {
        None
    };
    Some(render(
        op,
        pagination,
        Rendered {
            mode,
            control,
            model: model.clone(),
            variant: single.name.clone(),
            items,
            element,
            continuation,
            has_more,
            total,
            fallback_limit,
        },
    ))
}

/// The accessor leaf flavor a control kind can consume.
fn leaf_for(kind: ValueKind) -> Leaf {
    match kind {
        ValueKind::Text => Leaf::Token,
        ValueKind::JsonInteger | ValueKind::Native(_) => Leaf::Number,
    }
}

/// The model carrier of one pagination request parameter.
fn parameter_kind(plan: &HttpPlan, parameter: &PlannedParameter) -> Option<ValueKind> {
    let key = (
        parameter.wire.codec().schema().id().clone(),
        RepresentationRole::Model,
    );
    match plan.codecs.models().declarations.get(&key)? {
        Decl::Alias(Type::Primitive("crate::JsonInteger")) => Some(ValueKind::JsonInteger),
        Decl::Alias(Type::Primitive(name)) if NATIVE_INTEGERS.contains(name) => {
            Some(ValueKind::Native(name))
        }
        Decl::Alias(Type::Primitive("std::string::String")) => Some(ValueKind::Text),
        _ => None,
    }
}

/// Resolve one RFC 6901 pointer over the planned page model into a generated
/// accessor body. `None` means this plan cannot express the pointer with typed
/// field accesses and the operation stays without walkers.
fn walk_pointer(plan: &HttpPlan, root: &SchemaId, pointer: &str, leaf: Leaf) -> Option<Walk> {
    let segments: Vec<String> = if pointer.is_empty() {
        Vec::new()
    } else {
        pointer[1..]
            .split('/')
            .map(|segment| segment.replace("~1", "/").replace("~0", "~"))
            .collect()
    };
    let declarations = &plan.codecs.models().declarations;
    if segments.is_empty() {
        // The page model itself is the collection.
        let mut key = (root.clone(), RepresentationRole::Model);
        for _ in 0..64 {
            match declarations.get(&key)? {
                Decl::Alias(Type::Vec(element)) => {
                    return Some(Walk {
                        expr: "std::option::Option::Some(page.as_slice())".into(),
                        ty: (**element).clone(),
                        optional: true,
                    });
                }
                Decl::Alias(Type::Named(next)) => key = next.clone(),
                Decl::Alias(Type::Nullable(inner)) => match inner.as_ref() {
                    Type::Named(next) => key = next.clone(),
                    _ => return None,
                },
                _ => return None,
            }
        }
        return None;
    }
    // Follow nullable and alias roots to the page struct declaration.
    let mut key = (root.clone(), RepresentationRole::Model);
    for _ in 0..64 {
        match declarations.get(&key)? {
            Decl::Struct { .. } => break,
            Decl::Alias(Type::Named(next)) => key = next.clone(),
            Decl::Alias(Type::Nullable(inner)) => match inner.as_ref() {
                Type::Named(next) => key = next.clone(),
                _ => return None,
            },
            _ => return None,
        }
    }
    let mut counter = 0usize;
    walk(plan, &key, "page", &segments, &mut counter, leaf)
}

fn walk(
    plan: &HttpPlan,
    key: &crate::rust_models::Key,
    place: &str,
    segments: &[String],
    counter: &mut usize,
    leaf: Leaf,
) -> Option<Walk> {
    let declarations = &plan.codecs.models().declarations;
    let Decl::Struct { fields, .. } = declarations.get(key)? else {
        return None;
    };
    let field = fields.iter().find(|field| field.wire == segments[0])?;
    let (wrapper, inner) = unwrap_field(&field.ty)?;
    let access = format!("{place}.{}", field.name);
    if segments.len() == 1 {
        return leaf_convert(&access, wrapper, inner, leaf);
    }
    let Type::Named(next) = inner else {
        return None;
    };
    match wrapper {
        Wrapper::None => walk(plan, next, &access, &segments[1..], counter, leaf),
        Wrapper::Optional => {
            *counter += 1;
            let binding = format!("value_{}", counter);
            let child = walk(plan, next, &binding, &segments[1..], counter, leaf)?;
            Some(Walk {
                expr: format!("{access}.as_ref().and_then(|{binding}| {})", adapt(&child)),
                ty: child.ty,
                optional: true,
            })
        }
        Wrapper::Presence | Wrapper::Nullable => {
            *counter += 1;
            let binding = format!("value_{}", counter);
            let child = walk(plan, next, &binding, &segments[1..], counter, leaf)?;
            let container = if wrapper == Wrapper::Presence {
                "crate::Presence"
            } else {
                "crate::Nullable"
            };
            Some(Walk {
                expr: format!(
                    "match &{access} {{ {container}::Value({binding}) => {}, _ => std::option::Option::None }}",
                    adapt(&child)
                ),
                ty: child.ty,
                optional: true,
            })
        }
    }
}

/// Strip transparency and optionality wrappers from a planned field type.
fn unwrap_field(ty: &Type) -> Option<(Wrapper, &Type)> {
    let mut wrapper = Wrapper::None;
    let mut inner = ty;
    loop {
        match inner {
            Type::Optional(next) if wrapper == Wrapper::None => {
                wrapper = Wrapper::Optional;
                inner = next;
            }
            Type::Presence(next) if wrapper == Wrapper::None => {
                wrapper = Wrapper::Presence;
                inner = next;
            }
            Type::Nullable(next) if wrapper == Wrapper::None => {
                wrapper = Wrapper::Nullable;
                inner = next;
            }
            Type::Boxed(next) => inner = next,
            _ => break,
        }
    }
    Some((wrapper, inner))
}

fn adapt(child: &Walk) -> String {
    if child.optional {
        child.expr.clone()
    } else {
        format!("std::option::Option::Some({})", child.expr)
    }
}

/// Build the accessor leaf expression for one field access.
fn leaf_convert(access: &str, wrapper: Wrapper, inner: &Type, leaf: Leaf) -> Option<Walk> {
    let walk = |expr: String, ty: Type| {
        Some(Walk {
            expr,
            ty,
            optional: true,
        })
    };
    match leaf {
        Leaf::Slice => {
            let Type::Vec(element) = inner else {
                return None;
            };
            let element = (**element).clone();
            let expr = match wrapper {
                Wrapper::None => format!("std::option::Option::Some(({access}).as_slice())"),
                Wrapper::Optional => format!("({access}).as_ref().map(std::vec::Vec::as_slice)"),
                Wrapper::Presence => format!(
                    "match &{access} {{ crate::Presence::Value(value) => std::option::Option::Some(value.as_slice()), _ => std::option::Option::None }}"
                ),
                Wrapper::Nullable => format!(
                    "match &{access} {{ crate::Nullable::Value(value) => std::option::Option::Some(value.as_slice()), _ => std::option::Option::None }}"
                ),
            };
            walk(expr, element)
        }
        Leaf::Token => match inner {
            Type::Primitive("std::string::String") => {
                let expr = match wrapper {
                    Wrapper::None => format!("std::option::Option::Some(({access}).clone())"),
                    Wrapper::Optional => format!("({access}).clone()"),
                    Wrapper::Presence => format!(
                        "match &{access} {{ crate::Presence::Value(value) => std::option::Option::Some(value.clone()), _ => std::option::Option::None }}"
                    ),
                    Wrapper::Nullable => format!(
                        "match &{access} {{ crate::Nullable::Value(value) => std::option::Option::Some(value.clone()), _ => std::option::Option::None }}"
                    ),
                };
                walk(expr, Type::Primitive("std::string::String"))
            }
            Type::Primitive("crate::JsonInteger") => {
                let expr = match wrapper {
                    Wrapper::None => {
                        format!("std::option::Option::Some(({access}).as_str().to_owned())")
                    }
                    Wrapper::Optional => {
                        format!("({access}).as_ref().map(|value| value.as_str().to_owned())")
                    }
                    Wrapper::Presence => format!(
                        "match &{access} {{ crate::Presence::Value(value) => std::option::Option::Some(value.as_str().to_owned()), _ => std::option::Option::None }}"
                    ),
                    Wrapper::Nullable => format!(
                        "match &{access} {{ crate::Nullable::Value(value) => std::option::Option::Some(value.as_str().to_owned()), _ => std::option::Option::None }}"
                    ),
                };
                walk(expr, Type::Primitive("std::string::String"))
            }
            Type::Primitive(name) if NATIVE_INTEGERS.contains(name) => {
                let expr = match wrapper {
                    Wrapper::None => format!("std::option::Option::Some(({access}).to_string())"),
                    Wrapper::Optional => format!("({access}).map(|value| value.to_string())"),
                    Wrapper::Presence => format!(
                        "match &{access} {{ crate::Presence::Value(value) => std::option::Option::Some(value.to_string()), _ => std::option::Option::None }}"
                    ),
                    Wrapper::Nullable => format!(
                        "match &{access} {{ crate::Nullable::Value(value) => std::option::Option::Some(value.to_string()), _ => std::option::Option::None }}"
                    ),
                };
                walk(expr, Type::Primitive("std::string::String"))
            }
            _ => None,
        },
        Leaf::Number => match inner {
            Type::Primitive("crate::JsonInteger") => {
                let expr = match wrapper {
                    Wrapper::None => format!("({access}).to_i128()"),
                    Wrapper::Optional => {
                        format!("({access}).as_ref().and_then(crate::JsonInteger::to_i128)")
                    }
                    Wrapper::Presence => format!(
                        "match &{access} {{ crate::Presence::Value(value) => value.to_i128(), _ => std::option::Option::None }}"
                    ),
                    Wrapper::Nullable => format!(
                        "match &{access} {{ crate::Nullable::Value(value) => value.to_i128(), _ => std::option::Option::None }}"
                    ),
                };
                walk(expr, Type::Primitive("i128"))
            }
            Type::Primitive(name) if NATIVE_INTEGERS.contains(name) => {
                let expr = match wrapper {
                    Wrapper::None => format!("i128::try_from({access}).ok()"),
                    Wrapper::Optional => {
                        format!("({access}).and_then(|value| i128::try_from(value).ok())")
                    }
                    Wrapper::Presence => format!(
                        "match &{access} {{ crate::Presence::Value(value) => i128::try_from(*value).ok(), _ => std::option::Option::None }}"
                    ),
                    Wrapper::Nullable => format!(
                        "match &{access} {{ crate::Nullable::Value(value) => i128::try_from(*value).ok(), _ => std::option::Option::None }}"
                    ),
                };
                walk(expr, Type::Primitive("i128"))
            }
            _ => None,
        },
        Leaf::Flag => {
            if !matches!(inner, Type::Primitive("bool")) {
                return None;
            }
            let expr = match wrapper {
                Wrapper::None => format!("std::option::Option::Some({access})"),
                Wrapper::Optional => format!("({access})"),
                Wrapper::Presence => format!(
                    "match &{access} {{ crate::Presence::Value(value) => std::option::Option::Some(*value), _ => std::option::Option::None }}"
                ),
                Wrapper::Nullable => format!(
                    "match &{access} {{ crate::Nullable::Value(value) => std::option::Option::Some(*value), _ => std::option::Option::None }}"
                ),
            };
            walk(expr, Type::Primitive("bool"))
        }
    }
}

struct Rendered {
    mode: Mode,
    control: Control,
    model: String,
    variant: String,
    items: Walk,
    element: String,
    continuation: Option<Walk>,
    has_more: Option<Walk>,
    total: Option<Walk>,
    /// The limit control carrying the documented SDK fallback page size, when
    /// the operation has one and it can express the fallback.
    fallback_limit: Option<Control>,
}

fn render(op: &PlannedOperation, pagination: &OperationPagination, parts: Rendered) -> Compiled {
    let Rendered {
        mode,
        control,
        model,
        variant,
        items,
        element,
        continuation,
        has_more,
        total,
        fallback_limit,
    } = parts;
    let module = &op.module_name;
    let function = &op.function_name;
    let stem = rust_models::pascal(module);
    let pages = format!("{stem}Pages");
    let items_pager = format!("{stem}Items");
    let input = &op.input_type;
    let success = &op.success_type;
    let error = &op.error_type;
    let operations = format!("crate::operations::{module}");
    let page_model = format!("crate::models::{model}");
    let label = format!(
        "{} {} — {}",
        op.wire().method().as_str(),
        op.wire().path(),
        pattern_label(pagination)
    );
    let mut body = String::new();
    body.push_str(&format!(
        "\n// ---- {} ----\n\n/// The decoded page of `{function}` as its single successful alternative.\nfn {function}_page_data(page: &{operations}::{success}) -> &{page_model} {{\n    match page {{\n        {operations}::{success}::{variant}(response) => &response.data,\n    }}\n}}\n",
        prose(&label),
    ));
    body.push_str(&format!(
        "/// Items collection of one decoded `{function}` page at `{}`.\nfn {function}_page_items(page: &{page_model}) -> std::option::Option<&[{element}]> {{\n    {}\n}}\n",
        pagination
            .response
            .get(&PaginationResponseRole::Items)
            .map(String::as_str)
            .unwrap_or_default(),
        items.expr,
    ));
    if let Some(continuation) = &continuation {
        let return_type = match leaf_for(control.kind) {
            Leaf::Token => "std::option::Option<std::string::String>",
            _ => "std::option::Option<i128>",
        };
        body.push_str(&format!(
            "/// Continuation value of one decoded `{function}` page at `{}`.\nfn {function}_page_continuation(page: &{page_model}) -> {return_type} {{\n    {}\n}}\n",
            continuation_pointer(pagination),
            continuation.expr,
        ));
    }
    if let Some(has_more) = &has_more {
        body.push_str(&format!(
            "/// Declared has-more flag of one decoded `{function}` page at `{}`.\nfn {function}_page_has_more(page: &{page_model}) -> std::option::Option<bool> {{\n    {}\n}}\n",
            pagination
                .response
                .get(&PaginationResponseRole::HasMore)
                .map(String::as_str)
                .unwrap_or_default(),
            has_more.expr,
        ));
    }
    if let Some(total) = &total {
        body.push_str(&format!(
            "/// Declared total of one decoded `{function}` page at `{}`.\nfn {function}_page_total(page: &{page_model}) -> std::option::Option<i128> {{\n    {}\n}}\n",
            pagination
                .response
                .get(&PaginationResponseRole::Total)
                .map(String::as_str)
                .unwrap_or_default(),
            total.expr,
        ));
    }
    body.push_str(&error_function(function, &operations, error));
    body.push_str(&pages_pager(
        op,
        pagination,
        mode,
        &control,
        fallback_limit.as_ref(),
        &pages,
        &operations,
        input,
        success,
        error,
        function,
        has_more.is_some(),
        total.is_some(),
    ));
    body.push_str(&items_pager_source(
        &items_pager,
        &pages,
        &operations,
        input,
        error,
        function,
        &element,
    ));
    body.push_str(&next_page_source(
        mode,
        &control,
        fallback_limit.as_ref(),
        pagination.initial_limit,
        function,
        &operations,
        input,
        error,
        has_more.is_some(),
        pagination.initial_offset.unwrap_or(0),
    ));
    let method = client_methods(op, &pages, &items_pager, &operations, input, error);
    Compiled { body, method }
}

fn pattern_label(pagination: &OperationPagination) -> &'static str {
    match (pagination.pattern, pagination.advance) {
        (PaginationPattern::LimitOffset, PaginationAdvance::ItemsReturned) => {
            "limit/offset, advanced by items returned"
        }
        (PaginationPattern::LimitOffset, PaginationAdvance::NextOffset) => {
            "limit/offset, advanced by the declared next offset"
        }
        (PaginationPattern::Cursor, _) => "cursor continuation",
        (PaginationPattern::PageNumber, _) => "one-based page number",
        _ => "next-link continuation",
    }
}

fn continuation_pointer(pagination: &OperationPagination) -> &str {
    let offset = pagination.response.get(&PaginationResponseRole::NextOffset);
    let cursor = pagination.response.get(&PaginationResponseRole::NextCursor);
    let (first, second) = if pagination.pattern == PaginationPattern::Cursor {
        (cursor, offset)
    } else {
        (offset, cursor)
    };
    first.or(second).map(String::as_str).unwrap_or_default()
}

fn error_function(function: &str, operations: &str, error: &str) -> String {
    format!(
        "/// A pagination failure for `{function}`: `UnexpectedResponse` with a\n/// typed [`PaginationLoop`] cause for repeated continuations, or a\n/// request-validation failure when a pagination value is not representable.\nfn {function}_pagination_error(kind: crate::http::SdkErrorKind, message: &'static str, value: std::option::Option<std::string::String>) -> {operations}::{error} {{\n    let mut error = crate::http::validation_error(\n        {operations}::OPERATION.source,\n        {operations}::OPERATION.source,\n        message,\n    );\n    error.kind = kind;\n    if let std::option::Option::Some(value) = value {{\n        error.cause =\n            std::option::Option::Some(std::boxed::Box::new(PaginationLoop {{ value }}));\n    }}\n    {operations}::{error}::Sdk(std::boxed::Box::new(error))\n}}\n"
    )
}

/// An expression reading the control as `i128`, with embedded refusal returns.
fn read_i128(
    control: &Control,
    input: &str,
    fallback: Option<&str>,
    function: &str,
    message: &str,
) -> Option<String> {
    let refuse = |message: &str| {
        format!(
            "return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::RequestValidation,\n                {message:?},\n                std::option::Option::None,\n            ))"
        )
    };
    let read = match (control.kind, control.required) {
        (ValueKind::JsonInteger, true) => format!(
            "match {input}.{}.to_i128() {{\n        std::option::Option::Some(value) => value,\n        std::option::Option::None => {},\n    }}",
            control.member,
            refuse(message)
        ),
        (ValueKind::JsonInteger, false) => format!(
            "match {input}.{}.as_ref() {{\n        std::option::Option::Some(value) => match value.to_i128() {{\n            std::option::Option::Some(value) => value,\n            std::option::Option::None => {},\n        }},\n        std::option::Option::None => {},\n    }}",
            control.member,
            refuse(message),
            fallback?
        ),
        (ValueKind::Native(_), true) => format!(
            "match i128::try_from({input}.{}) {{\n        std::result::Result::Ok(value) => value,\n        std::result::Result::Err(_) => {},\n    }}",
            control.member,
            refuse(message)
        ),
        (ValueKind::Native(_), false) => format!(
            "match {input}.{} {{\n        std::option::Option::Some(value) => match i128::try_from(value) {{\n            std::result::Result::Ok(value) => value,\n            std::result::Result::Err(_) => {},\n        }},\n        std::option::Option::None => {},\n    }}",
            control.member,
            refuse(message),
            fallback?
        ),
        (ValueKind::Text, _) => return None,
    };
    Some(read)
}

/// An `Option<i128>` read without refusal paths, for stateless guards.
fn read_i128_option(control: &Control, input: &str) -> Option<String> {
    Some(match (control.kind, control.required) {
        (ValueKind::JsonInteger, true) => format!("{input}.{}.to_i128()", control.member),
        (ValueKind::JsonInteger, false) => format!(
            "({input}.{}).as_ref().and_then(crate::JsonInteger::to_i128)",
            control.member
        ),
        (ValueKind::Native(_), true) => {
            format!("i128::try_from({input}.{}).ok()", control.member)
        }
        (ValueKind::Native(_), false) => format!(
            "({input}.{}).and_then(|value| i128::try_from(value).ok())",
            control.member
        ),
        (ValueKind::Text, _) => return None,
    })
}

/// A statement storing one `i128` pagination value back into the input.
fn set_i128(control: &Control, input: &str, value: &str, function: &str, message: &str) -> String {
    let conversion = match control.kind {
        ValueKind::JsonInteger => {
            format!(
                "({value}).to_string().parse::<crate::models::{}>()",
                control.model
            )
        }
        ValueKind::Native(native) => format!("{native}::try_from({value})"),
        ValueKind::Text => unreachable!("integer control"),
    };
    format!(
        "match {conversion} {{\n        std::result::Result::Ok(value) => {{ {input}.{} = {}; }}\n        std::result::Result::Err(_) => return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::RequestValidation,\n                {message:?},\n                std::option::Option::None,\n            )),\n    }}",
        control.member,
        control.wrap("value"),
    )
}

/// A statement storing one continuation token back into the input.
fn set_text(control: &Control, input: &str, token: &str) -> String {
    format!("{input}.{} = {};", control.member, control.wrap(token))
}

/// The first-page fill of the configured initial offset, when applicable.
fn initial_fill(control: &Control, input: &str, initial: u32, function: &str) -> Option<String> {
    if control.required {
        return None;
    }
    let message = "the configured initial pagination offset is not representable";
    let conversion = match control.kind {
        ValueKind::JsonInteger => {
            format!("\"{initial}\".parse::<crate::models::{}>()", control.model)
        }
        ValueKind::Native(native) => format!("{native}::try_from({initial}i128)"),
        ValueKind::Text => return None,
    };
    Some(format!(
        "if {input}.{}.is_none() {{\n        let initial = match {conversion} {{\n            std::result::Result::Ok(value) => value,\n            std::result::Result::Err(_) => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    {message:?},\n                    std::option::Option::None,\n                )),\n        }};\n        {input}.{} = std::option::Option::Some(initial);\n    }}",
        control.member, control.member,
    ))
}

/// The first-page fill of the documented SDK fallback page size, when
/// applicable. Like the initial offset, it applies only when the caller left
/// the control absent; later pages keep whatever limit the walk last used.
fn initial_limit_fill(control: &Control, input: &str, size: u32, function: &str) -> Option<String> {
    if control.required {
        return None;
    }
    let message = "the configured fallback page size is not representable";
    let conversion = match control.kind {
        ValueKind::JsonInteger => {
            format!("\"{size}\".parse::<crate::models::{}>()", control.model)
        }
        ValueKind::Native(native) => format!("{native}::try_from({size}i128)"),
        ValueKind::Text => return None,
    };
    Some(format!(
        "if {input}.{}.is_none() {{\n        let page_size = match {conversion} {{\n            std::result::Result::Ok(value) => value,\n            std::result::Result::Err(_) => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    {message:?},\n                    std::option::Option::None,\n                )),\n        }};\n        {input}.{} = std::option::Option::Some(page_size);\n    }}",
        control.member, control.member,
    ))
}

#[allow(clippy::too_many_arguments)]
fn pages_pager(
    op: &PlannedOperation,
    pagination: &OperationPagination,
    mode: Mode,
    control: &Control,
    fallback_limit: Option<&Control>,
    pages: &str,
    operations: &str,
    input: &str,
    success: &str,
    error: &str,
    function: &str,
    has_more: bool,
    total: bool,
) -> String {
    let path = prose(&format!(
        "{} {}",
        op.wire().method().as_str(),
        op.wire().path()
    ));
    // The documented SDK fallback page size fills the limit control on page 1
    // only, and only when the caller left it absent.
    let limit_fill = match (fallback_limit, pagination.initial_limit) {
        (Some(limit), Some(size)) => initial_limit_fill(limit, "rebuilt", size, function)
            .map_or(String::new(), |fill| format!("{fill}\n        ")),
        _ => String::new(),
    };
    let fallback_doc = pagination.initial_limit.map_or_else(String::new, |size| {
        format!(
            " When the caller omits the limit, the first request supplies the documented SDK page size ({size}); later pages keep the limit the walk last used."
        )
    });
    let has_more_stop = |outcome: &str| {
        if !has_more {
            return String::new();
        }
        format!(
            "if {function}_page_has_more(data) == std::option::Option::Some(false) {{\n            return std::result::Result::Ok(std::option::Option::{outcome});\n        }}\n        "
        )
    };
    // Fields, docs, prefix, advance and constructor per walk mode.
    let (fields, docs, prefix, advance, constructor_fields, previous_type) = match mode {
        Mode::ItemsReturned => {
            let prefix = format!(
                "let std::option::Option::Some(mut rebuilt) = self.next.take() else {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }};\n        {limit_fill}{}\n        let base = {};\n        if self.total.is_some_and(|total| base >= total) {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }}\n        let page = {operations}::{function}(self.client, rebuilt.clone()).await?;\n        let data = {function}_page_data(&page);\n        let count = {function}_page_items(data)\n            .map_or(0usize, |items| items.len());\n        if count == 0 {{\n            return std::result::Result::Ok(std::option::Option::Some(page));\n        }}\n        {}{total_set}let advanced = match base.checked_add(count as i128) {{\n            std::option::Option::Some(value) => value,\n            std::option::Option::None => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    \"pagination offset overflow\",\n                    std::option::Option::None,\n                )),\n        }};",
                initial_fill(
                    control,
                    "rebuilt",
                    pagination.initial_offset.unwrap_or(0),
                    function
                )
                .unwrap_or_default(),
                read_i128(
                    control,
                    "rebuilt",
                    Some("0"),
                    function,
                    "the pagination offset is not representable",
                )
                .unwrap_or_default(),
                has_more_stop("Some(page)"),
                total_set = if total {
                    format!("self.total = {function}_page_total(data);\n        ")
                } else {
                    String::new()
                },
            );
            let advance = set_i128(
                control,
                "rebuilt",
                "advanced",
                function,
                "the advanced pagination offset is not representable",
            );
            let docs = format!(
                "/// Lazily walks every page of {path}.\n///\n/// Each `next` issues at most one request and awaits the transport directly:\n/// no tasks are spawned, the request starts only while the returned future is\n/// polled, and dropping the pager cancels a pending request without firing\n/// another one. The first call requests the input as given, filling the\n/// configured initial offset ({}) when the caller left it absent; every later\n/// call rebuilds the input with only the offset advanced by the previous\n/// page's item count. The walk stops on a zero-item page and on a\n/// `has_more=false` page{}.",
                pagination.initial_offset.unwrap_or(0),
                if total {
                    ", and before any request whose offset has reached the most recently declared total"
                } else {
                    ""
                },
            );
            (
                format!(
                    "    /// Input for the next page request; `None` once the walk has ended.\n    next: std::option::Option<{operations}::{input}>,\n    /// Total declared by the most recent page, when the source maps one.\n    total: std::option::Option<i128>,"
                ),
                docs,
                prefix,
                advance,
                "client,\n        next: std::option::Option::Some(input),\n        total: std::option::Option::None,",
                "",
            )
        }
        Mode::Pointer => {
            let (previous_field, continuation_read) = if control.kind == ValueKind::Text {
                (
                    "std::option::Option<std::string::String>",
                    format!(
                        "let std::option::Option::Some(token) = {function}_page_continuation(data)\n            .filter(|token| !token.is_empty())\n        else {{\n            return std::result::Result::Ok(std::option::Option::Some(page));\n        }};\n        if self.previous.as_ref() == std::option::Option::Some(&token) {{\n            return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::UnexpectedResponse,\n                \"the source repeated a pagination continuation\",\n                std::option::Option::Some(token),\n            ));\n        }}"
                    ),
                )
            } else {
                (
                    "std::option::Option<i128>",
                    format!(
                        "let std::option::Option::Some(continuation) = {function}_page_continuation(data) else {{\n            return std::result::Result::Ok(std::option::Option::Some(page));\n        }};\n        if self.previous == std::option::Option::Some(continuation) {{\n            return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::UnexpectedResponse,\n                \"the source repeated a pagination continuation\",\n                std::option::Option::Some(continuation.to_string()),\n            ));\n        }}"
                    ),
                )
            };
            let advance = if control.kind == ValueKind::Text {
                format!(
                    "{}\n        self.previous = std::option::Option::Some(token);",
                    set_text(control, "rebuilt", "token.clone()")
                )
            } else {
                format!(
                    "{}\n        self.previous = std::option::Option::Some(continuation);",
                    set_i128(
                        control,
                        "rebuilt",
                        "continuation",
                        function,
                        "the advanced pagination offset is not representable",
                    )
                )
            };
            let prefix = format!(
                "let std::option::Option::Some(mut rebuilt) = self.next.take() else {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }};\n        {limit_fill}let page = {operations}::{function}(self.client, rebuilt.clone()).await?;\n        let data = {function}_page_data(&page);\n        {}{}",
                has_more_stop("Some(page)"),
                continuation_read,
            );
            let docs = format!(
                "/// Lazily walks every page of {path}.\n///\n/// Each `next` issues at most one request and awaits the transport directly:\n/// no tasks are spawned, the request starts only while the returned future is\n/// polled, and dropping the pager cancels a pending request without firing\n/// another one. The first call requests the input as given; every later call\n/// rebuilds the input with only the continuation control set to the declared\n/// next value. The walk stops when the continuation is absent{}, on a\n/// `has_more=false` page, and refuses to loop when the source repeats an\n/// identical continuation.",
                if control.kind == ValueKind::Text {
                    " or empty"
                } else {
                    ""
                },
            );
            (
                format!(
                    "    /// Input for the next page request; `None` once the walk has ended.\n    next: std::option::Option<{operations}::{input}>,\n    /// The continuation that produced the pending request; an identical\n    /// continuation refuses the walk instead of looping.\n    previous: {previous_field},"
                ),
                docs,
                prefix,
                advance,
                "client,\n        next: std::option::Option::Some(input),\n        previous,",
                previous_field,
            )
        }
        Mode::Increment => {
            let prefix = format!(
                "let std::option::Option::Some(mut rebuilt) = self.next.take() else {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }};\n        {limit_fill}let current = {};\n        let page = {operations}::{function}(self.client, rebuilt.clone()).await?;\n        let data = {function}_page_data(&page);\n        let count = {function}_page_items(data)\n            .map_or(0usize, |items| items.len());\n        if count == 0 {{\n            return std::result::Result::Ok(std::option::Option::Some(page));\n        }}\n        {}let advanced = match current.checked_add(1) {{\n            std::option::Option::Some(value) => value,\n            std::option::Option::None => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    \"pagination page overflow\",\n                    std::option::Option::None,\n                )),\n        }};",
                read_i128(
                    control,
                    "rebuilt",
                    Some("1"),
                    function,
                    "the page number is not representable",
                )
                .unwrap_or_default(),
                has_more_stop("Some(page)"),
            );
            let advance = set_i128(
                control,
                "rebuilt",
                "advanced",
                function,
                "the advanced page number is not representable",
            );
            let docs = format!(
                "/// Lazily walks every page of {path}.\n///\n/// Each `next` issues at most one request and awaits the transport directly:\n/// no tasks are spawned, the request starts only while the returned future is\n/// polled, and dropping the pager cancels a pending request without firing\n/// another one. The first call requests the input as given; every later call\n/// rebuilds the input with only the one-based page incremented (an absent\n/// page is assumed to be page 1). The walk stops on a zero-item page and on\n/// a `has_more=false` page.",
            );
            (
                format!(
                    "    /// Input for the next page request; `None` once the walk has ended.\n    next: std::option::Option<{operations}::{input}>,"
                ),
                docs,
                prefix,
                advance,
                "client,\n        next: std::option::Option::Some(input),",
                "",
            )
        }
    };
    let docs = format!("{docs}{fallback_doc}");
    let previous_seed = match mode {
        Mode::Pointer if control.kind == ValueKind::Text => {
            if control.required {
                format!(
                    "let previous = std::option::Option::Some(input.{}.clone());\n    ",
                    control.member
                )
            } else {
                format!("let previous = (input.{}).clone();\n    ", control.member)
            }
        }
        Mode::Pointer => format!(
            "let previous = {};\n    ",
            read_i128_option(control, "input").unwrap_or_default()
        ),
        _ => String::new(),
    };
    let _ = previous_type;
    format!(
        "\n{docs}\npub struct {pages}<'a, T> {{\n    client: &'a crate::http::Client<T>,\n{fields}\n}}\nimpl<'a, T: crate::http::Transport> {pages}<'a, T> {{\n    /// The next page, or `None` only after the walk has ended. The request\n    /// starts when the returned future is first polled.\n    pub async fn next(\n        &mut self,\n    ) -> std::result::Result<\n        std::option::Option<{operations}::{success}>,\n        {operations}::{error},\n    > {{\n        {prefix}\n        {advance}\n        self.next = std::option::Option::Some(rebuilt);\n        std::result::Result::Ok(std::option::Option::Some(page))\n    }}\n}}\n/// Start a page walk over `input`; the caller's initial pagination values are\n/// respected for the first request.\n#[must_use]\npub fn {function}_pages<'a, T: crate::http::Transport>(\n    client: &'a crate::http::Client<T>,\n    input: {operations}::{input},\n) -> {pages}<'a, T> {{\n    {previous_seed}{pages} {{\n        {constructor_fields}\n    }}\n}}\n"
    )
}

#[allow(clippy::too_many_arguments)]
fn items_pager_source(
    items_pager: &str,
    pages: &str,
    operations: &str,
    input: &str,
    error: &str,
    function: &str,
    element: &str,
) -> String {
    format!(
        "/// Flattens every item of every page into one pull iterator. Queued items\n/// are returned without a request; requests fire only when the previous\n/// page's items are exhausted, so dropping the pager (or stopping iteration)\n/// never fires another one.\npub struct {items_pager}<'a, T> {{\n    pages: {pages}<'a, T>,\n    queue: std::collections::VecDeque<{element}>,\n}}\nimpl<'a, T: crate::http::Transport> {items_pager}<'a, T> {{\n    /// The next item, or `None` only after the final page's final item.\n    pub async fn next(\n        &mut self,\n    ) -> std::result::Result<\n        std::option::Option<{element}>,\n        {operations}::{error},\n    > {{\n        loop {{\n            if let std::option::Option::Some(item) = self.queue.pop_front() {{\n                return std::result::Result::Ok(std::option::Option::Some(item));\n            }}\n            match self.pages.next().await? {{\n                std::option::Option::Some(page) => {{\n                    let data = {function}_page_data(&page);\n                    if let std::option::Option::Some(items) = {function}_page_items(data) {{\n                        self.queue.extend(items.iter().cloned());\n                    }}\n                }}\n                std::option::Option::None => {{\n                    return std::result::Result::Ok(std::option::Option::None);\n                }}\n            }}\n        }}\n    }}\n}}\n/// Start an item walk over `input`; the caller's initial pagination values\n/// are respected for the first request.\n#[must_use]\npub fn {function}_items<'a, T: crate::http::Transport>(\n    client: &'a crate::http::Client<T>,\n    input: {operations}::{input},\n) -> {items_pager}<'a, T> {{\n    {items_pager} {{\n        pages: {function}_pages(client, input),\n        queue: std::collections::VecDeque::new(),\n    }}\n}}\n"
    )
}

#[allow(clippy::too_many_arguments)]
fn next_page_source(
    mode: Mode,
    control: &Control,
    fallback_limit: Option<&Control>,
    initial_limit: Option<u32>,
    function: &str,
    operations: &str,
    input: &str,
    error: &str,
    has_more: bool,
    initial_offset: u32,
) -> String {
    let has_more_stop = |outcome: &str| {
        if !has_more {
            return String::new();
        }
        format!(
            "if {function}_page_has_more(data) == std::option::Option::Some(false) {{\n            return std::result::Result::Ok(std::option::Option::{outcome});\n        }}\n        "
        )
    };
    let fill = initial_fill(control, "input", initial_offset, function).unwrap_or_default();
    let limit_fill = match (fallback_limit, initial_limit) {
        (Some(limit), Some(size)) => {
            initial_limit_fill(limit, "input", size, function).unwrap_or_default()
        }
        _ => String::new(),
    };
    let limit_lead = if limit_fill.is_empty() {
        String::new()
    } else {
        format!("{limit_fill}\n        ")
    };
    let body = match mode {
        Mode::ItemsReturned => format!(
            "{limit_lead}{fill}\n        let base = {base};\n        let page = {operations}::{function}(client, input.clone()).await?;\n        let data = {function}_page_data(&page);\n        let count = {function}_page_items(data)\n            .map_or(0usize, |items| items.len());\n        if count == 0 {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }}\n        {stop}let advanced = match base.checked_add(count as i128) {{\n            std::option::Option::Some(value) => value,\n            std::option::Option::None => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    \"pagination offset overflow\",\n                    std::option::Option::None,\n                )),\n        }};\n        {set}\n        std::result::Result::Ok(std::option::Option::Some(input))",
            base = read_i128(
                control,
                "input",
                Some("0"),
                function,
                "the pagination offset is not representable"
            )
            .unwrap_or_default(),
            stop = has_more_stop("None"),
            set = set_i128(
                control,
                "input",
                "advanced",
                function,
                "the advanced pagination offset is not representable"
            ),
        ),
        Mode::Pointer if control.kind == ValueKind::Text => format!(
            "{limit_lead}let page = {operations}::{function}(client, input.clone()).await?;\n        let data = {function}_page_data(&page);\n        {stop}let std::option::Option::Some(token) = {function}_page_continuation(data)\n            .filter(|token| !token.is_empty())\n        else {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }};\n        if {guard} {{\n            return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::UnexpectedResponse,\n                \"the source repeated a pagination continuation\",\n                std::option::Option::Some(token),\n            ));\n        }}\n        {set}\n        std::result::Result::Ok(std::option::Option::Some(input))",
            stop = has_more_stop("None"),
            guard = if control.required {
                format!("token == input.{}", control.member)
            } else {
                format!(
                    "std::option::Option::Some(&token) == (input.{}).as_ref()",
                    control.member
                )
            },
            set = set_text(control, "input", "token"),
        ),
        Mode::Pointer => format!(
            "{limit_lead}let page = {operations}::{function}(client, input.clone()).await?;\n        let data = {function}_page_data(&page);\n        {stop}let std::option::Option::Some(continuation) = {function}_page_continuation(data) else {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }};\n        if {guard} == std::option::Option::Some(continuation) {{\n            return std::result::Result::Err({function}_pagination_error(\n                crate::http::SdkErrorKind::UnexpectedResponse,\n                \"the source repeated a pagination continuation\",\n                std::option::Option::Some(continuation.to_string()),\n            ));\n        }}\n        {set}\n        std::result::Result::Ok(std::option::Option::Some(input))",
            stop = has_more_stop("None"),
            guard = read_i128_option(control, "input").unwrap_or_default(),
            set = set_i128(
                control,
                "input",
                "continuation",
                function,
                "the advanced pagination offset is not representable"
            ),
        ),
        Mode::Increment => format!(
            "{limit_lead}let current = {current};\n        let page = {operations}::{function}(client, input.clone()).await?;\n        let data = {function}_page_data(&page);\n        let count = {function}_page_items(data)\n            .map_or(0usize, |items| items.len());\n        if count == 0 {{\n            return std::result::Result::Ok(std::option::Option::None);\n        }}\n        {stop}let advanced = match current.checked_add(1) {{\n            std::option::Option::Some(value) => value,\n            std::option::Option::None => return std::result::Result::Err({function}_pagination_error(\n                    crate::http::SdkErrorKind::RequestValidation,\n                    \"pagination page overflow\",\n                    std::option::Option::None,\n                )),\n        }};\n        {set}\n        std::result::Result::Ok(std::option::Option::Some(input))",
            current = read_i128(
                control,
                "input",
                Some("1"),
                function,
                "the page number is not representable"
            )
            .unwrap_or_default(),
            stop = has_more_stop("None"),
            set = set_i128(
                control,
                "input",
                "advanced",
                function,
                "the advanced page number is not representable"
            ),
        ),
    };
    format!(
        "/// Issue one request for `input` and return the rebuilt input that fetches\n/// the following page, or `None` when the walk would stop. Every input member\n/// except the pagination control is preserved; the request starts when the\n/// returned future is first polled.\npub async fn {function}_next_page<T: crate::http::Transport>(\n    client: &crate::http::Client<T>,\n    mut input: {operations}::{input},\n) -> std::result::Result<\n    std::option::Option<{operations}::{input}>,\n    {operations}::{error},\n> {{\n        {body}\n}}\n"
    )
}

fn client_methods(
    op: &PlannedOperation,
    pages: &str,
    items_pager: &str,
    operations: &str,
    input: &str,
    error: &str,
) -> String {
    format!(
        "    /// Walk every page of {}. See [`pagination::{pages}`].\n    #[must_use]\n    pub fn {}_pages(\n        &self,\n        input: {operations}::{input},\n    ) -> pagination::{pages}<'_, T> {{\n        pagination::{}_pages(self, input)\n    }}\n    /// Flatten every item of every page. See [`pagination::{items_pager}`].\n    #[must_use]\n    pub fn {}_items(\n        &self,\n        input: {operations}::{input},\n    ) -> pagination::{items_pager}<'_, T> {{\n        pagination::{}_items(self, input)\n    }}\n    /// Build the input for the page after `input` by issuing its request\n    /// once. See [`pagination::{}_next_page`].\n    pub async fn {}_next_page(\n        &self,\n        input: {operations}::{input},\n    ) -> std::result::Result<\n        std::option::Option<{operations}::{input}>,\n        {operations}::{error},\n    > {{\n        pagination::{}_next_page(self, input).await\n    }}\n",
        prose(&format!(
            "{} {}",
            op.wire().method().as_str(),
            op.wire().path()
        )),
        op.function_name,
        op.function_name,
        op.function_name,
        op.function_name,
        op.function_name,
        op.function_name,
        op.function_name,
    )
}
