//! Typed server stub generation: Rust (axum) and TypeScript (Express).
//!
//! Emits route registrations with typed request/response structs derived
//! from the contract. Handlers are `todo!()`/`throw` placeholders the
//! developer fills in; the generated types are compile-time-checked
//! against the wire schema.

use serde_json::Value;
use std::path::PathBuf;
use std::sync::Arc;

use suspect_ir::IrSpec;

/// Stub generation target and output path.
#[derive(Debug, clap::Args)]
pub struct StubsArgs {
    /// The OpenAPI document.
    #[arg(required = true)]
    pub input: PathBuf,
    /// Target framework: `rust-axum` or `ts-express`.
    #[arg(long, value_enum)]
    pub backend: StubBackend,
    /// Output directory.
    #[arg(long)]
    pub out: PathBuf,
}

/// Server stub backends.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum StubBackend {
    /// Rust + axum handlers and typed extractors.
    RustAxum,
    /// TypeScript + Express handlers and typed interfaces.
    TsExpress,
}

/// Loads the IR spec and dispatches to the backend emitter.
///
/// # Errors
/// Propagates workspace and IR compilation failures.
pub fn stubs(args: &StubsArgs) -> anyhow::Result<i32> {
    let absolute = args.input.canonicalize()?;
    let uri =
        suspect_source::Uri::from_path(&absolute).map_err(|e| anyhow::Error::msg(e.to_string()))?;
    let ws = Arc::new(
        suspect_ref::WorkspaceBuilder::new()
            .build()
            .map_err(|e| anyhow::Error::msg(e.to_string()))?,
    );
    ws.load_all(
        absolute
            .to_str()
            .ok_or_else(|| anyhow::anyhow!("input path is not UTF-8"))?,
    )
    .map_err(|e| anyhow::Error::msg(e.to_string()))?;
    let spec = IrSpec::from_workspace(&ws, &uri).map_err(|e| anyhow::Error::msg(e.to_string()))?;

    match args.backend {
        StubBackend::RustAxum => emit_rust_axum(&spec, &args.out)?,
        StubBackend::TsExpress => emit_ts_express(&spec, &args.out)?,
    }
    eprintln!(
        "stubs → {} ({} operations)",
        args.out.display(),
        spec.operations.len()
    );
    Ok(0)
}

/// JSON Schema type name → Rust type.
fn rust_type(schema: &serde_json::Value) -> String {
    if let Some(r#ref) = schema.get("$ref")
        && let Some(name) = r#ref.as_str().and_then(|s| s.rsplit('/').next())
    {
        return name.to_owned();
    }
    match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "String".to_owned(),
        Some("integer") if schema.get("format").and_then(|f| f.as_str()) == Some("int64") => {
            "i64".to_owned()
        }
        Some("integer") => "i32".to_owned(),
        Some("number") => "f64".to_owned(),
        Some("boolean") => "bool".to_owned(),
        Some("array") => {
            let items = schema
                .get("items")
                .cloned()
                .unwrap_or(serde_json::Value::Null);
            format!("Vec<{}>", rust_type(&items))
        }
        _ => "serde_json::Value".to_owned(),
    }
}

/// JSON Schema type name → TypeScript type.
fn ts_type(schema: &serde_json::Value) -> String {
    if let Some(r#ref) = schema.get("$ref")
        && let Some(name) = r#ref.as_str().and_then(|s| s.rsplit('/').next())
    {
        return name.to_owned();
    }
    match schema.get("type").and_then(|t| t.as_str()) {
        Some("string") => "string".to_owned(),
        Some("integer") | Some("number") => "number".to_owned(),
        Some("boolean") => "boolean".to_owned(),
        Some("array") => {
            let items = schema
                .get("items")
                .cloned()
                .unwrap_or(serde_json::Value::Null);
            format!("{}[]", ts_type(&items))
        }
        _ => "unknown".to_owned(),
    }
}

/// Converts a path template to a route pattern: `/pets/{petId}` → `/pets/:petId`.
fn axum_route(path: &str) -> String {
    path.replace('{', ":").replace('}', "")
}

/// Emits Rust axum stubs: a `routes.rs` with typed handlers.
fn emit_rust_axum(spec: &IrSpec, out_dir: &std::path::Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(out_dir)?;
    let mut code = String::from(
        "// Generated by suspect — typed axum server stubs.\n\
         // Handlers return `todo!()` — fill in the implementation.\n\
         use axum::{Router, routing, extract::Path, Json};\n\
         use serde::{Serialize, Deserialize};\n\n",
    );

    // Type definitions from component schemas.
    for schema in &spec.schemas {
        if let Some(props) = schema.json.get("properties").and_then(|p| p.as_object()) {
            code.push_str(&format!(
                "#[derive(Debug, Serialize, Deserialize)]\npub struct {name} {{\n",
                name = schema.name
            ));
            for (prop_name, prop_schema) in props {
                let required = schema
                    .json
                    .get("required")
                    .and_then(|r| r.as_array())
                    .map(|a| a.iter().any(|v| v.as_str() == Some(prop_name.as_str())))
                    .unwrap_or(false);
                let rust_t = rust_type(prop_schema);
                let field = if required {
                    format!("    pub {prop_name}: {rust_t},\n")
                } else {
                    format!("    pub {prop_name}: Option<{rust_t}>,\n")
                };
                code.push_str(&field);
            }
            code.push_str("}\n\n");
        }
    }

    // Handlers + routes.
    code.push_str("pub fn router() -> Router {\n    Router::new()\n");
    for op in &spec.operations {
        let fn_name = op.id.clone().unwrap_or_else(|| {
            format!(
                "{}{}",
                op.method.as_str().to_ascii_lowercase(),
                op.path.replace('/', "_").replace(['{', '}'], "")
            )
        });
        let handler = format!("handle_{}", fn_name);
        let method_lower = op.method.as_str().to_ascii_lowercase();
        let route = axum_route(&op.path);
        code.push_str(&format!(
            "    .route(\"{route}\", routing::{method_lower}({handler}))\n"
        ));
        code.push_str(&format!(
            "\nasync fn {handler}(Path(path_params): Path<std::collections::HashMap<String, String>>) -> Json<serde_json::Value> {{\n    // TODO: implement {} {}\n    Json(serde_json::json!({{\"todo\": true}}))\n}}\n\n",
            op.method.as_str(),
            op.path,
        ));
    }
    code.push_str("}\n");
    std::fs::write(out_dir.join("routes.rs"), code)?;
    Ok(())
}

/// Emits TypeScript Express stubs: typed handlers and interfaces.
fn emit_ts_express(spec: &IrSpec, out_dir: &std::path::Path) -> anyhow::Result<()> {
    std::fs::create_dir_all(out_dir)?;
    let mut code = String::from(
        "// Generated by suspect — typed Express server stubs.\n\
         // Handlers throw 'not implemented' — fill in the implementation.\n\
         import express, { Request, Response } from 'express';\n\n",
    );

    for schema in &spec.schemas {
        if let Some(props) = schema.json.get("properties").and_then(|p| p.as_object()) {
            let required: Vec<&str> = schema
                .json
                .get("required")
                .and_then(|r| r.as_array())
                .map(|a| a.iter().filter_map(Value::as_str).collect())
                .unwrap_or_default();
            code.push_str(&format!("export interface {} {{\n", schema.name));
            for (prop_name, prop_schema) in props {
                let ts_t = ts_type(prop_schema);
                let optional = if required.contains(&prop_name.as_str()) {
                    ""
                } else {
                    "?"
                };
                code.push_str(&format!("  {prop_name}{optional}: {ts_t};\n"));
            }
            code.push_str("}\n\n");
        }
    }

    code.push_str("const app = express();\napp.use(express.json());\n\n");
    for op in &spec.operations {
        let _fn_name = op.id.clone().unwrap_or_else(|| {
            format!(
                "{}{}",
                op.method.as_str().to_ascii_lowercase(),
                op.path.replace(['/', '{', '}'], "_")
            )
        });
        let method_lower = op.method.as_str().to_ascii_lowercase();
        let route = op.path.replace('{', ":").replace('}', "");
        code.push_str(&format!(
            "app.{method_lower}(\"{route}\", (req: Request, res: Response) => {{\n  // TODO: implement {} {}\n  res.status(501).json({{ error: \"not implemented\" }});\n}});\n\n",
            op.method.as_str(),
            op.path,
        ));
    }
    code.push_str("const PORT = process.env.PORT ?? 3000;\napp.listen(PORT, () => console.log(`listening on :${PORT}`));\n");
    std::fs::write(out_dir.join("server.ts"), code)?;
    Ok(())
}
